In [1]:
import pandas as pd

In [13]:
list_of_strings = ["Value 1", "Value 2", "Value 3"]
list_of_integers = [1, 3, 5]

In [15]:
series_of_strings = pd.Series(list_of_strings)

In [17]:
print(series_of_strings)

0    Value 1
1    Value 2
2    Value 3
dtype: object

In [19]:
labeled_series = pd.Series(list_of_integers, index = list_of_strings)

In [21]:
print(labeled_series)

Value 1    1
Value 2    3
Value 3    5
dtype: int64

In [31]:
verkaeufe = {"Tag 1": 120, "Tag 2": 330, "Tag 3": 250}
series_verkaeufe = pd.Series(verkaeufe)
print(verkaeufe)

{'Tag 1': 120, 'Tag 2': 330, 'Tag 3': 250}

In [55]:
series_verkaeufe

Tag 1    120
Tag 2    330
Tag 3    250
dtype: int64

In [59]:
for value in series_verkaeufe:
    print(value)

120
330
250

# DF Objekte

## DF aus Liste

In [63]:
data = {
    "list1": [20, 340, 320],
    "list2": [234, 12, 2]
}

df_1 = pd.DataFrame(data)
df_1

   list1  list2
0     20    234
1    340     12
2    320      2

In [66]:
merlin = {"Name": "Merlin", "Tierart": "Katze", "Alter" : 3, "Farbe": "schwarz"}
otto = {"Name": "Otto", "Tierart": "Hund", "Alter" : 5, "Farbe": "braun"}
renate = {"Name": "Renate", "Tierart": "Fisch", "Alter" : 2, "Farbe": "rot"}

In [68]:
df_tiere = pd.DataFrame([merlin, otto, renate])

In [70]:
df_tiere

     Name Tierart  Alter    Farbe
0  Merlin   Katze      3  schwarz
1    Otto    Hund      5    braun
2  Renate   Fisch      2      rot

In [72]:
verkaeufe = {"Tag 1": 120, "Tag 2": 330, "Tag 3": 250, "Tag 4": 270}
einnahmen = {"Tag 1": 450, "Tag 2": 1210, "Tag 3": 760, "Tag 4": 950, "Tag 5": 350}

# erstellen aus Liste von dictionaries:
df_4 = pd.DataFrame([verkaeufe, einnahmen], index = ["verkäufe", "einnahmen"])

In [74]:
df_4

           Tag 1  Tag 2  Tag 3  Tag 4  Tag 5
verkäufe     120    330    250    270    NaN
einnahmen    450   1210    760    950  350.0

In [76]:
# mit ".T" kann ein Dataframe transponiert werden, wir tauschen also Zeilen und Spalten
df_4_transposed = df_4.T

In [78]:
df_4_transposed

       verkäufe  einnahmen
Tag 1     120.0      450.0
Tag 2     330.0     1210.0
Tag 3     250.0      760.0
Tag 4     270.0      950.0
Tag 5       NaN      350.0

In [88]:
df = pd.read_csv("data/nyt_bestsellers.csv", names = ["index_number", "title", "category"], index_col=0)

In [90]:
df[:10]

                                                          title  category
index_number
1                   I Love Dad with The Very Hungry Caterpillar  children
2                              The Wonderful Things You Will Be  children
3                Dr. Seuss's I Love Pop!: A Celebration of Dads  children
4                                            Dragons Love Tacos  children
5                                      How to Babysit a Grandpa  children
6                                               I Wish You More  children
7                                                 Grumpy Monkey  children
8                                      The Day the Crayons Quit  children
9                                                    Dear Girl,  children
10            Rosie Revere, Engineer (Questioneers Collectio...  children

In [92]:
df_nyt = pd.read_json("data/nyt_bestseller.json")

In [94]:
df_nyt

,_id,bestsellers_date,published_date,amazon_product_url,author,description,price,publisher,title,rank,rank_last_week,weeks_on_list
0,{'$oid': '5b4aa4ead3089013507db18b'},{'$date': {'$numberLong': '1211587200000'}},{'$date': {'$numberLong': '1212883200000'}},http://www.amazon.com/Odd-Hours-Dean-Koontz/dp...,Dean R Koontz,"Odd Thomas, who can communicate with the dead,...",{'$numberInt': '27'},Bantam,ODD HOURS,{'$numberInt': '1'},{'$numberInt': '0'},{'$numberInt': '1'}
1,{'$oid': '5b4aa4ead3089013507db18c'},{'$date': {'$numberLong': '1211587200000'}},{'$date': {'$numberLong': '1212883200000'}},http://www.amazon.com/The-Host-Novel-Stephenie...,Stephenie Meyer,Aliens have taken control of the minds and bod...,{'$numberDouble': '25.99'},"Little, Brown",THE HOST,{'$numberInt': '2'},{'$numberInt': '1'},{'$numberInt': '3'}
2,{'$oid': '5b4aa4ead3089013507db18d'},{'$date': {'$numberLong': '1211587200000'}},{'$date': {'$numberLong': '1212883200000'}},http://www.amazon.com/Love-Youre-With-Emily-Gi...,Emily Giffin,A woman's happy marriage is shaken when she en...,{'$numberDouble': '24.95'},St. Martin's,LOVE THE ONE YOU'RE WITH,{'$numberInt': '3'},{'$numberInt': '2'},{'$numberInt': '2'}
3,{'$oid': '5b4aa4ead3089013507db18e'},{'$date': {'$numberLong': '1211587200000'}},{'$date': {'$numberLong': '1212883200000'}},http://www.amazon.com/The-Front-Garano-Patrici...,Patricia Cornwell,A Massachusetts state investigator and his tea...,{'$numberDouble': '22.95'},Putnam,THE FRONT,{'$numberInt': '4'},{'$numberInt': '0'},{'$numberInt': '1'}
4,{'$oid': '5b4aa4ead3089013507db18f'},{'$date': {'$numberLong': '1211587200000'}},{'$date': {'$numberLong': '1212883200000'}},http://www.amazon.com/Snuff-Chuck-Palahniuk/dp...,Chuck Palahniuk,An aging porn queens aims to cap her career by...,{'$numberDouble': '24.95'},Doubleday,SNUFF,{'$numberInt': '5'},{'$numberInt': '0'},{'$numberInt': '1'}
...,...,...,...,...,...,...,...,...,...,...,...,...
95,{'$oid': '5b4aa4ead3089013507db1ea'},{'$date': {'$numberLong': '1214006400000'}},{'$date': {'$numberLong': '1215302400000'}},http://www.amazon.com/Blood-Anita-Blake-Vampir...,Laurell K Hamilton,The vampire hunter Anita Blake is involved in ...,{'$numberDouble': '25.95'},Berkley,BLOOD NOIR,{'$numberInt': '16'},{'$numberInt': '12'},{'$numberInt': '4'}
96,{'$oid': '5b4aa4ead3089013507db1eb'},{'$date': {'$numberLong': '1214006400000'}},{'$date': {'$numberLong': '1215302400000'}},http://www.amazon.com/Snuff-Chuck-Palahniuk/dp...,Chuck Palahniuk,An aging porn queens aims to cap her career by...,{'$numberInt': '0'},Doubleday,SNUFF,{'$numberInt': '17'},{'$numberInt': '0'},{'$numberInt': '0'}
97,{'$oid': '5b4aa4ead3089013507db1ec'},{'$date': {'$numberLong': '1214006400000'}},{'$date': {'$numberLong': '1215302400000'}},http://www.amazon.com/Death-Honor-Bound-Book/d...,W E B Griffin and William E Butterworth IV,A Marine pilot spies in Argentina in 1943; th...,{'$numberInt': '0'},Putnam,DEATH AND HONOR,{'$numberInt': '18'},{'$numberInt': '0'},{'$numberInt': '0'}
98,{'$oid': '5b4aa4ead3089013507db1ed'},{'$date': {'$numberLong': '1214006400000'}},{'$date': {'$numberLong': '1215302400000'}},http://www.amazon.com/The-Spies-Warsaw-A-Novel...,Alan Furst,Intrigue in Poland just before World War II.,{'$numberInt': '0'},Random House,THE SPIES OF WARSAW,{'$numberInt': '19'},{'$numberInt': '0'},{'$numberInt': '0'}
99,{'$oid': '5b4aa4ead3089013507db1ee'},{'$date': {'$numberLong': '1214006400000'}},{'$date': {'$numberLong': '1215302400000'}},http://www.amazon.com/Phantom-Prey-John-Sandfo...,John Sandford,The Minneapolis detective Lucas Davenport inve...,{'$numberInt': '0'},Putnam,PHANTOM PREY,{'$numberInt': '20'},{'$numberInt': '0'},{'$numberInt': '0'}

In [100]:
df_nyt.bestsellers_date[4]

{'$date': {'$numberLong': '1211587200000'}}