# Aufgabe Teilmodul 2.1
## Auswahl Ihrer Daten
Suchen Sie auf bibsonomy mit einem selbst gewählten Suchbegriff nach Publikationen. Auf Bibsonomy lassen sich die Ergebnisse einer Keyword-Suche (z.B. "Bibliothek") in einer Vielzahl verschiedener Formate exportieren (Limit ggf. vorher auf 1000 erhöhen) und lokal speichern. Geben Sie dafür einen Suchbegriff oben rechts in die Maske ein und bestätigen Sie die Eingabe. Rechts neben der Überschrift der rechten Spalte ("publications"/"Publikationen") klicken Sie ganz rechte auf das Symbol mit dem Pfeil nach rechts, der aus einem Kasten zeigt ("export options for displayed posts"/"Exportieren für angezeigte Einträge"), dann auf mehr/more. Wählen Sie ZUERST bei posts/Einträge "1000" aus, und wählen sie dann in dem Format drop-Down-Menü fast ganz unten JSON aus. Es öffnet sich die JSON Datei in ihrem Browser.  Sie können die URL wie im Tutorial über das requests Modul in Python öffnen.

Alternativ können Sie die Datei auch lokal speichern. Dafür rechtsklicken Sie irgendwo, wählen Sie "save as..."/"speichern unter..." und speichern Sie die Datei unter einem passenden Dateinamen mit der Endung ".json".

Für eine Nutzung im zweiten Modulteil ist ein großer Datensatz sinnvoll. Fügen Sie daher die Ergebnisse mehrerer Suchen mit Pandas in einem Datensatz zusammenführen.
Fügen sie ihren Datensätzen dabei den Suchterm hinzu, der zu den Ergebnissen geführt hat. Tipp: Informationen dazu finden Sie unter "Daten Verändern und Hinzufügen".

Nutzen sie dabei Python (vorzugsweise in einem Jupyter Notebook) mithilfe von Pandas. Sollten Sie Probleme haben, schauen Sie im Pandas Tutorial unter "JSON einlesen" oder bitten Sie Fabian Haak im Moodle Austauschforum um Hilfe.
Legen Sie Ihr Notebook bzw. Python-Script mit den Lösungen in einem "Modul_2-1" Ordner im eigenen Repositorium auf GitHub ab. Fügen Sie mich als zusätzlichen Collaborator (GitHub-Name: HaakFab) hinzu, so kann ich besser Feedback oder Hilfestellungen geben.

## Exportformat erstellen
Diese Aufgabe dient als direkte Vorbereitung des nächsten Modulteils. Wir empfehlen, Pandas für die Bearbeitung der Aufgabe zu nutzen. 

### Datenaufbereitung
Für den nächsten Teil dieses Modules möchten wir unseren Datensatz wieder als JSON-File ablegen. Zunächst möchten wir aber die Bibsonomy-Daten noch etwas zu bereinigen:
- Filtern Sie die Daten so, dass nur noch Einträge des Typs "Publication" enthalten sind.
- Überlegen Sie, welche Felder Sie möglicherweise umbenennen wollen, und welche Sie nicht benötigen. Benennen Sie entsprechend um und wählen Sie nur die Spalten, die für Sie sinnvolle Informationen enthalten. Mögliche Änderungen der Daten sind das Umbenennen von Felder zu eindeutigeren Bezeichnungen (wie beispielsweise im Pandas Tutorial "label" zu "title"). Filtern Sie ihre Daten jedoch nicht zu drastisch und entfernen Sie nicht zu viele Felder, damit im zweiten Modulteil noch genügend Informationen übrig bleiben.
- Wenn sie mehrere Suchergebnisse zusammengeführt haben, ist es sinnvoll, Nachduplikaten zu überprüfen.
- BONUS: Wie bei den Jareszahlen ist es durchaus sinnvoll, zu überprüfen, ob alle Einträge "sauber" vorliegen. Stellen sie dafür sicher, dass alle Einträge Informationen zu Titel, AutorInnen und Veröffentlichungsjahr enthalten und dass das Jahr eine sinnvolle Zahl ist!
Daten Export

### Erstellen Sie einen sauberen Export im JSON-Format, das von Solr akzeptiert wird.

Für die Weiterverwendung ist nicht relevant, wie die einzelnen Felder benannt sind oder wie viele Felder es gibt, Es ist aber entscheidend, dass die äußere Form einer Liste von Dictionaries gewahrt wird. (HINWEIS BEI PROBLEMEN: Schauen Sie im Pandas Tutorial unter "Export als JSON")

In [63]:
import pandas as pd
import requests

# zum Zusammenbauen der Bibsonomy URL brauchen wir alles, was vor und nach der Query kommt
url_base = "https://www.bibsonomy.org/json/search/"
url_attr = "?items=1000"

def df_from_query(query):
    # die URL; wir müssen Leerzeichen ersetzen mit "%20" nach ASCII Encoding guideline
    url = url_base + query.replace(" ", "%20") + url_attr
    
    result = requests.get(url)
    json_data = result.json()
    
    # im Feld "items" stecken die relevanten Dateneinträge
    dataframe = pd.DataFrame(json_data["items"])

    # wir filtern so, dass nur Publikationen bleiben
    dataframe.loc[dataframe["type"] == "Publication"]

    # wir möchten die query in die Daten eintragen 
    dataframe["query"] = query
    
    # die Rückgabe der Methode nicht vergessen:
    return dataframe

# wir erstellen eine leere Liste, in die wir unsere Dataframes packen
dataframes = []

# eine Liste von Suchanfragen
queries = ["artificial intelligence", "AI", "machine learning", "language model", "KI", "künstliche intelligenz", "maschinelles lernen", "sprachmodell"]

# jetzt gehen wir die Liste von Suchanfragen durch und rufen unsere Funktion für jede Suchanfrage auf
for query in queries:
    df = df_from_query(query)
    # schließlich fügen wir das DataFrame über append unserer Liste von Dataframes hinzu
    dataframes.append(df)

    # wie wir uns eine Statusausgabe schreiben würden:
    # print("Ergebnisse für ", query , " gefunden. Dataframe enthält ",len(df), " Einträge.")
    
    # mit einem f String lassen sich Variablen in Strings viel einfacher formatieren:
    print(f"{len(df)} Ergebnisse für query {query} gefunden.")

2000 Ergebnisse für query artificial intelligence gefunden.
2000 Ergebnisse für query AI gefunden.
2000 Ergebnisse für query machine learning gefunden.
1311 Ergebnisse für query language model gefunden.
1410 Ergebnisse für query KI gefunden.
1275 Ergebnisse für query künstliche intelligenz gefunden.
295 Ergebnisse für query maschinelles lernen gefunden.
30 Ergebnisse für query sprachmodell gefunden.

In [64]:
# Da die dataframes die selbe From (column titles sind identisch, wenn für alle vorhanden) haben, können wir die Dataframes über concat zusammenfügen
data_conc = pd.concat(dataframes, ignore_index=True)

#### Filtern Sie die Daten so, dass nur noch Einträge des Typs "Publication" enthalten sind.

#### Überlegen Sie, welche Felder Sie möglicherweise umbenennen wollen, und welche Sie nicht benötigen.

#### Benennen Sie entsprechend um und wählen Sie nur die Spalten, die für Sie sinnvolle Informationen enthalten. Mögliche Änderungen der Daten sind das Umbenennen von Felder zu eindeutigeren Bezeichnungen (wie beispielsweise im Pandas Tutorial "label" zu "title").

#### Wenn sie mehrere Suchergebnisse zusammengeführt haben, ist es sinnvoll, nach Duplikaten zu überprüfen.

#### SABINE:
- Sollte man Dublikate vor dem Merge entfernen lassen oder lieber danach?

#### BONUS: Wie bei den Jareszahlen ist es durchaus sinnvoll, zu überprüfen, ob alle Einträge "sauber" vorliegen. Stellen sie dafür sicher, dass alle Einträge Informationen zu Titel, AutorInnen und Veröffentlichungsjahr enthalten und dass das Jahr eine sinnvolle Zahl ist!

### Wenn noch Zeit ist (sonst: wird nachgereicht!)

#### LARA:
- habe bei der Autoren-Spalte alle NaN Einträge rausgelöscht später aber festgestellt, dass ich noch solche Einträge habe: [?]
Wie könnte ich diese rausfiltern und löschen sodass ich am Ende nur Namen in der Spalte habe?
- in der Spalte "language" hatte ich Titel auf deutsch und englisch. Deutsche Titel hatten bspws. folgende Werte: dt, ger, german
Wie kann ich diese Werte alle in "deutsch" umbenennen?



1. Language Spalte säubern --> nur noch EN oder DE als Werte! Bei keiner angabe EN eintragen

## PAUSE

# Gruppenaufgabe 1
### Aufgabenbeschreibung
Wir möchten nun zusätzlich zu den Bibsonomy Daten auch noch Daten aus einer weiteren Quelle zusammenführen, in diesem Fall Semantic Scholar.

1. Lade "bibsonomy.json" und "semantic_scholar.json" in Pandas als ein Dataframe, füge eine Spalte "source" hinzu, in der du festhälst, woher die Suchergebnisse kommen  (also: bibsonomy oder semantic_scholar).
2. Selektiere und benenne die Spalten so um, dass aus beiden Quellen Titel, Autoren, URL, Abstract, Keywords, Query (Suchanfrage) sowie das Jahr enthalten und gleich benannt sind.
3. Stelle sicher, dass die Autoren gleich als Liste formatiert sind (also z. B. [Max Mustermann, Lieschen Müller] oder [Mustermann M., Müller L.]).
4. Führe die Datensätze zusammen.
5. Stelle sicher, dass alle Einträge für "Jahr" eine 4-stellige Zahl (int) sind.
6. Entferne Duplikate (anhand der Spalte Title).
7. Sorge dafür, dass es einen durchgängigen Index gibt.

In [96]:
import pandas as pd
import numpy as np

In [8]:
df_bib = pd.read_json('data/bibsonomy.json')
df_sem = pd.read_json('data/semantic_scholar.json')

In [12]:
df_bib["source"] = 'bibsonomy'
df_sem["source"] = 'semantic_scholar'

In [32]:
df_sem.head()

,index,paperId,externalIds,publicationVenue,url,title,abstract,venue,year,referenceCount,...,isOpenAccess,openAccessPdf,fieldsOfStudy,publicationTypes,publicationDate,journal,citationStyles,authors,searchQuery,source
0,0,574beee702be3856d60aa482ec725168fe64fc99,"{'ArXiv': '2303.12712', 'DBLP': 'journals/corr...","{'id': '1901e811-ee72-4b20-8f7e-de08cd395a10',...",https://www.semanticscholar.org/paper/574beee7...,Sparks of Artificial General Intelligence: Ear...,Artificial intelligence (AI) researchers have ...,arXiv.org,2023,0,...,True,"{'url': 'http://arxiv.org/pdf/2303.12712', 'st...",[Computer Science],[JournalArticle],2023-03-22,"{'name': 'ArXiv', 'volume': 'abs/2303.12712'}","{'bibtex': '@Article{Bubeck2023SparksOA, auth...","[{'authorId': '121645690', 'name': 'Sébastien ...",artificial intelligence,semantic_scholar
1,1,e1d2f2a717aa03280126f87c8e5fad695f52bf7c,"{'DOI': '10.48047/ijfans/v12/i1/271', 'CorpusI...","{'id': '50c199ea-1ec5-4c24-a902-d9ce8d810efa',...",https://www.semanticscholar.org/paper/e1d2f2a7...,Explainable Artificial Intelligence (XAI),Explainable Artificial Intelligence (XAI) has ...,International Journal of Food and Nutritional ...,2023,33,...,True,{'url': 'https://www.ijfans.org/uploads/paper/...,None,[JournalArticle],2023-10-26,{'name': 'international journal of food and nu...,"{'bibtex': '@Article{Sewada2023ExplainableAI, ...","[{'authorId': '2151645335', 'name': 'Ranu Sewa...",artificial intelligence,semantic_scholar
2,2,530a059cb48477ad1e3d4f8f4b153274c8997332,"{'ArXiv': '1910.10045', 'DBLP': 'journals/inff...","{'id': '06afdd0b-0d85-413f-af8a-c3045c12c561',...",https://www.semanticscholar.org/paper/530a059c...,Explainable Artificial Intelligence (XAI): Con...,None,Information Fusion,2019,430,...,True,{'url': 'https://bird.bcamath.org/bitstream/20...,[Computer Science],"[JournalArticle, Review]",2019-10-22,"{'name': 'Inf. Fusion', 'pages': '82-115', 'vo...","{'bibtex': '@Article{Arrieta2019ExplainableAI,...","[{'authorId': '1379511816', 'name': 'Alejandro...",artificial intelligence,semantic_scholar
3,3,de4b9bc12ddb6b9f6090c032ef5c6290bd64ef36,"{'DBLP': 'conf/bnaic/2017', 'MAG': '2895834617...","{'id': '82cd90f0-386f-4446-b237-6404c27f6a15',...",https://www.semanticscholar.org/paper/de4b9bc1...,Artificial Intelligence,None,Communications in Computer and Information Sci...,2017,27,...,True,None,[Computer Science],[Review],None,{'volume': '823'},{'bibtex': '@Inproceedings{Verheij2017Artifici...,"[{'authorId': '1697177', 'name': 'Bart Verheij...",artificial intelligence,semantic_scholar
4,4,f134abeaf9bfd41f29b97aec675ec31895bf541d,"{'MAG': '2908201961', 'DOI': '10.1038/s41591-0...","{'id': '9e995b6d-f30b-4ab4-a13b-3dc2cc992f47',...",https://www.semanticscholar.org/paper/f134abea...,High-performance medicine: the convergence of ...,None,Nature Network Boston,2019,227,...,False,None,"[Computer Science, Medicine]","[Review, JournalArticle]",2019-01-01,"{'name': 'Nature Medicine', 'pages': '44 - 56'...",{'bibtex': '@Article{Topol2019HighperformanceM...,"[{'authorId': '144758045', 'name': 'E. Topol'}]",artificial intelligence,semantic_scholar

In [26]:
df_bib.columns

Index(['id', 'tags', 'query', 'title', 'description', 'date', 'url', 'year',
       'author', 'authors', 'text', 'pages', 'abstract', 'source'],
      dtype='object')

In [28]:
df_sem.columns

Index(['index', 'paperId', 'externalIds', 'publicationVenue', 'url', 'title',
       'abstract', 'venue', 'year', 'referenceCount', 'citationCount',
       'influentialCitationCount', 'isOpenAccess', 'openAccessPdf',
       'fieldsOfStudy', 'publicationTypes', 'publicationDate', 'journal',
       'citationStyles', 'authors', 'searchQuery', 'source'],
      dtype='object')

In [36]:
useful_bib_columns = ['title', 'authors', 'url', 'abstract', 'query', 'year', 'source']
useful_sem_columns = ['title', 'authors', 'url', 'abstract', 'searchQuery', 'year', 'source']

In [42]:
df_bib_filtered = df_bib[useful_bib_columns]
df_sem_filtered = df_sem[useful_sem_columns]

In [50]:
df_bib_filtered.columns

Index(['title', 'authors', 'url', 'abstract', 'query', 'year', 'source'], dtype='object')

In [48]:
df_sem_filtered.columns

Index(['title', 'authors', 'url', 'abstract', 'searchQuery', 'year', 'source'], dtype='object')

In [52]:
df_sem_filtered = df_sem_filtered.rename(columns={'searchQuery' : 'query'})

In [62]:
df_merged = pd.concat([df_bib_filtered, df_sem_filtered], ignore_index=True, sort=False)

In [64]:
df_merged

,title,authors,url,abstract,query,year,source
0,Artificial Intelligence in Agriculture,[{'first': 'Matthew N. O. Sadiku | Sarhan M. M...,https://www.ijtsrd.com/engineering/electrical-...,Artificial Intelligence is one of the emerging...,artificial intelligence,2021,bibsonomy
1,Artificial Intelligence Benefit and Risks,"[{'first': 'Seeta M.', 'last': 'Chauhan'}]",https://www.ijtsrd.com/computer-science/artifi...,this article demonstrate Disadvantage of artif...,artificial intelligence,2020,bibsonomy
2,Artificial Intelligence in Power Station,[{'first': 'P. Naveen | S. Nikitha | P. Sudees...,https://www.ijtsrd.com/engineering/electrical-...,With increased competitiveness in power genera...,artificial intelligence,2019,bibsonomy
3,Artificial Intelligence Based Training and Pla...,[{'first': 'Krishanu Deb | Pankaj Agrawal | Ha...,http://www.ijtsrd.com/computer-science/artific...,Training and placement cell in colleges is to ...,artificial intelligence,2018,bibsonomy
4,The Significance of Artificial Intelligence in...,"[{'first': 'Dr. Atul Kumar', 'last': 'Mishra'}]",https://www.ijtsrd.com/computer-science/artifi...,"In an increasingly digitalized world, the util...",artificial intelligence,2023,bibsonomy
...,...,...,...,...,...,...,...
8274,Phonologically Aware Neural Model for Named En...,"[{'authorId': '2528900', 'name': 'Akash Bharad...",https://www.semanticscholar.org/paper/f1a8ff55...,Named Entity Recognition is a well established...,large language model,2016,semantic_scholar
8275,Large-Scale Distributed Language Modeling,"[{'authorId': '35797272', 'name': 'Ahmad Emami...",https://www.semanticscholar.org/paper/591080c3...,A novel distributed language model that has no...,large language model,2007,semantic_scholar
8276,BERT for Joint Intent Classification and Slot ...,"[{'authorId': '47261124', 'name': 'Qian Chen'}...",https://www.semanticscholar.org/paper/476029ac...,Intent classification and slot filling are two...,large language model,2019,semantic_scholar
8277,Language and Translation Model Adaptation usin...,"[{'authorId': '32278254', 'name': 'M. Snover'}...",https://www.semanticscholar.org/paper/b281a9d0...,"Traditionally, statistical machine translation...",large language model,2008,semantic_scholar
8278,Commonsense Knowledge Mining from Pretrained M...,"[{'authorId': '2072080518', 'name': 'Joshua Fe...",https://www.semanticscholar.org/paper/f98e1359...,Inferring commonsense knowledge is a key chall...,large language model,2019,semantic_scholar

In [68]:
df_merged['year'].unique()

array(['2021', '2020', '2019', '2018', '2023', '1994', '2022', '2017',
       '2014', '1973', '2003', '1995', '2007', '2015', '1997', '2010',
       '1985', '1992', '1990', '1999', '1993', '2000', '1987', '1991',
       '2011', '1996', '2004', '2005', '2016', '2013', '1977', '1976',
       '2002', '1982', '2012', '2008', '1989', '1984', '1988', '2009',
       '1986', '1980', '1979', '2006', '1998', '1974', '1970', '1981',
       '1975', '{2006}', '2024', '1963', '2001', '1961', '1962', '1983',
       '1958', '1972', '{2010}', '1978', '1960', 2023, 2019, 2017, 2018,
       2020, 2022, 2021, 2014, 2016, 2015, 2001, 2002, 2007, 2003, 2013,
       2000, 2012, 2010, 2011, 2008, 2005, 2009, 2004, 2006], dtype=object)

In [80]:
df_merged['year'] = df_merged['year'].astype(int)

In [88]:
df_merged['year'].unique()

array([2021, 2020, 2019, 2018, 2023, 1994, 2022, 2017, 2014, 1973, 2003,
       1995, 2007, 2015, 1997, 2010, 1985, 1992, 1990, 1999, 1993, 2000,
       1987, 1991, 2011, 1996, 2004, 2005, 2016, 2013, 1977, 1976, 2002,
       1982, 2012, 2008, 1989, 1984, 1988, 2009, 1986, 1980, 1979, 2006,
       1998, 1974, 1970, 1981, 1975, 2024, 1963, 2001, 1961, 1962, 1983,
       1958, 1972, 1978, 1960])

In [108]:
df_merged_dropped = df_merged.drop_duplicates(subset='title')

In [110]:
df_merged_dropped.index.unique()

Index([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
       ...
       8267, 8268, 8269, 8270, 8271, 8272, 8273, 8274, 8275, 8276],
      dtype='int64', length=4740)

In [112]:
df_merged_dropped

,title,authors,url,abstract,query,year,source
1,Artificial Intelligence in Agriculture,[{'first': 'Matthew N. O. Sadiku | Sarhan M. M...,https://www.ijtsrd.com/engineering/electrical-...,Artificial Intelligence is one of the emerging...,artificial intelligence,2021,bibsonomy
2,Artificial Intelligence Benefit and Risks,"[{'first': 'Seeta M.', 'last': 'Chauhan'}]",https://www.ijtsrd.com/computer-science/artifi...,this article demonstrate Disadvantage of artif...,artificial intelligence,2020,bibsonomy
3,Artificial Intelligence in Power Station,[{'first': 'P. Naveen | S. Nikitha | P. Sudees...,https://www.ijtsrd.com/engineering/electrical-...,With increased competitiveness in power genera...,artificial intelligence,2019,bibsonomy
4,Artificial Intelligence Based Training and Pla...,[{'first': 'Krishanu Deb | Pankaj Agrawal | Ha...,http://www.ijtsrd.com/computer-science/artific...,Training and placement cell in colleges is to ...,artificial intelligence,2018,bibsonomy
5,The Significance of Artificial Intelligence in...,"[{'first': 'Dr. Atul Kumar', 'last': 'Mishra'}]",https://www.ijtsrd.com/computer-science/artifi...,"In an increasingly digitalized world, the util...",artificial intelligence,2023,bibsonomy
...,...,...,...,...,...,...,...
8272,Phonologically Aware Neural Model for Named En...,"[{'authorId': '2528900', 'name': 'Akash Bharad...",https://www.semanticscholar.org/paper/f1a8ff55...,Named Entity Recognition is a well established...,large language model,2016,semantic_scholar
8273,Large-Scale Distributed Language Modeling,"[{'authorId': '35797272', 'name': 'Ahmad Emami...",https://www.semanticscholar.org/paper/591080c3...,A novel distributed language model that has no...,large language model,2007,semantic_scholar
8274,BERT for Joint Intent Classification and Slot ...,"[{'authorId': '47261124', 'name': 'Qian Chen'}...",https://www.semanticscholar.org/paper/476029ac...,Intent classification and slot filling are two...,large language model,2019,semantic_scholar
8275,Language and Translation Model Adaptation usin...,"[{'authorId': '32278254', 'name': 'M. Snover'}...",https://www.semanticscholar.org/paper/b281a9d0...,"Traditionally, statistical machine translation...",large language model,2008,semantic_scholar
8276,Commonsense Knowledge Mining from Pretrained M...,"[{'authorId': '2072080518', 'name': 'Joshua Fe...",https://www.semanticscholar.org/paper/f98e1359...,Inferring commonsense knowledge is a key chall...,large language model,2019,semantic_scholar

In [116]:
df_merged_dropped.index = np.arange(1, len(df_merged_dropped) + 1)

In [118]:
df_merged_dropped.index

Index([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
       ...
       4731, 4732, 4733, 4734, 4735, 4736, 4737, 4738, 4739, 4740],
      dtype='int64', length=4740)