In [1]:
import pyterrier as pt
import requests
import pandas as pd
import pickle
import nltk
import numpy as np

In [3]:
query = 'artificial intelligence'
url = f"https://www.bibsonomy.org/json/search/{query}?items=1000"

In [5]:
res = requests.get(url)

In [6]:
data = res.json()

In [7]:
df_ai = pd.DataFrame(data["items"])
df_ai = df_ai[df_ai["type"] == "Publication"]

In [8]:
df_ai_filtered = df_ai.dropna(axis=1, thresh=len(df_ai)*0.5)

In [9]:
df_ai_filtered.columns

Index(['type', 'id', 'tags', 'intraHash', 'label', 'user', 'description',
       'date', 'changeDate', 'count', 'url', 'interHash', 'pub-type', 'year',
       'author', 'authors', 'volume', 'pages', 'bibtexKey', 'publisher'],
      dtype='object')

In [10]:
useful_columns = ['id', 'tags', 'label', 'description', 'date', 'changeDate', 'url', 'pub-type', 'year', 'author', 'authors', 'publisher']
df_ai_filtered = df_ai_filtered[useful_columns]

In [11]:
# initialise pyterrier
if not pt.started():
    pt.init()

/var/folders/88/9blsh45918g8y3n5vl6vztxr0000gq/T/ipykernel_2339/1219906578.py:2: DeprecationWarning: Call to deprecated function (or staticmethod) started. (use pt.java.started() instead) -- Deprecated since version 0.11.0.
  if not pt.started():
Java started and loaded: pyterrier.java, pyterrier.terrier.java [version=5.10 (build: craigm 2024-08-22 17:33), helper_version=0.0.8]
/var/folders/88/9blsh45918g8y3n5vl6vztxr0000gq/T/ipykernel_2339/1219906578.py:3: DeprecationWarning: Call to deprecated method pt.init(). Deprecated since version 0.11.0.
java is now started automatically with default settings. To force initialisation early, run:
pt.java.init() # optional, forces java initialisation
  pt.init()

In [21]:
df_ai_filtered['docno'] = df_ai_filtered['id']
df_ai_filtered['text'] = df_ai_filtered['label']

In [27]:
index_folder = "./ai_index"

indexer = pt.DFIndexer(index_folder, overwrite=True)
index_ref = indexer.index(df_ai_filtered['text'], df_ai_filtered['docno'])

print(f"path to our index: {index_ref.toString()}")

/var/folders/88/9blsh45918g8y3n5vl6vztxr0000gq/T/ipykernel_2339/1545029842.py:3: DeprecationWarning: Call to deprecated class DFIndexer. (use pt.terrier.IterDictIndexer().index(dataframe.to_dict(orient='records')) instead) -- Deprecated since version 0.11.0.
  indexer = pt.DFIndexer(index_folder, overwrite=True)

path to our index: ./ai_index/data.properties

In [29]:
index = pt.IndexFactory.of(index_ref)

In [31]:
print(index.getCollectionStatistics().toString())

Number of documents: 1000
Number of terms: 1433
Number of postings: 6208
Number of fields: 0
Number of tokens: 6441
Field names: []
Positions:   false

In [33]:
#term -> term_id Nt Tf
#Nt: In how many documents does the term occur 
#TF: How often does the term occur in total (Termfrequenz)

for kv in index.getLexicon():
    print(f"{kv.getKey()} -> {kv.getValue().toString()}")

0 -> term12 Nt=5 TF=6 maxTF=2 @{0 0 0}
02 -> term569 Nt=1 TF=1 maxTF=1 @{0 8 1}
1 -> term1006 Nt=1 TF=1 maxTF=1 @{0 10 1}
10 -> term1032 Nt=2 TF=2 maxTF=1 @{0 12 5}
10th -> term516 Nt=2 TF=2 maxTF=1 @{0 16 5}
11 -> term1096 Nt=2 TF=2 maxTF=1 @{0 20 7}
11th -> term1166 Nt=4 TF=4 maxTF=1 @{0 25 5}
12 -> term475 Nt=1 TF=1 maxTF=1 @{0 32 7}
12th -> term1091 Nt=4 TF=4 maxTF=1 @{0 34 7}
13 -> term1164 Nt=1 TF=1 maxTF=1 @{0 42 1}
13th -> term1247 Nt=3 TF=3 maxTF=1 @{0 44 5}
14 -> term1031 Nt=1 TF=1 maxTF=1 @{0 50 1}
14th -> term1033 Nt=4 TF=4 maxTF=1 @{0 52 5}
15th -> term1038 Nt=4 TF=4 maxTF=1 @{0 60 3}
16 -> term1314 Nt=1 TF=1 maxTF=1 @{0 67 5}
16th -> term897 Nt=4 TF=4 maxTF=1 @{0 70 1}
17 -> term1163 Nt=1 TF=1 maxTF=1 @{0 77 3}
17th -> term952 Nt=4 TF=4 maxTF=1 @{0 79 7}
18 -> term1255 Nt=2 TF=2 maxTF=1 @{0 86 5}
185 -> term709 Nt=2 TF=2 maxTF=1 @{0 90 5}
18th -> term570 Nt=3 TF=3 maxTF=1 @{0 93 5}
19 -> term209 Nt=4 TF=4 maxTF=1 @{0 99 7}
1955 -> term965 Nt=1 TF=1 maxTF=1 @{0 107 1}
1970 -> term707 Nt=2 TF=2 maxTF=1 @{0 109 3}
1971 -> term706 Nt=2 TF=2 maxTF=1 @{0 112 3}
1988 -> term1426 Nt=1 TF=2 maxTF=2 @{0 115 3}
1993 -> term1423 Nt=1 TF=2 maxTF=2 @{0 118 0}
1997 -> term1170 Nt=1 TF=1 maxTF=1 @{0 120 5}
1998 -> term1167 Nt=1 TF=1 maxTF=1 @{0 123 1}
1999 -> term1093 Nt=1 TF=1 maxTF=1 @{0 125 5}
19th -> term949 Nt=4 TF=4 maxTF=1 @{0 128 1}
2 -> term717 Nt=9 TF=9 maxTF=1 @{0 136 1}
20 -> term605 Nt=3 TF=3 maxTF=1 @{0 148 3}
2000 -> term1307 Nt=1 TF=1 maxTF=1 @{0 154 1}
2001 -> term1035 Nt=1 TF=2 maxTF=2 @{0 156 5}
2002 -> term1036 Nt=1 TF=2 maxTF=2 @{0 159 2}
2003 -> term575 Nt=3 TF=4 maxTF=2 @{0 161 7}
2004 -> term295 Nt=2 TF=3 maxTF=2 @{0 168 0}
2005 -> term956 Nt=2 TF=4 maxTF=2 @{0 172 1}
2006 -> term607 Nt=5 TF=7 maxTF=2 @{0 176 5}
2007 -> term1016 Nt=1 TF=2 maxTF=2 @{0 186 1}
2008 -> term1003 Nt=3 TF=6 maxTF=2 @{0 188 6}
2010 -> term1244 Nt=1 TF=1 maxTF=1 @{0 195 5}
2011 -> term375 Nt=3 TF=5 maxTF=2 @{0 198 1}
2012 -> term1077 Nt=2 TF=4 maxTF=3 @{0 204 7}
2013 -> term165 Nt=2 TF=2 maxTF=1 @{0 209 1}
2014 -> term163 Nt=3 TF=3 maxTF=1 @{0 213 1}
2015 -> term1126 Nt=2 TF=3 maxTF=2 @{0 218 7}
2016 -> term1146 Nt=2 TF=4 maxTF=3 @{0 223 6}
2017 -> term1334 Nt=1 TF=1 maxTF=1 @{0 227 2}
2018 -> term517 Nt=1 TF=2 maxTF=2 @{0 229 6}
2019 -> term362 Nt=1 TF=2 maxTF=2 @{0 231 7}
2020 -> term999 Nt=1 TF=1 maxTF=1 @{0 234 0}
2021 -> term973 Nt=2 TF=4 maxTF=2 @{0 236 4}
2022 -> term881 Nt=4 TF=5 maxTF=2 @{0 241 0}
2023 -> term755 Nt=4 TF=8 maxTF=2 @{0 248 3}
2024 -> term1187 Nt=1 TF=2 maxTF=2 @{0 256 3}
20th -> term1017 Nt=3 TF=3 maxTF=1 @{0 259 0}
21 -> term604 Nt=4 TF=4 maxTF=1 @{0 265 2}
21st -> term46 Nt=3 TF=3 maxTF=1 @{0 271 6}
22 -> term1124 Nt=5 TF=5 maxTF=1 @{0 277 0}
22nd -> term363 Nt=2 TF=2 maxTF=1 @{0 284 6}
23 -> term360 Nt=3 TF=3 maxTF=1 @{0 289 0}
23rd -> term1205 Nt=1 TF=1 maxTF=1 @{0 294 0}
24 -> term1076 Nt=4 TF=4 maxTF=1 @{0 296 4}
24th -> term379 Nt=3 TF=3 maxTF=1 @{0 303 4}
25 -> term359 Nt=4 TF=4 maxTF=1 @{0 310 2}
25th -> term1193 Nt=2 TF=2 maxTF=1 @{0 317 6}
26 -> term753 Nt=5 TF=5 maxTF=1 @{0 322 0}
26th -> term1188 Nt=2 TF=2 maxTF=1 @{0 331 6}
27 -> term1161 Nt=3 TF=3 maxTF=1 @{0 336 4}
27th -> term166 Nt=1 TF=1 maxTF=1 @{0 342 2}
28 -> term1152 Nt=3 TF=3 maxTF=1 @{0 343 6}
29 -> term1143 Nt=1 TF=1 maxTF=1 @{0 349 4}
2nd -> term441 Nt=7 TF=7 maxTF=1 @{0 352 0}
3 -> term623 Nt=6 TF=6 maxTF=1 @{0 361 4}
30 -> term752 Nt=4 TF=4 maxTF=1 @{0 371 0}
31 -> term964 Nt=2 TF=2 maxTF=1 @{0 379 2}
34th -> term972 Nt=1 TF=1 maxTF=1 @{0 383 4}
35th -> term915 Nt=1 TF=1 maxTF=1 @{0 385 6}
36th -> term1082 Nt=1 TF=1 maxTF=1 @{0 388 0}
3d -> term852 Nt=1 TF=1 maxTF=1 @{0 390 4}
3rd -> term1228 Nt=2 TF=2 maxTF=1 @{0 392 6}
4 -> term11 Nt=17 TF=17 maxTF=1 @{0 397 0}
4099 -> term826 Nt=1 TF=1 maxTF=1 @{0 418 4}
5 -> term380 Nt=7 TF=7 maxTF=1 @{0 420 6}
50 -> term743 Nt=1 TF=1 maxTF=1 @{0 432 2}
50th -> term741 Nt=1 TF=1 maxTF=1 @{0 434 4}
5g -> term1404 Nt=1 TF=1 maxTF=1 @{0 436 6}
6 -> term170 Nt=6 TF=6 maxTF=1 @{0 439 2}
60th -> term271 Nt=2 TF=2 maxTF=1 @{0 449 6}
6g -> term820 Nt=2 TF=2 maxTF=1 @{0 451 6}
7 -> term1099 Nt=2 TF=2 maxTF=1 @{0 456 2}
7th -> term249 Nt=1 TF=1 maxTF=1 @{0 461 0}
8 -> term378 Nt=3 TF=3 maxTF=1 @{0 462 6}
9 -> term169 Nt=4 TF=4 maxTF=1 @{0 468 6}
900mhz -> term935 Nt=1 TF=1 maxTF=1 @{0 476 4}
97 -> term1168 Nt=1 TF=1 maxTF=1 @{0 478 6}
98 -> term1165 Nt=1 TF=1 maxTF=1 @{0 481 2}
99 -> term1092 Nt=1 TF=1 maxTF=1 @{0 483 6}
9th -> term828 Nt=1 TF=1 maxTF=1 @{0 486 2}
aaai -> term292 Nt=2 TF=2 maxTF=1 @{0 488 4}
abuja -> term226 Nt=2 TF=2 maxTF=1 @{0 492 2}
academ -> term320 Nt=1 TF=1 maxTF=1 @{0 496 2}
accept -> term413 Nt=1 TF=1 maxTF=1 @{0 498 0}
access -> term745 Nt=1 TF=1 maxTF=1 @{0 500 0}
accord -> term138 Nt=1 TF=1 maxTF=1 @{0 502 2}
accur -> term451 Nt=1 TF=1 maxTF=1 @{0 503 6}
achiev -> term564 Nt=2 TF=2 maxTF=1 @{0 505 6}
across -> term68 Nt=2 TF=2 maxTF=1 @{0 510 0}
act -> term696 Nt=2 TF=2 maxTF=1 @{0 513 4}
action -> term1398 Nt=1 TF=1 maxTF=1 @{0 518 0}
actor -> term179 Nt=1 TF=1 maxTF=1 @{0 520 4}
acut -> term823 Nt=3 TF=3 maxTF=1 @{0 522 0}
adapt -> term254 Nt=8 TF=8 maxTF=1 @{0 525 4}
adelaid -> term1034 Nt=1 TF=1 maxTF=1 @{0 536 2}
adjust -> term1128 Nt=1 TF=1 maxTF=1 @{0 538 6}
adopt -> term734 Nt=1 TF=1 maxTF=1 @{0 541 2}
advanc -> term173 Nt=24 TF=24 maxTF=1 @{0 543 4}
advantag -> term373 Nt=3 TF=3 maxTF=1 @{0 571 6}
advent -> term256 Nt=2 TF=2 maxTF=1 @{0 576 4}
adversari -> term1114 Nt=1 TF=1 maxTF=1 @{0 580 2}
aerial -> term778 Nt=1 TF=1 maxTF=1 @{0 582 6}
aerospac -> term299 Nt=2 TF=2 maxTF=1 @{0 585 0}
aesthet -> term1133 Nt=2 TF=2 maxTF=1 @{0 589 0}
affect -> term303 Nt=2 TF=2 maxTF=1 @{0 593 4}
ag -> term156 Nt=8 TF=8 maxTF=1 @{0 597 4}
agenc -> term423 Nt=2 TF=2 maxTF=1 @{0 610 2}
agent -> term442 Nt=11 TF=11 maxTF=1 @{0 614 4}
agi -> term609 Nt=1 TF=1 maxTF=1 @{0 631 2}
agil -> term884 Nt=1 TF=1 maxTF=1 @{0 633 2}
agricultur -> term1 Nt=1 TF=1 maxTF=1 @{0 635 4}
ai -> term102 Nt=62 TF=63 maxTF=2 @{0 635 6}
aim -> term41 Nt=3 TF=3 maxTF=1 @{0 693 3}
air -> term909 Nt=1 TF=1 maxTF=1 @{0 697 3}
al -> term168 Nt=1 TF=1 maxTF=1 @{0 699 5}
alberta -> term1306 Nt=1 TF=1 maxTF=1 @{0 701 1}
algebra -> term1046 Nt=1 TF=1 maxTF=1 @{0 703 5}
algorithm -> term150 Nt=14 TF=15 maxTF=2 @{0 706 1}
alicant -> term1078 Nt=1 TF=1 maxTF=1 @{0 724 6}
alloc -> term1060 Nt=1 TF=1 maxTF=1 @{0 727 2}
alphazero -> term131 Nt=1 TF=1 maxTF=1 @{0 729 6}
alt -> term521 Nt=1 TF=1 maxTF=1 @{0 731 2}
ambient -> term1095 Nt=1 TF=1 maxTF=1 @{0 733 2}
america -> term1002 Nt=1 TF=1 maxTF=1 @{0 735 6}
amsterdam -> term1254 Nt=1 TF=1 maxTF=1 @{0 738 2}
analog -> term981 Nt=3 TF=3 maxTF=1 @{0 740 6}
analysi -> term16 Nt=27 TF=27 maxTF=1 @{0 745 4}
analyz -> term846 Nt=2 TF=2 maxTF=1 @{0 778 0}
andcclassif -> term847 Nt=1 TF=1 maxTF=1 @{0 781 6}
android -> term798 Nt=1 TF=1 maxTF=1 @{0 784 0}
andromeda -> term620 Nt=1 TF=1 maxTF=1 @{0 786 2}
anim -> term1347 Nt=1 TF=1 maxTF=1 @{0 788 4}
anniversari -> term272 Nt=4 TF=4 maxTF=1 @{0 791 0}
annot -> term984 Nt=4 TF=4 maxTF=1 @{0 797 2}
anomali -> term1209 Nt=4 TF=4 maxTF=1 @{0 801 2}
answer -> term1224 Nt=1 TF=1 maxTF=1 @{0 806 2}
anti -> term558 Nt=3 TF=3 maxTF=1 @{0 808 6}
antidot -> term996 Nt=1 TF=1 maxTF=1 @{0 814 4}
antimicrobi -> term345 Nt=1 TF=1 maxTF=1 @{0 817 0}
apex -> term728 Nt=1 TF=1 maxTF=1 @{0 818 6}
appli -> term151 Nt=3 TF=3 maxTF=1 @{0 821 0}
applic -> term42 Nt=49 TF=49 maxTF=1 @{0 827 2}
apprais -> term341 Nt=1 TF=1 maxTF=1 @{0 872 4}
approach -> term189 Nt=45 TF=45 maxTF=1 @{0 874 2}
archaeolog -> term1379 Nt=1 TF=1 maxTF=1 @{0 916 6}
architectur -> term608 Nt=8 TF=8 maxTF=1 @{0 919 2}
archon -> term1023 Nt=2 TF=2 maxTF=1 @{0 933 6}
arduino -> term1264 Nt=1 TF=1 maxTF=1 @{0 937 0}
area -> term228 Nt=4 TF=4 maxTF=1 @{0 939 4}
argument -> term997 Nt=4 TF=4 maxTF=1 @{0 947 2}
arm -> term1263 Nt=2 TF=2 maxTF=1 @{0 955 0}
arpa -> term708 Nt=2 TF=2 maxTF=1 @{0 959 4}
art -> term47 Nt=7 TF=8 maxTF=2 @{0 962 4}
artifact -> term832 Nt=1 TF=1 maxTF=1 @{0 974 3}
artifici -> term2 Nt=869 TF=931 maxTF=3 @{0 976 5}
artist -> term1181 Nt=2 TF=2 maxTF=1 @{0 1227 7}
aspect -> term698 Nt=3 TF=3 maxTF=1 @{0 1232 1}
assess -> term239 Nt=7 TF=7 maxTF=1 @{0 1236 3}
assist -> term113 Nt=6 TF=6 maxTF=1 @{0 1248 5}
associ -> term357 Nt=16 TF=16 maxTF=1 @{0 1257 7}
astro2020 -> term416 Nt=1 TF=1 maxTF=1 @{0 1275 5}
atla -> term647 Nt=2 TF=2 maxTF=1 @{0 1277 5}
attack -> term766 Nt=3 TF=3 maxTF=1 @{0 1281 3}
attempt -> term284 Nt=1 TF=1 maxTF=1 @{0 1287 1}
attend -> term1365 Nt=1 TF=1 maxTF=1 @{0 1288 7}
attent -> term145 Nt=1 TF=1 maxTF=1 @{0 1291 3}
auckland -> term1004 Nt=1 TF=1 maxTF=1 @{0 1292 7}
audienc -> term1342 Nt=1 TF=1 maxTF=1 @{0 1295 3}
audit -> term548 Nt=1 TF=1 maxTF=1 @{0 1297 7}
augment -> term417 Nt=4 TF=4 maxTF=1 @{0 1299 7}
august -> term968 Nt=4 TF=4 maxTF=1 @{0 1307 5}
australasian -> term381 Nt=2 TF=2 maxTF=1 @{0 1315 1}
australia -> term374 Nt=12 TF=12 maxTF=1 @{0 1319 3}
australian -> term898 Nt=10 TF=10 maxTF=1 @{0 1332 7}
authent -> term1070 Nt=1 TF=1 maxTF=1 @{0 1343 5}
autoaiviz -> term1109 Nt=1 TF=1 maxTF=1 @{0 1346 1}
autom -> term148 Nt=6 TF=6 maxTF=1 @{0 1348 5}
automat -> term740 Nt=1 TF=1 maxTF=1 @{0 1357 1}
autonom -> term92 Nt=3 TF=3 maxTF=1 @{0 1359 3}
autonomi -> term836 Nt=2 TF=2 maxTF=1 @{0 1365 3}
avatar -> term1134 Nt=1 TF=1 maxTF=1 @{0 1368 5}
avoid -> term930 Nt=1 TF=1 maxTF=1 @{0 1371 1}
awar -> term1178 Nt=1 TF=1 maxTF=1 @{0 1373 3}
axiom -> term785 Nt=1 TF=1 maxTF=1 @{0 1375 7}
back -> term1256 Nt=1 TF=1 maxTF=1 @{0 1378 1}
banff -> term1305 Nt=1 TF=1 maxTF=1 @{0 1380 5}
bank -> term109 Nt=3 TF=3 maxTF=1 @{0 1383 1}
bankruptci -> term1318 Nt=1 TF=1 maxTF=1 @{0 1388 5}
barcelona -> term1123 Nt=3 TF=3 maxTF=1 @{0 1391 1}
barrier -> term1355 Nt=1 TF=1 maxTF=1 @{0 1396 1}
base -> term29 Nt=53 TF=54 maxTF=2 @{0 1398 5}
basi -> term902 Nt=1 TF=1 maxTF=1 @{0 1451 6}
basic -> term78 Nt=1 TF=1 maxTF=1 @{0 1454 0}
bayesian -> term289 Nt=9 TF=9 maxTF=1 @{0 1455 2}
be -> term731 Nt=1 TF=1 maxTF=1 @{0 1469 2}
behavior -> term537 Nt=4 TF=4 maxTF=1 @{0 1471 4}
belief -> term1156 Nt=4 TF=4 maxTF=1 @{0 1478 6}
benefici -> term1375 Nt=1 TF=1 maxTF=1 @{0 1484 4}
benefit -> term6 Nt=3 TF=3 maxTF=1 @{0 1487 0}
benet -> term1276 Nt=1 TF=1 maxTF=1 @{0 1491 2}
best -> term1362 Nt=2 TF=2 maxTF=1 @{0 1493 6}
bibliographi -> term615 Nt=1 TF=1 maxTF=1 @{0 1498 0}
bid -> term941 Nt=1 TF=1 maxTF=1 @{0 1500 2}
big -> term275 Nt=4 TF=5 maxTF=2 @{0 1502 4}
biochemistri -> term447 Nt=1 TF=1 maxTF=1 @{0 1510 3}
bioinformat -> term809 Nt=1 TF=1 maxTF=1 @{0 1512 3}
biolog -> term911 Nt=5 TF=5 maxTF=1 @{0 1514 5}
biologi -> term562 Nt=7 TF=7 maxTF=1 @{0 1521 7}
biomed -> term1210 Nt=1 TF=1 maxTF=1 @{0 1531 1}
biometr -> term1354 Nt=1 TF=1 maxTF=1 @{0 1533 5}
black -> term533 Nt=1 TF=1 maxTF=1 @{0 1536 1}
blackbox -> term1108 Nt=1 TF=1 maxTF=1 @{0 1538 1}
blockchain -> term484 Nt=5 TF=6 maxTF=2 @{0 1540 5}
book -> term788 Nt=2 TF=2 maxTF=1 @{0 1550 0}
boon -> term211 Nt=1 TF=1 maxTF=1 @{0 1553 6}
boost -> term1378 Nt=1 TF=1 maxTF=1 @{0 1555 4}
bottom -> term1132 Nt=1 TF=1 maxTF=1 @{0 1558 0}
bound -> term892 Nt=1 TF=1 maxTF=1 @{0 1560 4}
box -> term531 Nt=1 TF=1 maxTF=1 @{0 1562 6}
brain -> term600 Nt=4 TF=4 maxTF=1 @{0 1564 6}
brazilian -> term869 Nt=1 TF=1 maxTF=1 @{0 1571 4}
breast -> term522 Nt=2 TF=2 maxTF=1 @{0 1573 6}
breed -> term688 Nt=1 TF=1 maxTF=1 @{0 1578 0}
bridg -> term939 Nt=1 TF=1 maxTF=1 @{0 1580 2}
bring -> term1235 Nt=1 TF=1 maxTF=1 @{0 1582 4}
brisban -> term1162 Nt=1 TF=1 maxTF=1 @{0 1585 0}
broad -> term1026 Nt=1 TF=1 maxTF=1 @{0 1587 4}
broadband -> term1320 Nt=1 TF=1 maxTF=1 @{0 1590 0}
broadcast -> term1066 Nt=1 TF=1 maxTF=1 @{0 1592 4}
brutu -> term436 Nt=1 TF=1 maxTF=1 @{0 1595 0}
build -> term250 Nt=6 TF=6 maxTF=1 @{0 1597 0}
built -> term595 Nt=1 TF=1 maxTF=1 @{0 1606 4}
burden -> term628 Nt=1 TF=1 maxTF=1 @{0 1608 4}
busi -> term325 Nt=4 TF=4 maxTF=1 @{0 1610 6}
cai -> term702 Nt=2 TF=2 maxTF=1 @{0 1618 2}
caibda -> term1313 Nt=1 TF=1 maxTF=1 @{0 1622 4}
cairn -> term951 Nt=1 TF=1 maxTF=1 @{0 1625 0}
call -> term944 Nt=1 TF=1 maxTF=1 @{0 1627 2}
cambridg -> term1239 Nt=1 TF=1 maxTF=1 @{0 1629 4}
camera -> term1105 Nt=1 TF=1 maxTF=1 @{0 1632 0}
can -> term344 Nt=10 TF=10 maxTF=1 @{0 1634 4}
canada -> term171 Nt=4 TF=4 maxTF=1 @{0 1649 0}
canadian -> term164 Nt=4 TF=7 maxTF=2 @{0 1656 4}
canai -> term1084 Nt=1 TF=1 maxTF=1 @{0 1663 5}
canberra -> term1037 Nt=1 TF=1 maxTF=1 @{0 1666 1}
cancer -> term523 Nt=5 TF=5 maxTF=1 @{0 1668 5}
capabl -> term777 Nt=1 TF=1 maxTF=1 @{0 1676 5}
capit -> term1385 Nt=1 TF=1 maxTF=1 @{0 1678 7}
caption -> term1401 Nt=1 TF=1 maxTF=1 @{0 1681 3}
captur -> term462 Nt=1 TF=1 maxTF=1 @{0 1683 7}
car -> term1048 Nt=1 TF=1 maxTF=1 @{0 1685 7}
card -> term938 Nt=1 TF=1 maxTF=1 @{0 1688 3}
cardiac -> term496 Nt=4 TF=4 maxTF=1 @{0 1690 5}
cardiolog -> term93 Nt=1 TF=1 maxTF=1 @{0 1695 7}
care -> term1087 Nt=2 TF=2 maxTF=1 @{0 1697 1}
carlo -> term963 Nt=1 TF=1 maxTF=1 @{0 1701 3}
case -> term260 Nt=7 TF=7 maxTF=1 @{0 1703 5}
castl -> term1097 Nt=1 TF=1 maxTF=1 @{0 1714 7}
catalan -> term365 Nt=15 TF=15 maxTF=1 @{0 1717 3}
catalogu -> term761 Nt=1 TF=1 maxTF=1 @{0 1734 5}
catalonia -> term519 Nt=6 TF=6 maxTF=1 @{0 1736 7}
catalyz -> term51 Nt=1 TF=1 maxTF=1 @{0 1743 3}
categori -> term1131 Nt=1 TF=1 maxTF=1 @{0 1744 3}
caus -> term928 Nt=1 TF=1 maxTF=1 @{0 1746 7}
causabl -> term1195 Nt=1 TF=1 maxTF=1 @{0 1749 1}
causal -> term1252 Nt=2 TF=2 maxTF=1 @{0 1751 5}
ccia -> term358 Nt=7 TF=7 maxTF=1 @{0 1755 1}
celebr -> term1192 Nt=1 TF=1 maxTF=1 @{0 1765 1}
cell -> term448 Nt=2 TF=2 maxTF=1 @{0 1767 5}
censu -> term1000 Nt=1 TF=1 maxTF=1 @{0 1771 7}
center -> term510 Nt=2 TF=2 maxTF=1 @{0 1774 3}
centric -> term1348 Nt=1 TF=1 maxTF=1 @{0 1777 7}
centuri -> term50 Nt=2 TF=2 maxTF=1 @{0 1780 3}
cervic -> term931 Nt=1 TF=2 maxTF=2 @{0 1783 7}
chain -> term307 Nt=2 TF=2 maxTF=1 @{0 1786 2}
challeng -> term111 Nt=19 TF=19 maxTF=1 @{0 1790 2}
chang -> term506 Nt=3 TF=3 maxTF=1 @{0 1814 6}
changer -> term194 Nt=1 TF=1 maxTF=1 @{0 1820 4}
character -> term1138 Nt=2 TF=2 maxTF=1 @{0 1822 2}
charl -> term1304 Nt=1 TF=1 maxTF=1 @{0 1825 6}
chatbot -> term978 Nt=1 TF=1 maxTF=1 @{0 1828 2}
chatgpt -> term597 Nt=4 TF=4 maxTF=1 @{0 1830 4}
check -> term736 Nt=1 TF=1 maxTF=1 @{0 1837 6}
china -> term1085 Nt=3 TF=3 maxTF=1 @{0 1840 0}
cim -> term1337 Nt=1 TF=1 maxTF=1 @{0 1845 2}
citi -> term866 Nt=1 TF=1 maxTF=1 @{0 1847 6}
classif -> term337 Nt=5 TF=5 maxTF=1 @{0 1850 0}
classifi -> term1259 Nt=1 TF=1 maxTF=1 @{0 1858 6}
clean -> term185 Nt=1 TF=1 maxTF=1 @{0 1861 2}
clinic -> term323 Nt=6 TF=6 maxTF=1 @{0 1863 0}
clone -> term1271 Nt=1 TF=1 maxTF=1 @{0 1873 0}
close -> term1219 Nt=2 TF=2 maxTF=1 @{0 1875 4}
cloud -> term525 Nt=4 TF=4 maxTF=1 @{0 1879 6}
cluster -> term1135 Nt=1 TF=1 maxTF=1 @{0 1887 0}
coalesc -> term796 Nt=1 TF=1 maxTF=1 @{0 1889 4}
coast -> term1015 Nt=1 TF=1 maxTF=1 @{0 1891 6}
code -> term1040 Nt=1 TF=1 maxTF=1 @{0 1894 2}
cognit -> term566 Nt=7 TF=7 maxTF=1 @{0 1896 6}
collabor -> term430 Nt=4 TF=4 maxTF=1 @{0 1908 4}
collect -> term1332 Nt=1 TF=1 maxTF=1 @{0 1916 0}
colleg -> term903 Nt=1 TF=1 maxTF=1 @{0 1918 4}
colloqui -> term330 Nt=1 TF=1 maxTF=1 @{0 1920 6}
combat -> term432 Nt=2 TF=2 maxTF=1 @{0 1922 4}
combin -> term444 Nt=5 TF=5 maxTF=1 @{0 1926 4}
comic -> term619 Nt=1 TF=1 maxTF=1 @{0 1936 0}
commerc -> term116 Nt=1 TF=1 maxTF=1 @{0 1938 2}
commerci -> term258 Nt=1 TF=1 maxTF=1 @{0 1939 6}
common -> term513 Nt=2 TF=2 maxTF=1 @{0 1941 4}
commonsens -> term1251 Nt=1 TF=1 maxTF=1 @{0 1945 2}
commun -> term412 Nt=2 TF=2 maxTF=1 @{0 1947 6}
compani -> term676 Nt=2 TF=2 maxTF=1 @{0 1952 0}
compar -> term56 Nt=1 TF=1 maxTF=1 @{0 1955 6}
comparison -> term1294 Nt=1 TF=1 maxTF=1 @{0 1957 0}
compat -> term834 Nt=1 TF=1 maxTF=1 @{0 1959 4}
compendium -> term712 Nt=1 TF=1 maxTF=1 @{0 1961 6}
compet -> term1119 Nt=3 TF=3 maxTF=1 @{0 1964 0}
complex -> term839 Nt=6 TF=6 maxTF=1 @{0 1968 2}
composit -> term1028 Nt=1 TF=1 maxTF=1 @{0 1977 0}
comprehens -> term105 Nt=6 TF=6 maxTF=1 @{0 1979 4}
comput -> term75 Nt=33 TF=35 maxTF=2 @{0 1989 0}
concept -> term300 Nt=5 TF=5 maxTF=1 @{0 2026 2}
conceptu -> term797 Nt=3 TF=3 maxTF=1 @{0 2034 6}
concis -> term1237 Nt=1 TF=1 maxTF=1 @{0 2040 2}
condit -> term1110 Nt=1 TF=1 maxTF=1 @{0 2042 6}
conf -> term571 Nt=1 TF=1 maxTF=1 @{0 2045 2}
confer -> term161 Nt=75 TF=75 maxTF=1 @{0 2047 2}
connect -> term633 Nt=1 TF=1 maxTF=1 @{0 2100 4}
connection -> term858 Nt=1 TF=1 maxTF=1 @{0 2102 6}
consciou -> term1207 Nt=1 TF=1 maxTF=1 @{0 2105 0}
conscious -> term262 Nt=5 TF=6 maxTF=2 @{0 2107 4}
constitut -> term652 Nt=1 TF=1 maxTF=1 @{0 2114 3}
constraint -> term399 Nt=1 TF=1 maxTF=1 @{0 2116 5}
construct -> term729 Nt=3 TF=3 maxTF=1 @{0 2118 5}
consumpt -> term252 Nt=1 TF=1 maxTF=1 @{0 2124 3}
content -> term590 Nt=3 TF=3 maxTF=1 @{0 2126 1}
context -> term327 Nt=5 TF=7 maxTF=2 @{0 2132 5}
contextsensit -> term971 Nt=1 TF=1 maxTF=1 @{0 2138 7}
contrast -> term864 Nt=1 TF=1 maxTF=1 @{0 2141 1}
control -> term343 Nt=11 TF=11 maxTF=1 @{0 2143 3}
converg -> term873 Nt=1 TF=1 maxTF=1 @{0 2160 7}
convers -> term1316 Nt=2 TF=2 maxTF=1 @{0 2163 1}
convolut -> term1408 Nt=1 TF=1 maxTF=1 @{0 2167 1}
cooper -> term1211 Nt=2 TF=2 maxTF=1 @{0 2169 5}
coordin -> term403 Nt=3 TF=3 maxTF=1 @{0 2173 7}
corpor -> term1212 Nt=1 TF=1 maxTF=1 @{0 2179 7}
correl -> term1080 Nt=1 TF=1 maxTF=1 @{0 2182 3}
corrupt -> term290 Nt=1 TF=1 maxTF=1 @{0 2184 7}
cosmolog -> term407 Nt=1 TF=1 maxTF=1 @{0 2186 5}
cost -> term646 Nt=3 TF=3 maxTF=1 @{0 2188 5}
countermeasur -> term1417 Nt=1 TF=1 maxTF=1 @{0 2194 5}
cours -> term390 Nt=3 TF=3 maxTF=1 @{0 2197 1}
court -> term286 Nt=1 TF=1 maxTF=1 @{0 2202 5}
cover -> term747 Nt=2 TF=2 maxTF=1 @{0 2204 3}
coverag -> term937 Nt=1 TF=1 maxTF=1 @{0 2208 3}
covid -> term213 Nt=2 TF=2 maxTF=1 @{0 2210 5}
creat -> term1039 Nt=2 TF=2 maxTF=1 @{0 2214 5}
creation -> term160 Nt=2 TF=2 maxTF=1 @{0 2218 5}
creativ -> term48 Nt=6 TF=6 maxTF=1 @{0 2220 3}
critic -> term585 Nt=4 TF=4 maxTF=1 @{0 2230 5}
critiqu -> term982 Nt=1 TF=1 maxTF=1 @{0 2237 5}
cross -> term1369 Nt=1 TF=1 maxTF=1 @{0 2239 7}
crossdisciplinari -> term795 Nt=1 TF=1 maxTF=1 @{0 2242 3}
crowd -> term661 Nt=2 TF=2 maxTF=1 @{0 2244 5}
crude -> term205 Nt=1 TF=1 maxTF=1 @{0 2249 1}
cryptocurr -> term342 Nt=1 TF=1 maxTF=1 @{0 2250 7}
cryptographi -> term1343 Nt=2 TF=2 maxTF=1 @{0 2252 5}
csa -> term933 Nt=1 TF=1 maxTF=1 @{0 2256 1}
cscw -> term602 Nt=1 TF=1 maxTF=1 @{0 2258 3}
cultur -> term959 Nt=2 TF=2 maxTF=1 @{0 2260 3}
curios -> term35 Nt=1 TF=1 maxTF=1 @{0 2264 5}
current -> term518 Nt=2 TF=2 maxTF=1 @{0 2265 5}
curv -> term660 Nt=1 TF=1 maxTF=1 @{0 2269 3}
cyber -> term1179 Nt=1 TF=1 maxTF=1 @{0 2271 5}
cybersecur -> term540 Nt=3 TF=3 maxTF=1 @{0 2274 1}
cyborg -> term1240 Nt=1 TF=1 maxTF=1 @{0 2280 3}
dagstuhl -> term1100 Nt=1 TF=1 maxTF=1 @{0 2282 7}
dartmouth -> term966 Nt=1 TF=1 maxTF=1 @{0 2285 3}
data -> term225 Nt=19 TF=20 maxTF=2 @{0 2287 5}
databas -> term445 Nt=4 TF=4 maxTF=1 @{0 2313 0}
dc -> term606 Nt=1 TF=1 maxTF=1 @{0 2319 2}
ddo -> term767 Nt=1 TF=1 maxTF=1 @{0 2321 2}
de -> term1245 Nt=3 TF=3 maxTF=1 @{0 2323 4}
debat -> term750 Nt=1 TF=1 maxTF=1 @{0 2329 6}
decad -> term311 Nt=1 TF=1 maxTF=1 @{0 2332 0}
deceiv -> term488 Nt=1 TF=1 maxTF=1 @{0 2333 6}
decemb -> term377 Nt=11 TF=11 maxTF=1 @{0 2335 6}
decis -> term632 Nt=5 TF=5 maxTF=1 @{0 2348 6}
dedic -> term742 Nt=1 TF=1 maxTF=1 @{0 2358 6}
deep -> term70 Nt=8 TF=8 maxTF=1 @{0 2361 0}
defens -> term787 Nt=1 TF=1 maxTF=1 @{0 2373 4}
deficit -> term146 Nt=1 TF=1 maxTF=1 @{0 2375 6}
defin -> term671 Nt=2 TF=2 maxTF=1 @{0 2377 2}
definit -> term906 Nt=1 TF=1 maxTF=1 @{0 2382 0}
defuzzif -> term1295 Nt=1 TF=1 maxTF=1 @{0 2384 2}
deliveri -> term1086 Nt=1 TF=1 maxTF=1 @{0 2386 6}
deltebr -> term1335 Nt=1 TF=1 maxTF=1 @{0 2389 2}
demand -> term645 Nt=2 TF=2 maxTF=1 @{0 2391 6}
demetria -> term1270 Nt=1 TF=1 maxTF=1 @{0 2396 4}
demetrio -> term1269 Nt=1 TF=1 maxTF=1 @{0 2399 0}
democraci -> term298 Nt=6 TF=6 maxTF=1 @{0 2401 4}

In [39]:
term = "barcelona"
index.getLexicon()[term].toString()

'term1123 Nt=3 TF=3 maxTF=1 @{0 1391 1}'

In [41]:
#how often does the term occur
term_freq_dict = {}

for kv in index.getLexicon():
    term_freq_dict[kv.getKey()] = kv.getValue().frequency

In [43]:
#sort all terms from the index in descending order
term_freq_dict_sorted = sorted(term_freq_dict.items(), key=lambda x: x[1], reverse=True)

In [45]:
#show the 30 most popular entries
top_k = 30
term_freq_dict_sorted[:top_k]

[('intellig', 963),
 ('artifici', 931),
 ('confer', 75),
 ('proceed', 66),
 ('ai', 63),
 ('system', 63),
 ('base', 54),
 ('learn', 50),
 ('applic', 49),
 ('approach', 45),
 ('us', 43),
 ('human', 40),
 ('gener', 38),
 ('research', 36),
 ('comput', 35),
 ('educ', 30),
 ('develop', 29),
 ('nation', 28),
 ('analysi', 27),
 ('technolog', 27),
 ('review', 26),
 ('advanc', 24),
 ('impact', 24),
 ('model', 24),
 ('intern', 23),
 ('machin', 23),
 ('modern', 23),
 ('futur', 22),
 ('data', 20),
 ('explain', 20)]

In [47]:
#define our search engine
search_engine = pt.BatchRetrieve(index, wmodel="Tf")

/var/folders/88/9blsh45918g8y3n5vl6vztxr0000gq/T/ipykernel_2339/2780833963.py:2: DeprecationWarning: Call to deprecated class BatchRetrieve. (use pt.terrier.Retriever() instead) -- Deprecated since version 0.11.0.
  search_engine = pt.BatchRetrieve(index, wmodel="Tf")

In [49]:
search_engine.search("system")

,qid,docid,docno,rank,score,query
0,1,290,https://www.bibsonomy.org/bibtex/24768ef52a6c0...,0,2.0,system
1,1,41,https://www.bibsonomy.org/bibtex/249f58604f738...,1,1.0,system
2,1,68,https://www.bibsonomy.org/bibtex/2f693b1d1c623...,2,1.0,system
3,1,81,https://www.bibsonomy.org/bibtex/28585af0407b9...,3,1.0,system
4,1,84,https://www.bibsonomy.org/bibtex/2f6f3aecbaa29...,4,1.0,system
...,...,...,...,...,...,...
57,1,942,https://www.bibsonomy.org/bibtex/293fb4fd88de7...,57,1.0,system
58,1,951,https://www.bibsonomy.org/bibtex/20dac3cd23401...,58,1.0,system
59,1,974,https://www.bibsonomy.org/bibtex/27ba4173ca906...,59,1.0,system
60,1,980,https://www.bibsonomy.org/bibtex/234996efa89f2...,60,1.0,system
61,1,986,https://www.bibsonomy.org/bibtex/20eb599f35759...,61,1.0,system

In [51]:
search_engine.search("intelligent education")

,qid,docid,docno,rank,score,query
0,1,736,https://www.bibsonomy.org/bibtex/2b476e9f37ca1...,0,5.0,intelligent education
1,1,241,https://www.bibsonomy.org/bibtex/2f91c0697115d...,1,3.0,intelligent education
2,1,347,https://www.bibsonomy.org/bibtex/26895e4605d5e...,2,3.0,intelligent education
3,1,559,https://www.bibsonomy.org/bibtex/2362d4d486a4a...,3,3.0,intelligent education
4,1,644,https://www.bibsonomy.org/bibtex/226a944b1f244...,4,3.0,intelligent education
...,...,...,...,...,...,...
870,1,994,https://www.bibsonomy.org/bibtex/2d968ca695d80...,870,1.0,intelligent education
871,1,995,https://www.bibsonomy.org/bibtex/2506d96485fc4...,871,1.0,intelligent education
872,1,996,https://www.bibsonomy.org/bibtex/28765d3d19da8...,872,1.0,intelligent education
873,1,997,https://www.bibsonomy.org/bibtex/22405228e10c2...,873,1.0,intelligent education
874,1,999,https://www.bibsonomy.org/bibtex/250b84586cbc8...,874,1.0,intelligent education

In [55]:
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()

In [57]:
stem = stemmer.stem("learning")
stem

'learn'

In [59]:
lexicon = index.getLexicon()
lexicon[stem].getDocumentFrequency()

48

In [61]:
#how many documents occur in our index?
index.getCollectionStatistics().numberOfDocuments

1000

In [73]:
def get_idf_for_term(term, index):
  lex = index.getLexicon()
  stemmed_term = stemmer.stem(term)

  if not stemmed_term in lex:
    return 
    
  lex_entry = lex[stemmed_term]

  df_term = lex_entry.getDocumentFrequency()
  N = index.getCollectionStatistics().numberOfDocuments
  
  #inverse document frequency
  idf = N/df_term

  #apply logarithm(base 10) to idf
  log_idf = np.emath.logn(10, idf)

  return log_idf

In [75]:
get_idf_for_term("learning", index)

1.3187587626244126

In [77]:
#define your own tf_idf method here:

def calc_tf_idf(query, docno, index):
    #remember that tfidf is the product of two components
    #hint: the tf model search result contains tf frequencies
    return 0

In [87]:
search_engine_tfidf = pt.BatchRetrieve(index, wmodel="TF_IDF")

/var/folders/88/9blsh45918g8y3n5vl6vztxr0000gq/T/ipykernel_2339/1376347478.py:1: DeprecationWarning: Call to deprecated class BatchRetrieve. (use pt.terrier.Retriever() instead) -- Deprecated since version 0.11.0.
  search_engine_tfidf = pt.BatchRetrieve(index, wmodel="TF_IDF")

In [89]:
search_engine_tfidf.search("intelligent education")

,qid,docid,docno,rank,score,query
0,1,815,https://www.bibsonomy.org/bibtex/29cc0434b3e50...,0,4.361531,intelligent education
1,1,926,https://www.bibsonomy.org/bibtex/275d5c245ba41...,1,4.361531,intelligent education
2,1,972,https://www.bibsonomy.org/bibtex/2eb8e8e572869...,2,4.361531,intelligent education
3,1,24,https://www.bibsonomy.org/bibtex/259133e526641...,3,4.033687,intelligent education
4,1,78,https://www.bibsonomy.org/bibtex/259133e526641...,4,4.033687,intelligent education
...,...,...,...,...,...,...
870,1,132,https://www.bibsonomy.org/bibtex/2c4df47ce17b7...,870,0.373180,intelligent education
871,1,230,https://www.bibsonomy.org/bibtex/29fcc0f646278...,871,0.373180,intelligent education
872,1,595,https://www.bibsonomy.org/bibtex/21b69569af8d0...,872,0.373180,intelligent education
873,1,250,https://www.bibsonomy.org/bibtex/2ba15da18da2c...,873,0.345844,intelligent education
874,1,350,https://www.bibsonomy.org/bibtex/24d041e3486cf...,874,0.333625,intelligent education

In [91]:
df_ai_filtered.columns

Index(['id', 'tags', 'label', 'description', 'date', 'changeDate', 'url',
       'pub-type', 'year', 'author', 'authors', 'publisher', 'docno', 'text'],
      dtype='object')

In [93]:
ai_dict = df_ai_filtered.to_dict(orient='records')

In [95]:
ai_dict

[{'id': 'https://www.bibsonomy.org/bibtex/24e338b04bc2abafd9fa0a1f4fe79103a/ijtsrd',
  'tags': ['710-714'],
  'label': 'Artificial Intelligence in Agriculture',
  'description': '',
  'date': '2021-04-13 13:15:04',
  'changeDate': '2021-04-13 13:15:04',
  'url': 'https://www.ijtsrd.com/engineering/electrical-engineering/38513/artificial-intelligence-in-agriculture/matthew-n-o-sadiku',
  'pub-type': 'article',
  'year': '2021',
  'author': ['Matthew N. O. Sadiku | Sarhan M. Musa | Abayomi Ajayi-Majebi'],
  'authors': [{'first': 'Matthew N. O. Sadiku | Sarhan M. Musa | Abayomi',
    'last': 'Ajayi-Majebi'}],
  'publisher': nan,
  'docno': 'https://www.bibsonomy.org/bibtex/24e338b04bc2abafd9fa0a1f4fe79103a/ijtsrd',
  'text': 'Artificial Intelligence in Agriculture'},
 {'id': 'https://www.bibsonomy.org/bibtex/283c4174f111d968e8ca51b252f8fea3e/meneteqel',
  'tags': ['digitalisation',
   'artificial_intelligence',
   'society',
   'labour_rights'],
  'label': 'Artificial intelligence, labour and society',
  'description': '',
  'date': '2024-04-08 09:45:09',
  'changeDate': '2024-04-08 09:46:54',
  'url': 'https://www.etui.org/publications/artificial-intelligence-labour-and-society',
  'pub-type': 'book',
  'year': '2024',
  'author': nan,
  'authors': nan,
  'publisher': 'ETUI aisbl',
  'docno': 'https://www.bibsonomy.org/bibtex/283c4174f111d968e8ca51b252f8fea3e/meneteqel',
  'text': 'Artificial intelligence, labour and society'},
 {'id': 'https://www.bibsonomy.org/bibtex/29f3b593035714a894c265f4fb9c535e7/ijtsrd',
  'tags': ['Artificial', 'Intelligence', 'Risks', 'and', 'Benefits'],
  'label': 'Artificial Intelligence Benefit and Risks',
  'description': '',
  'date': '2020-05-14 10:40:49',
  'changeDate': '2020-05-14 10:40:49',
  'url': 'https://www.ijtsrd.com/computer-science/artificial-intelligence/30232/artificial-intelligence-benefit-and-risks/seeta-m-chauhan',
  'pub-type': 'article',
  'year': '2020',
  'author': ['Seeta M. Chauhan'],
  'authors': [{'first': 'Seeta M.', 'last': 'Chauhan'}],
  'publisher': nan,
  'docno': 'https://www.bibsonomy.org/bibtex/29f3b593035714a894c265f4fb9c535e7/ijtsrd',
  'text': 'Artificial Intelligence Benefit and Risks'},
 {'id': 'https://www.bibsonomy.org/bibtex/2a97c2267cfe4a39d368f1507149affd0/meneteqel',
  'tags': ['industry',
   'artificial_intelligence',
   'health_and_safety',
   'produktion'],
  'label': 'Artificial intelligence in Industry 4.0: Implications for occupational safety and health',
  'description': '',
  'date': '2024-08-01 15:21:53',
  'changeDate': '2024-08-01 15:21:53',
  'url': 'https://www.etui.org/publications/artificial-intelligence-industry-40',
  'pub-type': 'book',
  'year': '2024',
  'author': ['Pierre Bérastégui'],
  'authors': [{'first': 'Pierre', 'last': 'Bérastégui'}],
  'publisher': 'European Trade Union Institute',
  'docno': 'https://www.bibsonomy.org/bibtex/2a97c2267cfe4a39d368f1507149affd0/meneteqel',
  'text': 'Artificial intelligence in Industry 4.0: Implications for occupational safety and health'},
 {'id': 'https://www.bibsonomy.org/bibtex/2df98b0d20723566bfc445b3da9e69ac2/ijtsrd',
  'tags': ['Human',
   'Intelligence,',
   'intelligence,',
   'centric',
   'Artificialintelligence',
   'AGI,',
   'Ethical',
   'AI'],
  'label': 'Evolution of Artificial Intelligence by Prompt Science Analysis',
  'description': '',
  'date': '2024-12-30 07:46:23',
  'changeDate': '2024-12-30 07:46:23',
  'url': 'https://www.ijtsrd.com/computer-science/artificial-intelligence/69358/evolution-of-artificial-intelligence-by-prompt-science-analysis/manish-verma',
  'pub-type': 'article',
  'year': '2024',
  'author': ['Manish Verma'],
  'authors': [{'first': 'Manish', 'last': 'Verma'}],
  'publisher': nan,
  'docno': 'https://www.bibsonomy.org/bibtex/2df98b0d20723566bfc445b3da9e69ac2/ijtsrd',
  'text': 'Evolution of Artificial Intelligence by Prompt Science Analysis'},
 {'id': 'https://www.bibsonomy.org/bibtex/21a31a7056bb1c84ffe568f434b9d565f/ijtsrd',
  'tags': ['robotics,',
   'artificial',
   'intelligence,',
   'exploration,',
   'machine',
   'learning',
   'space',
   'industry,'],
  'label': 'Artificial Intelligence in Space Exploration',
  'description': '',
  'date': '2025-01-02 13:18:33',
  'changeDate': '2025-01-02 13:18:33',
  'url': 'https://www.ijtsrd.com/computer-science/artificial-intelligence/70469/artificial-intelligence-in-space-exploration/matthew-n-o-sadiku',
  'pub-type': 'article',
  'year': '2024',
  'author': ['Matthew N. O. Sadiku | Paul A. Adekunte | Janet O. Sadiku'],
  'authors': [{'first': 'Matthew N. O. Sadiku | Paul A. Adekunte | Janet O.',
    'last': 'Sadiku'}],
  'publisher': nan,
  'docno': 'https://www.bibsonomy.org/bibtex/21a31a7056bb1c84ffe568f434b9d565f/ijtsrd',
  'text': 'Artificial Intelligence in Space Exploration'},
 {'id': 'https://www.bibsonomy.org/bibtex/2f76cb3964befb565e8456efb255b9918/brusilovsky',
  'tags': ['explanation'],
  'label': 'Explanation in artificial intelligence: Insights from the social sciences',
  'description': 'Explanation in artificial intelligence: Insights from the social sciences - ScienceDirect',
  'date': '2023-06-05 00:07:52',
  'changeDate': '2023-06-05 00:07:52',
  'url': 'https://www.sciencedirect.com/science/article/pii/S0004370218305988',
  'pub-type': 'article',
  'year': '2019',
  'author': ['Tim Miller'],
  'authors': [{'first': 'Tim', 'last': 'Miller'}],
  'publisher': nan,
  'docno': 'https://www.bibsonomy.org/bibtex/2f76cb3964befb565e8456efb255b9918/brusilovsky',
  'text': 'Explanation in artificial intelligence: Insights from the social sciences'},
 {'id': 'https://www.bibsonomy.org/bibtex/24bc08fb79365b5bc698af1cd97fc1a75/ijtsrd',
  'tags': ['ANN',
   'Fuzzylogic',
   'ElectricalEngineering',
   'Artificialintelligence'],
  'label': 'Artificial Intelligence in Power Station',
  'description': '',
  'date': '2020-01-10 09:23:37',
  'changeDate': '2020-01-10 09:23:37',
  'url': 'https://www.ijtsrd.com/engineering/electrical-engineering/29784/artificial-intelligence-in-power-station/p-naveen',
  'pub-type': 'article',
  'year': '2019',
  'author': ['P. Naveen | S. Nikitha | P. Sudeesh | V. Vaishnavi'],
  'authors': [{'first': 'P. Naveen | S. Nikitha | P. Sudeesh | V.',
    'last': 'Vaishnavi'}],
  'publisher': nan,
  'docno': 'https://www.bibsonomy.org/bibtex/24bc08fb79365b5bc698af1cd97fc1a75/ijtsrd',
  'text': 'Artificial Intelligence in Power Station'},
 {'id': 'https://www.bibsonomy.org/bibtex/219d04dda236da5a4e7592a9eb2d4f5eb/mardukasoka',
  'tags': ['simulation', 'ai'],
  'label': 'A framework for Integrating Artificial Intelligence and Simulation',
  'description': 'A framework for Integrating Artificial Intelligence and Simulation | SpringerLink',
  'date': '2017-04-29 16:53:32',
  'changeDate': '2017-04-29 16:53:32',
  'url': 'http://dx.doi.org/10.1007/BF00851350',
  'pub-type': 'article',
  'year': '1994',
  'author': ['Georgios I. Doukidis', 'Marios C. Angelides'],
  'authors': [{'first': 'Georgios I.', 'last': 'Doukidis'},
   {'first': 'Marios C.', 'last': 'Angelides'}],
  'publisher': nan,
  'docno': 'https://www.bibsonomy.org/bibtex/219d04dda236da5a4e7592a9eb2d4f5eb/mardukasoka',
  'text': 'A framework for Integrating Artificial Intelligence and Simulation'},
 {'id': 'https://www.bibsonomy.org/bibtex/29f87881e4decfde15a1af630c8ea27d5/ijtsrd',
  'tags': ['Artificial',
   'Intelligence',
   'Markup',
   'Chatbot',
   'Language',
   'Articial',
   'Natural',
   'Processing'],
  'label': 'Artificial Intelligence Based Training and Placement Management',
  'description': '',
  'date': '2019-03-26 12:35:44',
  'changeDate': '2019-03-26 12:35:44',
  'url': 'http://www.ijtsrd.com/computer-science/artificial-intelligence/19180/artificial-intelligence-based-training-and-placement-management/krishanu-deb',
  'pub-type': 'article',
  'year': '2018',
  'author': ['Krishanu Deb | Pankaj Agrawal | Harish Nawale | Shradha Jadhav | Prof. Manisha Darak'],
  'authors': [{'first': 'Krishanu Deb | Pankaj Agrawal | Harish Nawale | Shradha Jadhav | Prof. Manisha',
    'last': 'Darak'}],
  'publisher': nan,
  'docno': 'https://www.bibsonomy.org/bibtex/29f87881e4decfde15a1af630c8ea27d5/ijtsrd',
  'text': 'Artificial Intelligence Based Training and Placement Management'},
 {'id': 'https://www.bibsonomy.org/bibtex/263320f0ab96ae778b51b2376aa914f59/ijtsrd',
  'tags': ['Learning,',
   'Systems,',
   'Artificialintelligence',
   'E-Marketing,',
   'Digital',
   'Electronic',
   'Computing,',
   'Machine',
   'Advertising,',
   'Intelligence,',
   'Web',
   'Intelligent',
   'Marketing,',
   'Cognitive',
   'Internet',
   'Advertising',
   'Automated',
   'Online'],
  'label': 'The Significance of Artificial Intelligence in Digital Marketing',
  'description': '',
  'date': '2023-10-14 13:59:49',
  'changeDate': '2023-10-14 13:59:49',
  'url': 'https://www.ijtsrd.com/computer-science/artificial-intelligence/59801/the-significance-of-artificial-intelligence-in-digital-marketing/dr-atul-kumar-mishra',
  'pub-type': 'article',
  'year': '2023',
  'author': ['Dr. Atul Kumar Mishra'],
  'authors': [{'first': 'Dr. Atul Kumar', 'last': 'Mishra'}],
  'publisher': nan,
  'docno': 'https://www.bibsonomy.org/bibtex/263320f0ab96ae778b51b2376aa914f59/ijtsrd',
  'text': 'The Significance of Artificial Intelligence in Digital Marketing'},
 {'id': 'https://www.bibsonomy.org/bibtex/26feca839dc10fb815235e9b0f19c2707/ijtsrd',
  'tags': ['Human',
   'Artificialintelligence',
   'Curiosity,',
   'Students,',
   'Instruction,',
   'Growth,',
   'Intelligence,',
   'Technology',
   'Creative',
   'Thinking',
   'Things,',
   'Chat-GPT,',
   'Classroom',
   'Machines,',
   'New',
   'Skills,'],
  'label': 'Impact of Artificial Intelligence and Curiosity among Students to Learn New Things',
  'description': '',
  'date': '2025-01-03 06:49:55',
  'changeDate': '2025-01-03 06:49:55',
  'url': 'https://www.ijtsrd.com/computer-science/artificial-intelligence/70509/impact-of-artificial-intelligence-and-curiosity-among-students-to-learn-new-things/dr-charu-sharma',
  'pub-type': 'article',
  'year': '2024',
  'author': ['Dr. Charu Sharma'],
  'authors': [{'first': 'Dr. Charu', 'last': 'Sharma'}],
  'publisher': nan,
  'docno': 'https://www.bibsonomy.org/bibtex/26feca839dc10fb815235e9b0f19c2707/ijtsrd',
  'text': 'Impact of Artificial Intelligence and Curiosity among Students to Learn New Things'},
 {'id': 'https://www.bibsonomy.org/bibtex/28a86ca74e262b9883c8dd4a7c60f1652/ijtsrd',
  'tags': ['(AI),',
   'Behavior,',
   'Intelligent',
   'Artificialintelligence',
   'Intelligence',
   'Computer',
   'Science,',
   'STEM'],
  'label': 'Artificial Intelligence Role in Modern Science Aims, Merits, Risks and Its Applications',
  'description': '',
  'date': '2024-01-05 10:08:27',
  'changeDate': '2024-01-05 10:08:27',
  'url': 'https://www.ijtsrd.com/computer-science/artificial-intelligence/59910/artificial-intelligence-role-in-modern-science-aims-merits-risks-and-its-applications/manish-verma',
  'pub-type': 'article',
  'year': '2023',
  'author': ['Manish Verma'],
  'authors': [{'first': 'Manish', 'last': 'Verma'}],
  'publisher': nan,
  'docno': 'https://www.bibsonomy.org/bibtex/28a86ca74e262b9883c8dd4a7c60f1652/ijtsrd',
  'text': 'Artificial Intelligence Role in Modern Science Aims, Merits, Risks and Its Applications'},
 {'id': 'https://www.bibsonomy.org/bibtex/2b31f13f50e07ac7e22de4ea993ba89ee/ijtsrd',
  'tags': ['Human',
   'Intelligence,',
   'Creativity,',
   'Artificialintelligence',
   'of',
   'Art,',
   'Expression',
   'Computational',
   'Freedom',
   'Modern'],
  'label': 'Artificial Intelligence Catalyzes a Revolution for 21st Century Human Creativity and Modern Art',
  'description': '',
  'date': '2022-07-22 08:10:40',
  'changeDate': '2022-07-22 08:10:40',
  'url': 'https://www.ijtsrd.com/computer-science/artificial-intelligence/49150/artificial-intelligence-catalyzes-a-revolution-for-21st-century-human-creativity-and-modern-art/avani-goenka',
  'pub-type': 'article',
  'year': '2022',
  'author': ['Avani Goenka'],
  'authors': [{'first': 'Avani', 'last': 'Goenka'}],
  'publisher': nan,
  'docno': 'https://www.bibsonomy.org/bibtex/2b31f13f50e07ac7e22de4ea993ba89ee/ijtsrd',
  'text': 'Artificial Intelligence Catalyzes a Revolution for 21st Century Human Creativity and Modern Art'},
 {'id': 'https://www.bibsonomy.org/bibtex/27ecf6efc8052756e6b1c5084ddcea538/ijtsrd',
  'tags': ['etc', 'Artificial', 'Intelligence', 'machines', 'technology'],
  'label': 'Artificial Intelligence Empowering the Future of Digital Transformation',
  'description': '',
  'date': '2020-06-10 06:39:14',
  'changeDate': '2020-06-10 06:39:14',
  'url': 'https://www.ijtsrd.com/computer-science/artificial-intelligence/30287/artificial-intelligence-empowering-the-future-of-digital-transformation/deepak-kumar',
  'pub-type': 'article',
  'year': '2020',
  'author': ['Deepak Kumar'],
  'authors': [{'first': 'Deepak', 'last': 'Kumar'}],
  'publisher': nan,
  'docno': 'https://www.bibsonomy.org/bibtex/27ecf6efc8052756e6b1c5084ddcea538/ijtsrd',
  'text': 'Artificial Intelligence Empowering the Future of Digital Transformation'},
 {'id': 'https://www.bibsonomy.org/bibtex/2c6e8dcc6939a3a8145af0bfcb66613d0/ijtsrd',
  'tags': ['Aayog',
   'Artificialintelligence',
   'Intelligence',
   'MeitY',
   'NITI',
   'Taskforce'],
  'label': 'Analysis and Comparative Study of the Development of Technology with Artificial Intelligence in India',
  'description': '',
  'date': '2020-07-16 11:09:36',
  'changeDate': '2020-07-16 11:09:36',
  'url': 'https://www.ijtsrd.com/computer-science/artificial-intelligence/31249/analysis-and-comparative-study-of-the-development-of-technology-with-artificial-intelligence-in-india/chinmaya-naik',
  'pub-type': 'article',
  'year': '2020',
  'author': ['Chinmaya Naik | Sonali Jain | Jai Sehgal'],
  'authors': [{'first': 'Chinmaya Naik | Sonali Jain | Jai',
    'last': 'Sehgal'}],
  'publisher': nan,
  'docno': 'https://www.bibsonomy.org/bibtex/2c6e8dcc6939a3a8145af0bfcb66613d0/ijtsrd',
  'text': 'Analysis and Comparative Study of the Development of Technology with Artificial Intelligence in India'},
 {'id': 'https://www.bibsonomy.org/bibtex/2934ad4d5459670059204a31a0aa7213b/ijtsrd',
  'tags': ['Discriminant',
   'Analysis',
   'SVM,',
   'Opinion',
   'Analysis,',
   'BOW,',
   'K-NN,'],
  'label': 'Opinion Text Analysis Using Artificial Intelligence',
  'description': '',
  'date': '2024-08-08 08:47:08',
  'changeDate': '2024-08-08 08:47:08',
  'url': 'https://www.ijtsrd.com/computer-science/artificial-intelligence/64847/opinion-text-analysis-using-artificial-intelligence/rahul-sagar',
  'pub-type': 'article',
  'year': '2024',
  'author': ['Rahul Sagar | Sumit Dalal | Sumiran'],
  'authors': [{'first': 'Rahul Sagar | Sumit Dalal |', 'last': 'Sumiran'}],
  'publisher': nan,
  'docno': 'https://www.bibsonomy.org/bibtex/2934ad4d5459670059204a31a0aa7213b/ijtsrd',
  'text': 'Opinion Text Analysis Using Artificial Intelligence'},
 {'id': 'https://www.bibsonomy.org/bibtex/24feff2b5c07e645c377f8a93c27ae02e/ijtsrd',
  'tags': ['Intelligence,',
   'Artificialintelligence',
   'Pharmaceutical,',
   'Trials,',
   'Challenges',
   'Clinical',
   'Industry,'],
  'label': 'Impact of Artificial Intelligence in the Pharmaceutical World A Review',
  'description': '',
  'date': '2023-07-18 14:31:02',
  'changeDate': '2023-07-18 14:31:02',
  'url': 'https://www.ijtsrd.com.com/computer-science/artificial-intelligence/57564/impact-of-artificial-intelligence-in-the-pharmaceutical-world-a-review/shaikh-sameer-salim',
  'pub-type': 'article',
  'year': '2023',
  'author': ['Shaikh Sameer Salim | Manoj Kumar'],
  'authors': [{'first': 'Shaikh Sameer Salim | Manoj', 'last': 'Kumar'}],
  'publisher': nan,
  'docno': 'https://www.bibsonomy.org/bibtex/24feff2b5c07e645c377f8a93c27ae02e/ijtsrd',
  'text': 'Impact of Artificial Intelligence in the Pharmaceutical World A Review'},
 {'id': 'https://www.bibsonomy.org/bibtex/2a5daa928276945e33c2a6ef3ee635e90/ijtsrd',
  'tags': ['gamification',
   'artificial',
   'game',
   'computer',
   'gaming',
   'in',
   'of',
   'AI',
   'games',
   'intelligence'],
  'label': 'Artificial Intelligence in Gaming',
  'description': '',
  'date': '2021-04-13 13:24:36',
  'changeDate': '2021-04-13 13:24:36',
  'url': 'https://www.ijtsrd.com/engineering/electrical-engineering/38516/artificial-intelligence-in-gaming/matthew-n-o-sadiku',
  'pub-type': 'article',
  'year': '2021',
  'author': ['Matthew N. O. Sadiku | Sarhan M. Musa | Abayomi Ajayi-Majebi'],
  'authors': [{'first': 'Matthew N. O. Sadiku | Sarhan M. Musa | Abayomi',
    'last': 'Ajayi-Majebi'}],
  'publisher': nan,
  'docno': 'https://www.bibsonomy.org/bibtex/2a5daa928276945e33c2a6ef3ee635e90/ijtsrd',
  'text': 'Artificial Intelligence in Gaming'},
 {'id': 'https://www.bibsonomy.org/bibtex/2ba1d81348174d6afe4b4264f9934767d/ijtsrd',
  'tags': ['intelligence,',
   'marketing,',
   'Artificialintelligence',
   'data',
   'machine',
   'analytics,',
   'learning',
   'digitalization,',
   'big'],
  'label': 'The Transformative Role of Artificial Intelligence Technology for Simulating Human Intelligence Across Various Sectors',
  'description': '',
  'date': '2024-08-09 10:58:41',
  'changeDate': '2024-08-09 10:58:41',
  'url': 'https://www.ijtsrd.com/physics/other/64924/the-transformative-role-of-artificial-intelligence-technology-for-simulating-human-intelligence-across-various-sectors/dr-madhuri-asati',
  'pub-type': 'article',
  'year': '2024',
  'author': ['Dr. Madhuri Asati'],
  'authors': [{'first': 'Dr. Madhuri', 'last': 'Asati'}],
  'publisher': nan,
  'docno': 'https://www.bibsonomy.org/bibtex/2ba1d81348174d6afe4b4264f9934767d/ijtsrd',
  'text': 'The Transformative Role of Artificial Intelligence Technology for Simulating Human Intelligence Across Various Sectors'},
 {'id': 'https://www.bibsonomy.org/bibtex/2a812df36a1a60ab7c70a27f78f966e6d/kirk86',
  'tags': ['deep-learning', 'logic'],
  'label': 'Reconciling deep learning with symbolic artificial intelligence: representing objects and relations',
  'description': 'Reconciling deep learning with symbolic artificial intelligence: representing objects and relations - ScienceDirect',
  'date': '2019-07-15 04:36:37',
  'changeDate': '2019-07-15 04:36:37',
  'url': 'http://www.sciencedirect.com/science/article/pii/S2352154618301943',
  'pub-type': 'article',
  'year': '2019',
  'author': ['Marta Garnelo', 'Murray Shanahan'],
  'authors': [{'first': 'Marta', 'last': 'Garnelo'},
   {'first': 'Murray', 'last': 'Shanahan'}],
  'publisher': nan,
  'docno': 'https://www.bibsonomy.org/bibtex/2a812df36a1a60ab7c70a27f78f966e6d/kirk86',
  'text': 'Reconciling deep learning with symbolic artificial intelligence: representing objects and relations'},
 {'id': 'https://www.bibsonomy.org/bibtex/210782e0d83c4c2cc7175f6012b3bbbe4/ijtsrd',
  'tags': ['human-computerinteraction', 'artificialintelligence'],
  'label': 'Artificial Intelligence and Human Computer Interaction',
  'description': '',
  'date': '2022-03-01 13:19:32',
  'changeDate': '2022-03-01 13:19:32',
  'url': 'https://www.ijtsrd.com/engineering/computer-engineering/47491/artificial-intelligence-and-humancomputer-interaction/matthew-n-o-sadiku',
  'pub-type': 'article',
  'year': '2021',
  'author': ['Matthew N. O. Sadiku | Uwakwe C. Chukwu | Abayomi Ajayi-Majebi | Sarhan M. Musa'],
  'authors': [{'first': 'Matthew N. O. Sadiku | Uwakwe C. Chukwu | Abayomi Ajayi-Majebi | Sarhan M.',
    'last': 'Musa'}],
  'publisher': nan,
  'docno': 'https://www.bibsonomy.org/bibtex/210782e0d83c4c2cc7175f6012b3bbbe4/ijtsrd',
  'text': 'Artificial Intelligence and Human Computer Interaction'},
 {'id': 'https://www.bibsonomy.org/bibtex/20650ad799a08ccda673011c68b0a4cfa/ijtsrd',
  'tags': ['Engineering', 'Computers'],
  'label': 'Artificial Intelligence Basics and Terminology',
  'description': '',
  'date': '2018-11-20 12:31:40',
  'changeDate': '2018-11-20 12:31:40',

In [99]:
index_folder_mult = "./ai_index_mult"

fields=['docno', 'text', 'tags', 'description']

indexer_mult = pt.IterDictIndexer(index_folder_mult, meta={'docno': 200, 'text': 4096}, overwrite=True)
index_ref_mult = indexer_mult.index(ai_dict, fields=fields)

print(f"path to our index: {index_ref_mult.toString()}")

path to our index: ./ai_index_mult/data.properties

In [101]:
index_mult = pt.IndexFactory.of(index_ref_mult)

In [103]:
print(index_mult.getCollectionStatistics().toString())

Number of documents: 1000
Number of terms: 2273
Number of postings: 14595
Number of fields: 4
Number of tokens: 16828
Field names: [docno, text, tags, description]
Positions:   false

In [107]:
search_engine_mult = pt.BatchRetrieve(index_mult, wmodel="TF_IDF")

/var/folders/88/9blsh45918g8y3n5vl6vztxr0000gq/T/ipykernel_2339/495383578.py:1: DeprecationWarning: Call to deprecated class BatchRetrieve. (use pt.terrier.Retriever() instead) -- Deprecated since version 0.11.0.
  search_engine_mult = pt.BatchRetrieve(index_mult, wmodel="TF_IDF")

In [109]:
res = search_engine_mult.search("intelligence")
res

,qid,docid,docno,rank,score,query
0,1,732,https://www.bibsonomy.org/bibtex/224ac67b53792...,0,0.949091,intelligence
1,1,347,https://www.bibsonomy.org/bibtex/26895e4605d5e...,1,0.924343,intelligence
2,1,323,https://www.bibsonomy.org/bibtex/29a73b5ea0550...,2,0.891737,intelligence
3,1,501,https://www.bibsonomy.org/bibtex/2f7cf941158e2...,3,0.891737,intelligence
4,1,733,https://www.bibsonomy.org/bibtex/21a922cb4af1f...,4,0.891737,intelligence
...,...,...,...,...,...,...
925,1,860,https://www.bibsonomy.org/bibtex/25a061b694a47...,925,0.385489,intelligence
926,1,833,https://www.bibsonomy.org/bibtex/25a061b694a47...,926,0.379302,intelligence
927,1,666,https://www.bibsonomy.org/bibtex/28cff9d35fb12...,927,0.367505,intelligence
928,1,667,https://www.bibsonomy.org/bibtex/28cff9d35fb12...,928,0.367505,intelligence
929,1,70,https://www.bibsonomy.org/bibtex/23311da130c4e...,929,0.301801,intelligence

In [111]:
#save our data
pickle.dump(df_ai_filtered, open("workspace/ai_publications.pkl", "wb"))

FileNotFoundError: [Errno 2] No such file or directory: 'workspace/ai_publications.pkl'

In [113]:
pip install streamlit

Requirement already satisfied: streamlit in /opt/anaconda3/lib/python3.12/site-packages (1.37.1)
Requirement already satisfied: altair<6,>=4.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (5.0.1)
Requirement already satisfied: blinker<2,>=1.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (1.6.2)
Requirement already satisfied: cachetools<6,>=4.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (5.3.3)
Requirement already satisfied: click<9,>=7.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (8.1.7)
Requirement already satisfied: numpy<3,>=1.20 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (1.26.4)
Requirement already satisfied: packaging<25,>=20 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (24.1)
Requirement already satisfied: pandas<3,>=1.3.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<11,>=7.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (10.4.0)
Requirement already satisfied: protobuf<6,>=3.20 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (4.25.3)
Requirement already satisfied: pyarrow>=7.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (16.1.0)
Requirement already satisfied: requests<3,>=2.27 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (2.32.3)
Requirement already satisfied: rich<14,>=10.14.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (13.7.1)
Requirement already satisfied: tenacity<9,>=8.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (8.2.3)
Requirement already satisfied: toml<2,>=0.10.1 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.3.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (4.11.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (3.1.43)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (0.8.0)
Requirement already satisfied: tornado<7,>=6.0.3 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (6.4.1)
Requirement already satisfied: jinja2 in /opt/anaconda3/lib/python3.12/site-packages (from altair<6,>=4.0->streamlit) (3.1.4)
Requirement already satisfied: jsonschema>=3.0 in /opt/anaconda3/lib/python3.12/site-packages (from altair<6,>=4.0->streamlit) (4.23.0)
Requirement already satisfied: toolz in /opt/anaconda3/lib/python3.12/site-packages (from altair<6,>=4.0->streamlit) (0.12.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /opt/anaconda3/lib/python3.12/site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.7)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.12/site-packages (from pandas<3,>=1.3.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.12/site-packages (from pandas<3,>=1.3.0->streamlit) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.12/site-packages (from pandas<3,>=1.3.0->streamlit) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit) (2024.8.30)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from rich<14,>=10.14.0->streamlit) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/anaconda3/lib/python3.12/site-packages (from rich<14,>=10.14.0->streamlit) (2.15.1)
Requirement already satisfied: smmap<5,>=3.0.1 in /opt/anaconda3/lib/python3.12/site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.12/site-packages (from jinja2->altair<6,>=4.0->streamlit) (2.1.3)
Requirement already satisfied: attrs>=22.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in /opt/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in /opt/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.10.6)
Requirement already satisfied: mdurl~=0.1 in /opt/anaconda3/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit) (0.1.0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.3.0->streamlit) (1.16.0)
Note: you may need to restart the kernel to use updated packages.