# Data Librarian - Modul 2 PyTerrier Tutorial
## This notebook is based on a CIKM workshop
https://github.com/terrier-org/cikm2021tutorial/blob/main/notebooks

In [2]:
#learn more about pyterrier: https://pyterrier.readthedocs.io/en/latest/

In [4]:
#install pyterrier
%pip install python-terrier

Requirement already satisfied: python-terrier in /opt/anaconda3/lib/python3.12/site-packages (0.12.1)
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.12/site-packages (from python-terrier) (1.26.4)
Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.12/site-packages (from python-terrier) (2.2.2)
Requirement already satisfied: more-itertools in /opt/anaconda3/lib/python3.12/site-packages (from python-terrier) (10.3.0)
Requirement already satisfied: tqdm in /opt/anaconda3/lib/python3.12/site-packages (from python-terrier) (4.66.5)
Requirement already satisfied: requests in /opt/anaconda3/lib/python3.12/site-packages (from python-terrier) (2.32.3)
Requirement already satisfied: ir-datasets>=0.3.2 in /opt/anaconda3/lib/python3.12/site-packages (from python-terrier) (0.5.9)
Requirement already satisfied: wget in /opt/anaconda3/lib/python3.12/site-packages (from python-terrier) (3.2)
Requirement already satisfied: pyjnius>=1.4.2 in /opt/anaconda3/lib/python3.12/site-packages (from python-terrier) (1.6.1)
Requirement already satisfied: deprecated in /opt/anaconda3/lib/python3.12/site-packages (from python-terrier) (1.2.15)
Requirement already satisfied: scipy in /opt/anaconda3/lib/python3.12/site-packages (from python-terrier) (1.13.1)
Requirement already satisfied: ir-measures>=0.3.1 in /opt/anaconda3/lib/python3.12/site-packages (from python-terrier) (0.3.6)
Requirement already satisfied: pytrec-eval-terrier>=0.5.3 in /opt/anaconda3/lib/python3.12/site-packages (from python-terrier) (0.5.6)
Requirement already satisfied: jinja2 in /opt/anaconda3/lib/python3.12/site-packages (from python-terrier) (3.1.4)
Requirement already satisfied: statsmodels in /opt/anaconda3/lib/python3.12/site-packages (from python-terrier) (0.14.2)
Requirement already satisfied: dill in /opt/anaconda3/lib/python3.12/site-packages (from python-terrier) (0.3.8)
Requirement already satisfied: joblib in /opt/anaconda3/lib/python3.12/site-packages (from python-terrier) (1.4.2)
Requirement already satisfied: chest in /opt/anaconda3/lib/python3.12/site-packages (from python-terrier) (0.2.3)
Requirement already satisfied: beautifulsoup4>=4.4.1 in /opt/anaconda3/lib/python3.12/site-packages (from ir-datasets>=0.3.2->python-terrier) (4.12.3)
Requirement already satisfied: inscriptis>=2.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from ir-datasets>=0.3.2->python-terrier) (2.5.0)
Requirement already satisfied: lxml>=4.5.2 in /opt/anaconda3/lib/python3.12/site-packages (from ir-datasets>=0.3.2->python-terrier) (5.2.1)
Requirement already satisfied: pyyaml>=5.3.1 in /opt/anaconda3/lib/python3.12/site-packages (from ir-datasets>=0.3.2->python-terrier) (6.0.1)
Requirement already satisfied: trec-car-tools>=2.5.4 in /opt/anaconda3/lib/python3.12/site-packages (from ir-datasets>=0.3.2->python-terrier) (2.6)
Requirement already satisfied: lz4>=3.1.10 in /opt/anaconda3/lib/python3.12/site-packages (from ir-datasets>=0.3.2->python-terrier) (4.3.2)
Requirement already satisfied: warc3-wet>=0.2.3 in /opt/anaconda3/lib/python3.12/site-packages (from ir-datasets>=0.3.2->python-terrier) (0.2.5)
Requirement already satisfied: warc3-wet-clueweb09>=0.2.5 in /opt/anaconda3/lib/python3.12/site-packages (from ir-datasets>=0.3.2->python-terrier) (0.2.5)
Requirement already satisfied: zlib-state>=0.1.3 in /opt/anaconda3/lib/python3.12/site-packages (from ir-datasets>=0.3.2->python-terrier) (0.1.9)
Requirement already satisfied: ijson>=3.1.3 in /opt/anaconda3/lib/python3.12/site-packages (from ir-datasets>=0.3.2->python-terrier) (3.3.0)
Requirement already satisfied: unlzw3>=0.2.1 in /opt/anaconda3/lib/python3.12/site-packages (from ir-datasets>=0.3.2->python-terrier) (0.2.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests->python-terrier) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests->python-terrier) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.12/site-packages (from requests->python-terrier) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.12/site-packages (from requests->python-terrier) (2024.8.30)
Requirement already satisfied: heapdict in /opt/anaconda3/lib/python3.12/site-packages (from chest->python-terrier) (1.0.1)
Requirement already satisfied: wrapt<2,>=1.10 in /opt/anaconda3/lib/python3.12/site-packages (from deprecated->python-terrier) (1.14.1)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.12/site-packages (from jinja2->python-terrier) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.12/site-packages (from pandas->python-terrier) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.12/site-packages (from pandas->python-terrier) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.12/site-packages (from pandas->python-terrier) (2023.3)
Requirement already satisfied: patsy>=0.5.6 in /opt/anaconda3/lib/python3.12/site-packages (from statsmodels->python-terrier) (0.5.6)
Requirement already satisfied: packaging>=21.3 in /opt/anaconda3/lib/python3.12/site-packages (from statsmodels->python-terrier) (24.1)
Requirement already satisfied: soupsieve>1.2 in /opt/anaconda3/lib/python3.12/site-packages (from beautifulsoup4>=4.4.1->ir-datasets>=0.3.2->python-terrier) (2.5)
Requirement already satisfied: six in /opt/anaconda3/lib/python3.12/site-packages (from patsy>=0.5.6->statsmodels->python-terrier) (1.16.0)
Requirement already satisfied: cbor>=1.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from trec-car-tools>=2.5.4->ir-datasets>=0.3.2->python-terrier) (1.0.0)
Note: you may need to restart the kernel to use updated packages.

In [6]:
%pip install nltk

Requirement already satisfied: nltk in /opt/anaconda3/lib/python3.12/site-packages (3.9.1)
Requirement already satisfied: click in /opt/anaconda3/lib/python3.12/site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in /opt/anaconda3/lib/python3.12/site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /opt/anaconda3/lib/python3.12/site-packages (from nltk) (2024.9.11)
Requirement already satisfied: tqdm in /opt/anaconda3/lib/python3.12/site-packages (from nltk) (4.66.5)
Note: you may need to restart the kernel to use updated packages.

In [8]:
import pyterrier as pt
import requests
import pandas as pd
import pickle
import nltk
import numpy as np

In [9]:
query = "artificial intelligence"
url =  f"https://www.bibsonomy.org/json/search/{query}?items=1000"

In [10]:
url

'https://www.bibsonomy.org/json/search/artificial intelligence?items=1000'

In [11]:
res = requests.get(url)

In [15]:
data = res.json()

In [16]:
df_ai = pd.DataFrame(data["items"])
df_ai = df_ai[df_ai["type"] == "Publication"]

In [20]:
df_ai

,type,id,tags,intraHash,label,user,description,date,changeDate,count,...,position,category,impact,quartile,dnbtitleid,pdf,broken,organisation,citedreferences,optseries
1000,Publication,https://www.bibsonomy.org/bibtex/24e338b04bc2a...,[710-714],4e338b04bc2abafd9fa0a1f4fe79103a,Artificial Intelligence in Agriculture,ijtsrd,,2021-04-13 13:15:04,2021-04-13 13:15:04,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001,Publication,https://www.bibsonomy.org/bibtex/283c4174f111d...,"[digitalisation, artificial_intelligence, soci...",83c4174f111d968e8ca51b252f8fea3e,"Artificial intelligence, labour and society",meneteqel,,2024-04-08 09:45:09,2024-04-08 09:46:54,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1002,Publication,https://www.bibsonomy.org/bibtex/29f3b59303571...,"[Artificial, Intelligence, Risks, and, Benefits]",9f3b593035714a894c265f4fb9c535e7,Artificial Intelligence Benefit and Risks,ijtsrd,,2020-05-14 10:40:49,2020-05-14 10:40:49,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1003,Publication,https://www.bibsonomy.org/bibtex/2a97c2267cfe4...,"[industry, artificial_intelligence, health_and...",a97c2267cfe4a39d368f1507149affd0,Artificial intelligence in Industry 4.0: Impli...,meneteqel,,2024-08-01 15:21:53,2024-08-01 15:21:53,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1004,Publication,https://www.bibsonomy.org/bibtex/2df98b0d20723...,"[Human, Intelligence,, intelligence,, centric,...",df98b0d20723566bfc445b3da9e69ac2,Evolution of Artificial Intelligence by Prompt...,ijtsrd,,2024-12-30 07:46:23,2024-12-30 07:46:23,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,Publication,https://www.bibsonomy.org/bibtex/20eb599f35759...,[dblp],0eb599f35759d6724fa55f4552f0eeec,Securing Intelligent Autonomous Systems Throug...,dblp,,2023-03-10 00:00:00,2024-04-09 12:57:10,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1996,Publication,https://www.bibsonomy.org/bibtex/259c82e49dd3c...,"[image, artificial, design,, and, human-comput...",59c82e49dd3c187658e7019e2c58f8c8,An Analysis on the Use of Image Design with Ge...,ijtsrd,,2024-03-08 07:51:43,2024-03-08 07:51:43,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1997,Publication,https://www.bibsonomy.org/bibtex/24ccc5d8128ef...,[dblp],4ccc5d8128ef4b4ba28594fdcee31bed,Analysis of Artificial Intelligence Applied in...,dblp,,2023-01-10 00:00:00,2024-04-10 01:50:25,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998,Publication,https://www.bibsonomy.org/bibtex/268db9fb41250...,[dblp],68db9fb412509b02d6b0cba5eb2876a9,Tenth Scandinavian Conference on Artificial In...,dblp,,2021-02-15 00:00:00,2024-04-09 20:31:41,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999,Publication,https://www.bibsonomy.org/bibtex/2b95d8d066e7c...,[dblp],b95d8d066e7c61335df7c4dddf756d10,Thirteenth Scandinavian Conference on Artifici...,dblp,,2015-11-02 00:00:00,2024-10-07 09:21:15,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
#drops columns where at least 50% of the rows have missing values
df_ai_filtered = df_ai.dropna(axis=1, thresh=len(df_ai)*0.5)

In [24]:
df_ai_filtered.columns

Index(['type', 'id', 'tags', 'intraHash', 'label', 'user', 'description',
       'date', 'changeDate', 'count', 'url', 'interHash', 'pub-type', 'year',
       'author', 'authors', 'volume', 'pages', 'bibtexKey', 'publisher'],
      dtype='object')

In [26]:
#lets only use columns which seems useful for us
useful_coulmns = ['id', 'tags', 'label', 'description', 'date', 'changeDate', 'url', 'pub-type', 'year', 'author', 'authors']
df_ai_filtered = df_ai_filtered[useful_coulmns]

In [28]:
#initialise pyterrier
if pt.java.started():
    pt.java.init()

In [30]:
#pyterrier exspects a docno field
df_ai_filtered['docno'] = df_ai_filtered['id']
df_ai_filtered['text'] = df_ai_filtered['label']

In [32]:
#excursus indexing

In [34]:
#now we start to index our data
#more details at https://pyterrier.readthedocs.io/en/latest/terrier-indexing.html

index_folder = "./ai_index"

indexer = pt.DFIndexer(index_folder, overwrite=True)
index_ref = indexer.index(df_ai_filtered['text'], df_ai_filtered['docno'])

print(f"path to our index: {index_ref.toString()}")

/var/folders/88/9blsh45918g8y3n5vl6vztxr0000gq/T/ipykernel_2259/2741070391.py:6: DeprecationWarning: Call to deprecated class DFIndexer. (use pt.terrier.IterDictIndexer().index(dataframe.to_dict(orient='records')) instead) -- Deprecated since version 0.11.0.
  indexer = pt.DFIndexer(index_folder, overwrite=True)
Java started (triggered by TerrierIndexer.__init__) and loaded: pyterrier.java, pyterrier.terrier.java [version=5.11 (build: craig.macdonald 2025-01-13 21:29), helper_version=0.0.8]

path to our index: ./ai_index/data.properties

In [36]:
#load our index
index = pt.IndexFactory.of(index_ref)

In [38]:
print(index.getCollectionStatistics().toString())

Number of documents: 1000
Number of terms: 1420
Number of postings: 6189
Number of fields: 0
Number of tokens: 6417
Field names: []
Positions:   false

In [40]:
#term -> term_id Nt Tf
#Nt: In how many documents does the term occur
#TF: How often does the term occur in total

for kv in index.getLexicon():
    print(f"{kv.getKey()} -> {kv.getValue().toString()}")

0 -> term12 Nt=5 TF=6 maxTF=2 @{0 0 0}
02 -> term571 Nt=1 TF=1 maxTF=1 @{0 8 1}
1 -> term1013 Nt=1 TF=1 maxTF=1 @{0 10 1}
10 -> term1042 Nt=2 TF=2 maxTF=1 @{0 12 5}
10th -> term518 Nt=2 TF=2 maxTF=1 @{0 16 5}
11 -> term1101 Nt=1 TF=1 maxTF=1 @{0 20 7}
11th -> term1176 Nt=4 TF=4 maxTF=1 @{0 23 3}
12 -> term477 Nt=1 TF=1 maxTF=1 @{0 31 1}
12th -> term1097 Nt=4 TF=4 maxTF=1 @{0 33 1}
13 -> term1174 Nt=1 TF=1 maxTF=1 @{0 40 3}
13th -> term1249 Nt=3 TF=3 maxTF=1 @{0 42 7}
14 -> term1041 Nt=1 TF=1 maxTF=1 @{0 48 7}
14th -> term1043 Nt=4 TF=4 maxTF=1 @{0 51 3}
15th -> term1040 Nt=4 TF=4 maxTF=1 @{0 58 7}
16 -> term1318 Nt=1 TF=1 maxTF=1 @{0 65 5}
16th -> term901 Nt=4 TF=4 maxTF=1 @{0 68 1}
17 -> term1173 Nt=1 TF=1 maxTF=1 @{0 75 3}
17th -> term958 Nt=4 TF=4 maxTF=1 @{0 77 7}
18 -> term1257 Nt=2 TF=2 maxTF=1 @{0 84 7}
185 -> term712 Nt=2 TF=2 maxTF=1 @{0 88 7}
18th -> term572 Nt=3 TF=3 maxTF=1 @{0 91 5}
19 -> term209 Nt=4 TF=4 maxTF=1 @{0 97 7}
1955 -> term974 Nt=1 TF=1 maxTF=1 @{0 105 3}
1970 -> term710 Nt=2 TF=2 maxTF=1 @{0 107 5}
1971 -> term709 Nt=2 TF=2 maxTF=1 @{0 110 3}
1997 -> term1171 Nt=1 TF=1 maxTF=1 @{0 113 1}
1998 -> term1177 Nt=1 TF=1 maxTF=1 @{0 115 5}
1999 -> term1099 Nt=1 TF=1 maxTF=1 @{0 118 1}
19th -> term955 Nt=4 TF=4 maxTF=1 @{0 120 5}
2 -> term720 Nt=9 TF=9 maxTF=1 @{0 128 5}
20 -> term607 Nt=3 TF=3 maxTF=1 @{0 141 1}
2000 -> term1309 Nt=1 TF=1 maxTF=1 @{0 146 7}
2001 -> term1045 Nt=1 TF=2 maxTF=2 @{0 149 3}
2002 -> term1038 Nt=1 TF=2 maxTF=2 @{0 152 0}
2003 -> term577 Nt=3 TF=4 maxTF=2 @{0 154 5}
2004 -> term295 Nt=2 TF=3 maxTF=2 @{0 160 6}
2005 -> term962 Nt=2 TF=4 maxTF=2 @{0 164 7}
2006 -> term609 Nt=5 TF=7 maxTF=2 @{0 169 3}
2007 -> term1016 Nt=1 TF=2 maxTF=2 @{0 178 7}
2008 -> term1010 Nt=3 TF=6 maxTF=2 @{0 181 4}
2010 -> term1246 Nt=1 TF=1 maxTF=1 @{0 188 3}
2011 -> term381 Nt=2 TF=3 maxTF=2 @{0 190 7}
2012 -> term1085 Nt=2 TF=4 maxTF=3 @{0 195 2}
2013 -> term165 Nt=2 TF=2 maxTF=1 @{0 199 4}
2014 -> term163 Nt=3 TF=3 maxTF=1 @{0 203 4}
2015 -> term1134 Nt=2 TF=3 maxTF=2 @{0 209 2}
2016 -> term1154 Nt=2 TF=4 maxTF=3 @{0 214 1}
2017 -> term1338 Nt=1 TF=1 maxTF=1 @{0 217 5}
2018 -> term519 Nt=1 TF=2 maxTF=2 @{0 220 1}
2019 -> term369 Nt=1 TF=2 maxTF=2 @{0 222 2}
2020 -> term1004 Nt=1 TF=1 maxTF=1 @{0 224 3}
2021 -> term979 Nt=2 TF=4 maxTF=2 @{0 226 7}
2022 -> term892 Nt=4 TF=5 maxTF=2 @{0 231 3}
2023 -> term761 Nt=4 TF=8 maxTF=2 @{0 238 6}
2024 -> term1191 Nt=1 TF=2 maxTF=2 @{0 246 6}
20th -> term1017 Nt=3 TF=3 maxTF=1 @{0 249 3}
21 -> term606 Nt=4 TF=4 maxTF=1 @{0 255 5}
21st -> term46 Nt=3 TF=3 maxTF=1 @{0 262 1}
22 -> term1132 Nt=5 TF=5 maxTF=1 @{0 267 3}
22nd -> term370 Nt=2 TF=2 maxTF=1 @{0 275 1}
23 -> term367 Nt=3 TF=3 maxTF=1 @{0 279 3}
23rd -> term1209 Nt=1 TF=1 maxTF=1 @{0 284 3}
24 -> term1084 Nt=4 TF=4 maxTF=1 @{0 286 7}
24th -> term385 Nt=2 TF=2 maxTF=1 @{0 293 5}
25 -> term366 Nt=4 TF=4 maxTF=1 @{0 298 1}
25th -> term1197 Nt=2 TF=2 maxTF=1 @{0 305 5}
26 -> term759 Nt=5 TF=5 maxTF=1 @{0 309 7}
26th -> term1192 Nt=1 TF=1 maxTF=1 @{0 319 5}
27 -> term1165 Nt=3 TF=3 maxTF=1 @{0 322 1}
27th -> term166 Nt=1 TF=1 maxTF=1 @{0 327 7}
28 -> term1149 Nt=3 TF=3 maxTF=1 @{0 329 3}
29 -> term1151 Nt=1 TF=1 maxTF=1 @{0 335 1}
2nd -> term444 Nt=7 TF=7 maxTF=1 @{0 337 5}
3 -> term623 Nt=6 TF=6 maxTF=1 @{0 347 1}
30 -> term758 Nt=4 TF=4 maxTF=1 @{0 356 7}
31 -> term973 Nt=2 TF=2 maxTF=1 @{0 365 1}
34th -> term978 Nt=1 TF=1 maxTF=1 @{0 369 3}
35th -> term921 Nt=1 TF=1 maxTF=1 @{0 371 5}
36th -> term1087 Nt=1 TF=1 maxTF=1 @{0 373 7}
3d -> term858 Nt=1 TF=1 maxTF=1 @{0 376 3}
3rd -> term1235 Nt=2 TF=2 maxTF=1 @{0 378 5}
4 -> term11 Nt=16 TF=16 maxTF=1 @{0 382 7}
4099 -> term832 Nt=1 TF=1 maxTF=1 @{0 401 7}
5 -> term386 Nt=7 TF=7 maxTF=1 @{0 404 1}
50 -> term746 Nt=1 TF=1 maxTF=1 @{0 415 5}
50th -> term744 Nt=1 TF=1 maxTF=1 @{0 417 7}
5g -> term1408 Nt=1 TF=1 maxTF=1 @{0 420 1}
6 -> term170 Nt=6 TF=6 maxTF=1 @{0 422 5}
60th -> term271 Nt=2 TF=2 maxTF=1 @{0 433 1}
6g -> term826 Nt=2 TF=2 maxTF=1 @{0 435 1}
7 -> term1104 Nt=1 TF=1 maxTF=1 @{0 439 5}
7th -> term249 Nt=1 TF=1 maxTF=1 @{0 442 1}
8 -> term384 Nt=3 TF=3 maxTF=1 @{0 443 7}
9 -> term169 Nt=3 TF=3 maxTF=1 @{0 449 7}
900mhz -> term941 Nt=1 TF=1 maxTF=1 @{0 455 3}
97 -> term1169 Nt=1 TF=1 maxTF=1 @{0 457 5}
98 -> term1175 Nt=1 TF=1 maxTF=1 @{0 460 1}
99 -> term1098 Nt=1 TF=1 maxTF=1 @{0 462 5}
9th -> term834 Nt=1 TF=1 maxTF=1 @{0 465 1}
aaai -> term292 Nt=2 TF=2 maxTF=1 @{0 467 3}
abuja -> term225 Nt=2 TF=2 maxTF=1 @{0 471 1}
academ -> term327 Nt=1 TF=1 maxTF=1 @{0 475 1}
accept -> term419 Nt=1 TF=1 maxTF=1 @{0 476 7}
access -> term748 Nt=1 TF=1 maxTF=1 @{0 478 7}
accord -> term138 Nt=1 TF=1 maxTF=1 @{0 481 1}
accur -> term454 Nt=1 TF=1 maxTF=1 @{0 482 5}
achiev -> term566 Nt=2 TF=2 maxTF=1 @{0 484 5}
across -> term68 Nt=2 TF=2 maxTF=1 @{0 488 7}
act -> term695 Nt=2 TF=2 maxTF=1 @{0 492 3}
action -> term1405 Nt=1 TF=1 maxTF=1 @{0 496 7}
actor -> term179 Nt=1 TF=1 maxTF=1 @{0 499 3}
acut -> term829 Nt=3 TF=3 maxTF=1 @{0 500 7}
adapt -> term254 Nt=9 TF=9 maxTF=1 @{0 504 1}
adelaid -> term1044 Nt=1 TF=1 maxTF=1 @{0 516 3}
adjust -> term1129 Nt=1 TF=1 maxTF=1 @{0 518 7}
adopt -> term737 Nt=1 TF=1 maxTF=1 @{0 521 3}
advanc -> term173 Nt=24 TF=24 maxTF=1 @{0 523 5}
advantag -> term379 Nt=3 TF=3 maxTF=1 @{0 551 3}
advent -> term256 Nt=2 TF=2 maxTF=1 @{0 556 1}
adversari -> term1117 Nt=1 TF=1 maxTF=1 @{0 559 7}
aerial -> term783 Nt=1 TF=1 maxTF=1 @{0 562 3}
aerospac -> term306 Nt=2 TF=2 maxTF=1 @{0 564 5}
aesthet -> term1145 Nt=2 TF=2 maxTF=1 @{0 568 5}
affect -> term308 Nt=2 TF=2 maxTF=1 @{0 573 1}
ag -> term156 Nt=8 TF=8 maxTF=1 @{0 577 1}
agenc -> term428 Nt=2 TF=2 maxTF=1 @{0 589 7}
agenda -> term298 Nt=1 TF=1 maxTF=1 @{0 594 1}
agent -> term445 Nt=11 TF=11 maxTF=1 @{0 595 7}
agi -> term611 Nt=1 TF=1 maxTF=1 @{0 612 1}
agil -> term891 Nt=1 TF=1 maxTF=1 @{0 614 1}
agricultur -> term1 Nt=1 TF=1 maxTF=1 @{0 616 3}
ai -> term102 Nt=63 TF=64 maxTF=2 @{0 616 5}
aim -> term41 Nt=3 TF=3 maxTF=1 @{0 675 6}
air -> term913 Nt=1 TF=1 maxTF=1 @{0 679 4}
al -> term168 Nt=1 TF=1 maxTF=1 @{0 681 6}
alberta -> term1308 Nt=1 TF=1 maxTF=1 @{0 683 2}
algebra -> term1061 Nt=1 TF=1 maxTF=1 @{0 685 6}
algorithm -> term150 Nt=14 TF=15 maxTF=2 @{0 688 2}
alicant -> term1086 Nt=1 TF=1 maxTF=1 @{0 707 3}
alloc -> term1068 Nt=1 TF=1 maxTF=1 @{0 709 7}
alphazero -> term131 Nt=1 TF=1 maxTF=1 @{0 712 3}
alt -> term523 Nt=1 TF=1 maxTF=1 @{0 713 7}
ambient -> term1100 Nt=1 TF=1 maxTF=1 @{0 715 7}
america -> term1007 Nt=1 TF=1 maxTF=1 @{0 718 3}
amsterdam -> term1256 Nt=1 TF=1 maxTF=1 @{0 720 7}
analog -> term987 Nt=3 TF=3 maxTF=1 @{0 723 3}
analysi -> term16 Nt=27 TF=27 maxTF=1 @{0 728 3}
analyt -> term753 Nt=1 TF=1 maxTF=1 @{0 760 5}
analyz -> term852 Nt=2 TF=2 maxTF=1 @{0 762 7}
andcclassif -> term853 Nt=1 TF=1 maxTF=1 @{0 766 5}
android -> term803 Nt=1 TF=1 maxTF=1 @{0 768 7}
andromeda -> term630 Nt=1 TF=1 maxTF=1 @{0 771 1}
anim -> term1351 Nt=1 TF=1 maxTF=1 @{0 773 3}
anniversari -> term272 Nt=4 TF=4 maxTF=1 @{0 775 7}
annot -> term990 Nt=4 TF=4 maxTF=1 @{0 782 1}
anomali -> term1210 Nt=4 TF=4 maxTF=1 @{0 786 3}
answer -> term1225 Nt=1 TF=1 maxTF=1 @{0 791 5}
anti -> term557 Nt=3 TF=3 maxTF=1 @{0 794 1}
antidot -> term1001 Nt=1 TF=1 maxTF=1 @{0 799 7}
antimicrobi -> term352 Nt=1 TF=1 maxTF=1 @{0 802 3}
apex -> term728 Nt=1 TF=1 maxTF=1 @{0 804 3}
appli -> term154 Nt=3 TF=3 maxTF=1 @{0 806 5}
applic -> term42 Nt=49 TF=49 maxTF=1 @{0 812 7}
apprais -> term348 Nt=1 TF=1 maxTF=1 @{0 858 3}
approach -> term189 Nt=45 TF=45 maxTF=1 @{0 860 1}
archaeolog -> term1384 Nt=1 TF=1 maxTF=1 @{0 903 7}
architectur -> term610 Nt=8 TF=8 maxTF=1 @{0 906 3}
archon -> term1028 Nt=2 TF=2 maxTF=1 @{0 920 5}
arduino -> term1268 Nt=1 TF=1 maxTF=1 @{0 923 7}
area -> term227 Nt=4 TF=4 maxTF=1 @{0 926 3}
argument -> term1002 Nt=4 TF=4 maxTF=1 @{0 934 1}
arm -> term1267 Nt=1 TF=1 maxTF=1 @{0 942 1}
arpa -> term711 Nt=2 TF=2 maxTF=1 @{0 944 5}
art -> term47 Nt=6 TF=6 maxTF=1 @{0 947 3}
artifact -> term838 Nt=1 TF=1 maxTF=1 @{0 958 1}
artifici -> term2 Nt=868 TF=929 maxTF=3 @{0 960 3}
artist -> term1185 Nt=2 TF=2 maxTF=1 @{0 1209 2}
aspect -> term700 Nt=3 TF=3 maxTF=1 @{0 1213 4}
assess -> term239 Nt=7 TF=7 maxTF=1 @{0 1218 0}
assist -> term113 Nt=6 TF=6 maxTF=1 @{0 1230 2}
associ -> term364 Nt=16 TF=16 maxTF=1 @{0 1239 4}
astro2020 -> term422 Nt=1 TF=1 maxTF=1 @{0 1257 0}
atla -> term650 Nt=2 TF=2 maxTF=1 @{0 1259 0}
attack -> term771 Nt=3 TF=3 maxTF=1 @{0 1262 6}
attempt -> term284 Nt=1 TF=1 maxTF=1 @{0 1268 4}
attend -> term1363 Nt=1 TF=1 maxTF=1 @{0 1270 2}
attent -> term145 Nt=1 TF=1 maxTF=1 @{0 1272 6}
auckland -> term1011 Nt=1 TF=1 maxTF=1 @{0 1274 2}
audienc -> term1342 Nt=1 TF=1 maxTF=1 @{0 1276 6}
audit -> term550 Nt=1 TF=1 maxTF=1 @{0 1279 2}
augment -> term301 Nt=5 TF=5 maxTF=1 @{0 1281 2}
august -> term977 Nt=4 TF=4 maxTF=1 @{0 1290 2}
australasian -> term387 Nt=2 TF=2 maxTF=1 @{0 1297 4}
australia -> term380 Nt=12 TF=12 maxTF=1 @{0 1301 6}
australian -> term902 Nt=10 TF=10 maxTF=1 @{0 1315 2}
authent -> term1075 Nt=1 TF=1 maxTF=1 @{0 1326 0}
autoaiviz -> term1110 Nt=1 TF=1 maxTF=1 @{0 1328 4}
autom -> term148 Nt=6 TF=6 maxTF=1 @{0 1331 0}
automat -> term743 Nt=1 TF=1 maxTF=1 @{0 1339 6}
autonom -> term92 Nt=3 TF=3 maxTF=1 @{0 1342 0}
autonomi -> term842 Nt=2 TF=2 maxTF=1 @{0 1348 0}
avatar -> term1146 Nt=1 TF=1 maxTF=1 @{0 1351 2}
avoid -> term940 Nt=1 TF=1 maxTF=1 @{0 1353 6}
awar -> term1182 Nt=1 TF=1 maxTF=1 @{0 1356 0}
axiom -> term791 Nt=1 TF=1 maxTF=1 @{0 1358 4}
back -> term1263 Nt=1 TF=1 maxTF=1 @{0 1360 6}
banff -> term1307 Nt=1 TF=1 maxTF=1 @{0 1363 2}
bank -> term109 Nt=3 TF=3 maxTF=1 @{0 1365 6}
bankruptci -> term1322 Nt=1 TF=1 maxTF=1 @{0 1371 2}
barcelona -> term1131 Nt=3 TF=3 maxTF=1 @{0 1373 6}
barrier -> term1360 Nt=1 TF=1 maxTF=1 @{0 1378 6}
base -> term29 Nt=54 TF=55 maxTF=2 @{0 1381 2}
basi -> term906 Nt=1 TF=1 maxTF=1 @{0 1435 7}
basic -> term78 Nt=1 TF=1 maxTF=1 @{0 1438 1}
bayesian -> term289 Nt=9 TF=9 maxTF=1 @{0 1439 3}
be -> term734 Nt=1 TF=1 maxTF=1 @{0 1453 1}
behavior -> term539 Nt=4 TF=4 maxTF=1 @{0 1455 3}
belief -> term1135 Nt=4 TF=4 maxTF=1 @{0 1462 5}
benefici -> term1382 Nt=1 TF=1 maxTF=1 @{0 1468 5}
benefit -> term6 Nt=3 TF=3 maxTF=1 @{0 1471 1}
benet -> term1280 Nt=1 TF=1 maxTF=1 @{0 1475 3}
best -> term1364 Nt=2 TF=2 maxTF=1 @{0 1477 7}
bibliographi -> term618 Nt=1 TF=1 maxTF=1 @{0 1482 1}
bid -> term947 Nt=1 TF=1 maxTF=1 @{0 1484 3}
big -> term275 Nt=4 TF=5 maxTF=2 @{0 1486 5}
biochemistri -> term450 Nt=1 TF=1 maxTF=1 @{0 1494 4}
bioinformat -> term814 Nt=1 TF=1 maxTF=1 @{0 1496 4}
biolog -> term915 Nt=5 TF=5 maxTF=1 @{0 1498 6}
biologi -> term564 Nt=7 TF=7 maxTF=1 @{0 1506 0}
biomed -> term1214 Nt=1 TF=1 maxTF=1 @{0 1515 2}
biometr -> term1359 Nt=1 TF=1 maxTF=1 @{0 1517 6}
black -> term535 Nt=1 TF=1 maxTF=1 @{0 1520 2}
blackbox -> term1109 Nt=1 TF=1 maxTF=1 @{0 1522 2}
blockchain -> term486 Nt=5 TF=6 maxTF=2 @{0 1524 6}
book -> term790 Nt=2 TF=2 maxTF=1 @{0 1534 1}
boon -> term211 Nt=1 TF=1 maxTF=1 @{0 1538 1}
boost -> term1374 Nt=1 TF=1 maxTF=1 @{0 1539 7}
bottom -> term1144 Nt=1 TF=1 maxTF=1 @{0 1542 3}
bound -> term899 Nt=1 TF=1 maxTF=1 @{0 1544 7}
box -> term533 Nt=1 TF=1 maxTF=1 @{0 1547 1}
brain -> term602 Nt=4 TF=4 maxTF=1 @{0 1549 1}
brazilian -> term875 Nt=1 TF=1 maxTF=1 @{0 1555 7}
breast -> term524 Nt=2 TF=2 maxTF=1 @{0 1558 1}
breed -> term697 Nt=1 TF=1 maxTF=1 @{0 1562 3}
bridg -> term945 Nt=1 TF=1 maxTF=1 @{0 1564 5}
bring -> term1239 Nt=1 TF=1 maxTF=1 @{0 1566 7}
brisban -> term1172 Nt=1 TF=1 maxTF=1 @{0 1569 3}
broad -> term1031 Nt=1 TF=1 maxTF=1 @{0 1571 7}
broadband -> term1324 Nt=1 TF=1 maxTF=1 @{0 1574 3}
broadcast -> term1074 Nt=1 TF=1 maxTF=1 @{0 1576 7}
brutu -> term439 Nt=1 TF=1 maxTF=1 @{0 1579 3}
build -> term250 Nt=6 TF=6 maxTF=1 @{0 1581 3}
built -> term593 Nt=1 TF=1 maxTF=1 @{0 1590 5}
burden -> term628 Nt=1 TF=1 maxTF=1 @{0 1592 5}
busi -> term332 Nt=4 TF=4 maxTF=1 @{0 1594 7}
cai -> term705 Nt=2 TF=2 maxTF=1 @{0 1602 3}
caibda -> term1317 Nt=1 TF=1 maxTF=1 @{0 1606 5}
cairn -> term957 Nt=1 TF=1 maxTF=1 @{0 1609 1}
call -> term950 Nt=1 TF=1 maxTF=1 @{0 1611 3}
cambridg -> term1243 Nt=1 TF=1 maxTF=1 @{0 1613 5}
camera -> term1115 Nt=1 TF=1 maxTF=1 @{0 1616 1}
can -> term351 Nt=10 TF=10 maxTF=1 @{0 1618 5}
canada -> term171 Nt=4 TF=4 maxTF=1 @{0 1633 5}
canadian -> term164 Nt=4 TF=7 maxTF=2 @{0 1641 1}
canai -> term1089 Nt=1 TF=1 maxTF=1 @{0 1648 2}
canberra -> term1039 Nt=1 TF=1 maxTF=1 @{0 1650 6}
cancer -> term525 Nt=5 TF=5 maxTF=1 @{0 1653 2}
capabl -> term781 Nt=1 TF=1 maxTF=1 @{0 1661 0}
capit -> term1389 Nt=1 TF=1 maxTF=1 @{0 1663 2}
caption -> term1402 Nt=1 TF=1 maxTF=1 @{0 1665 6}
captur -> term459 Nt=1 TF=1 maxTF=1 @{0 1668 2}
car -> term1051 Nt=1 TF=1 maxTF=1 @{0 1670 2}
card -> term944 Nt=1 TF=1 maxTF=1 @{0 1672 6}
cardiac -> term498 Nt=4 TF=4 maxTF=1 @{0 1675 0}
cardiolog -> term93 Nt=1 TF=1 maxTF=1 @{0 1680 0}
care -> term1092 Nt=2 TF=2 maxTF=1 @{0 1681 2}
carlo -> term967 Nt=1 TF=1 maxTF=1 @{0 1685 4}
case -> term260 Nt=7 TF=7 maxTF=1 @{0 1687 6}
castl -> term1102 Nt=1 TF=1 maxTF=1 @{0 1699 0}
catalan -> term372 Nt=15 TF=15 maxTF=1 @{0 1701 4}
catalogu -> term766 Nt=1 TF=1 maxTF=1 @{0 1718 4}
catalonia -> term521 Nt=6 TF=6 maxTF=1 @{0 1720 6}
catalyz -> term51 Nt=1 TF=1 maxTF=1 @{0 1727 0}
categori -> term1143 Nt=1 TF=1 maxTF=1 @{0 1728 0}
caus -> term938 Nt=1 TF=1 maxTF=1 @{0 1730 4}
causabl -> term1203 Nt=1 TF=1 maxTF=1 @{0 1732 6}
causal -> term1259 Nt=2 TF=2 maxTF=1 @{0 1735 2}
ccia -> term365 Nt=7 TF=7 maxTF=1 @{0 1738 6}
celebr -> term1196 Nt=1 TF=1 maxTF=1 @{0 1748 6}
cell -> term451 Nt=2 TF=2 maxTF=1 @{0 1751 2}
censu -> term1005 Nt=1 TF=1 maxTF=1 @{0 1755 4}
center -> term512 Nt=2 TF=2 maxTF=1 @{0 1758 0}
centric -> term1352 Nt=1 TF=1 maxTF=1 @{0 1761 4}
centuri -> term50 Nt=2 TF=2 maxTF=1 @{0 1764 0}
cervic -> term932 Nt=1 TF=2 maxTF=2 @{0 1767 4}
chain -> term314 Nt=2 TF=2 maxTF=1 @{0 1769 7}
challeng -> term111 Nt=19 TF=19 maxTF=1 @{0 1773 7}
chang -> term508 Nt=3 TF=3 maxTF=1 @{0 1798 5}
changer -> term194 Nt=1 TF=1 maxTF=1 @{0 1804 3}
character -> term1138 Nt=2 TF=2 maxTF=1 @{0 1806 1}
charl -> term1312 Nt=1 TF=1 maxTF=1 @{0 1809 5}
chatbot -> term984 Nt=1 TF=1 maxTF=1 @{0 1812 1}
chatgpt -> term599 Nt=4 TF=4 maxTF=1 @{0 1814 3}
check -> term739 Nt=1 TF=1 maxTF=1 @{0 1821 5}
china -> term1090 Nt=3 TF=3 maxTF=1 @{0 1823 7}
cim -> term1341 Nt=1 TF=1 maxTF=1 @{0 1829 1}
citi -> term872 Nt=1 TF=1 maxTF=1 @{0 1831 5}
classif -> term344 Nt=5 TF=5 maxTF=1 @{0 1833 7}
classifi -> term1260 Nt=1 TF=1 maxTF=1 @{0 1842 5}
clean -> term185 Nt=1 TF=1 maxTF=1 @{0 1845 1}
clinic -> term330 Nt=6 TF=6 maxTF=1 @{0 1846 7}
clone -> term1277 Nt=1 TF=1 maxTF=1 @{0 1856 7}
close -> term1220 Nt=2 TF=2 maxTF=1 @{0 1859 3}
cloud -> term527 Nt=4 TF=4 maxTF=1 @{0 1863 5}
cluster -> term1147 Nt=1 TF=1 maxTF=1 @{0 1870 7}
coalesc -> term801 Nt=1 TF=1 maxTF=1 @{0 1873 3}
coast -> term1015 Nt=1 TF=1 maxTF=1 @{0 1875 5}
code -> term1036 Nt=1 TF=1 maxTF=1 @{0 1878 1}
cognit -> term568 Nt=7 TF=7 maxTF=1 @{0 1880 5}
collabor -> term302 Nt=5 TF=5 maxTF=1 @{0 1892 5}
collect -> term617 Nt=2 TF=2 maxTF=1 @{0 1901 3}
colleg -> term907 Nt=1 TF=1 maxTF=1 @{0 1906 1}
colloqui -> term337 Nt=1 TF=1 maxTF=1 @{0 1908 3}
combat -> term436 Nt=2 TF=2 maxTF=1 @{0 1910 1}
combin -> term447 Nt=5 TF=5 maxTF=1 @{0 1914 1}
comic -> term622 Nt=1 TF=1 maxTF=1 @{0 1923 5}
commerc -> term116 Nt=1 TF=1 maxTF=1 @{0 1925 7}
commerci -> term258 Nt=1 TF=1 maxTF=1 @{0 1927 3}
common -> term516 Nt=2 TF=2 maxTF=1 @{0 1929 1}
commonsens -> term1258 Nt=1 TF=1 maxTF=1 @{0 1932 7}
commun -> term418 Nt=2 TF=2 maxTF=1 @{0 1935 3}
compani -> term679 Nt=2 TF=2 maxTF=1 @{0 1939 5}
compar -> term56 Nt=1 TF=1 maxTF=1 @{0 1943 1}
comparison -> term1295 Nt=1 TF=1 maxTF=1 @{0 1944 3}
compat -> term840 Nt=1 TF=1 maxTF=1 @{0 1946 7}
compendium -> term715 Nt=1 TF=1 maxTF=1 @{0 1949 1}
compet -> term1124 Nt=3 TF=3 maxTF=1 @{0 1951 3}
complex -> term845 Nt=6 TF=6 maxTF=1 @{0 1955 5}
compon -> term1334 Nt=1 TF=1 maxTF=1 @{0 1964 5}
composit -> term1033 Nt=1 TF=1 maxTF=1 @{0 1967 1}
comprehens -> term105 Nt=6 TF=6 maxTF=1 @{0 1969 5}
comput -> term75 Nt=33 TF=35 maxTF=2 @{0 1979 1}
concept -> term307 Nt=5 TF=5 maxTF=1 @{0 2016 7}
conceptu -> term802 Nt=3 TF=3 maxTF=1 @{0 2025 3}
concis -> term1241 Nt=1 TF=1 maxTF=1 @{0 2030 7}
condit -> term1111 Nt=1 TF=1 maxTF=1 @{0 2033 3}
conf -> term573 Nt=1 TF=1 maxTF=1 @{0 2035 7}
confer -> term161 Nt=72 TF=72 maxTF=1 @{0 2037 7}
connect -> term638 Nt=1 TF=1 maxTF=1 @{0 2090 1}
connection -> term861 Nt=1 TF=1 maxTF=1 @{0 2092 3}
consciou -> term1212 Nt=1 TF=1 maxTF=1 @{0 2094 5}
conscious -> term262 Nt=5 TF=6 maxTF=2 @{0 2097 1}
constitut -> term655 Nt=1 TF=1 maxTF=1 @{0 2103 6}
constraint -> term405 Nt=1 TF=1 maxTF=1 @{0 2106 0}
construct -> term729 Nt=3 TF=3 maxTF=1 @{0 2108 0}
consumpt -> term252 Nt=1 TF=1 maxTF=1 @{0 2113 6}
content -> term588 Nt=3 TF=3 maxTF=1 @{0 2115 4}
context -> term334 Nt=5 TF=7 maxTF=2 @{0 2122 0}
contextsensit -> term972 Nt=1 TF=1 maxTF=1 @{0 2128 2}
contrast -> term869 Nt=1 TF=1 maxTF=1 @{0 2130 4}
control -> term350 Nt=10 TF=10 maxTF=1 @{0 2132 6}
converg -> term879 Nt=1 TF=1 maxTF=1 @{0 2148 4}
convers -> term1320 Nt=2 TF=2 maxTF=1 @{0 2150 6}
convolut -> term1410 Nt=1 TF=1 maxTF=1 @{0 2154 6}
cooper -> term1215 Nt=2 TF=2 maxTF=1 @{0 2157 2}
coordin -> term409 Nt=3 TF=3 maxTF=1 @{0 2161 4}
corpor -> term1216 Nt=1 TF=1 maxTF=1 @{0 2167 4}
correl -> term1081 Nt=1 TF=1 maxTF=1 @{0 2170 0}
corrupt -> term290 Nt=1 TF=1 maxTF=1 @{0 2172 4}
cosmolog -> term414 Nt=1 TF=1 maxTF=1 @{0 2174 2}
cost -> term649 Nt=3 TF=3 maxTF=1 @{0 2176 2}
cours -> term398 Nt=3 TF=3 maxTF=1 @{0 2182 2}
court -> term286 Nt=1 TF=1 maxTF=1 @{0 2187 6}
cover -> term750 Nt=2 TF=2 maxTF=1 @{0 2189 4}
coverag -> term943 Nt=1 TF=1 maxTF=1 @{0 2193 4}
covid -> term213 Nt=2 TF=2 maxTF=1 @{0 2195 6}
creat -> term1046 Nt=2 TF=2 maxTF=1 @{0 2199 6}
creation -> term160 Nt=2 TF=2 maxTF=1 @{0 2203 6}
creativ -> term48 Nt=6 TF=6 maxTF=1 @{0 2205 6}
critic -> term587 Nt=4 TF=4 maxTF=1 @{0 2216 0}
critiqu -> term988 Nt=1 TF=1 maxTF=1 @{0 2223 0}
cross -> term1372 Nt=1 TF=1 maxTF=1 @{0 2225 2}
crossdisciplinari -> term800 Nt=1 TF=1 maxTF=1 @{0 2227 6}
crowd -> term664 Nt=2 TF=2 maxTF=1 @{0 2230 0}
crude -> term205 Nt=1 TF=1 maxTF=1 @{0 2234 4}
cryptocurr -> term349 Nt=1 TF=1 maxTF=1 @{0 2236 2}
cryptographi -> term1343 Nt=2 TF=2 maxTF=1 @{0 2238 0}
csa -> term934 Nt=1 TF=1 maxTF=1 @{0 2242 0}
cscw -> term604 Nt=1 TF=1 maxTF=1 @{0 2244 2}
cultur -> term968 Nt=2 TF=2 maxTF=1 @{0 2246 2}
curios -> term35 Nt=1 TF=1 maxTF=1 @{0 2250 4}
current -> term520 Nt=2 TF=2 maxTF=1 @{0 2251 4}
curv -> term663 Nt=1 TF=1 maxTF=1 @{0 2255 2}
cyber -> term1183 Nt=1 TF=1 maxTF=1 @{0 2257 4}
cybersecur -> term542 Nt=3 TF=3 maxTF=1 @{0 2260 0}
cyborg -> term1251 Nt=1 TF=1 maxTF=1 @{0 2266 2}
dagstuhl -> term1105 Nt=1 TF=1 maxTF=1 @{0 2268 6}
dartmouth -> term975 Nt=1 TF=1 maxTF=1 @{0 2271 2}
data -> term234 Nt=19 TF=20 maxTF=2 @{0 2273 4}
databas -> term448 Nt=4 TF=4 maxTF=1 @{0 2298 7}
dc -> term608 Nt=1 TF=1 maxTF=1 @{0 2305 1}
ddo -> term772 Nt=1 TF=1 maxTF=1 @{0 2307 1}
de -> term1247 Nt=3 TF=3 maxTF=1 @{0 2309 3}
debat -> term756 Nt=1 TF=1 maxTF=1 @{0 2315 5}
decad -> term318 Nt=1 TF=1 maxTF=1 @{0 2317 7}
deceiv -> term490 Nt=1 TF=1 maxTF=1 @{0 2319 5}
decemb -> term383 Nt=11 TF=11 maxTF=1 @{0 2321 5}
decis -> term637 Nt=5 TF=5 maxTF=1 @{0 2334 5}
dedic -> term745 Nt=1 TF=1 maxTF=1 @{0 2344 5}
deep -> term70 Nt=8 TF=8 maxTF=1 @{0 2346 7}
defens -> term793 Nt=1 TF=1 maxTF=1 @{0 2359 3}
deficit -> term146 Nt=1 TF=1 maxTF=1 @{0 2361 5}
defin -> term674 Nt=2 TF=2 maxTF=1 @{0 2363 1}
definit -> term910 Nt=1 TF=1 maxTF=1 @{0 2367 7}
defuzzif -> term1296 Nt=1 TF=1 maxTF=1 @{0 2370 1}
deliveri -> term1091 Nt=1 TF=1 maxTF=1 @{0 2372 5}
deltebr -> term1339 Nt=1 TF=1 maxTF=1 @{0 2375 1}
demand -> term648 Nt=1 TF=1 maxTF=1 @{0 2377 5}
demetria -> term1276 Nt=1 TF=1 maxTF=1 @{0 2379 7}
demetrio -> term1275 Nt=1 TF=1 maxTF=1 @{0 2382 3}
democraci -> term305 Nt=6 TF=6 maxTF=1 @{0 2384 7}

In [42]:
term = "game"
index.getLexicon()[term].toString()

'term66 Nt=12 TF=13 maxTF=2 @{0 3346 6}'

In [44]:
#how often do the terms occur
term_freq_dict = {}

for kv in index.getLexicon():
    term_freq_dict[kv.getKey()] = kv.getValue().frequency

In [46]:
#sort all terms from the index in descending order 
term_freq_dict_sorted = sorted(term_freq_dict.items(), key=lambda x: x[1], reverse=True)

In [48]:
#show the 30 nost popular entries
top_k = 30
term_freq_dict_sorted[:top_k]

[('intellig', 963),
 ('artifici', 929),
 ('confer', 72),
 ('proceed', 65),
 ('ai', 64),
 ('system', 63),
 ('base', 55),
 ('learn', 51),
 ('applic', 49),
 ('approach', 45),
 ('us', 44),
 ('gener', 40),
 ('human', 40),
 ('research', 36),
 ('comput', 35),
 ('educ', 33),
 ('develop', 28),
 ('nation', 28),
 ('analysi', 27),
 ('review', 26),
 ('technolog', 26),
 ('advanc', 24),
 ('model', 24),
 ('impact', 23),
 ('intern', 23),
 ('machin', 23),
 ('modern', 23),
 ('explain', 22),
 ('futur', 22),
 ('data', 20)]

In [50]:
#define our search engine
search_engine = pt.BatchRetrieve(index, wmodel="Tf")

/var/folders/88/9blsh45918g8y3n5vl6vztxr0000gq/T/ipykernel_2259/2780833963.py:2: DeprecationWarning: Call to deprecated class BatchRetrieve. (use pt.terrier.Retriever() instead) -- Deprecated since version 0.11.0.
  search_engine = pt.BatchRetrieve(index, wmodel="Tf")

In [52]:
search_engine.search("system")

,qid,docid,docno,rank,score,query
0,1,292,https://www.bibsonomy.org/bibtex/24768ef52a6c0...,0,2.0,system
1,1,41,https://www.bibsonomy.org/bibtex/249f58604f738...,1,1.0,system
2,1,68,https://www.bibsonomy.org/bibtex/2f693b1d1c623...,2,1.0,system
3,1,81,https://www.bibsonomy.org/bibtex/28585af0407b9...,3,1.0,system
4,1,84,https://www.bibsonomy.org/bibtex/2f6f3aecbaa29...,4,1.0,system
...,...,...,...,...,...,...
57,1,910,https://www.bibsonomy.org/bibtex/2f951427cc281...,57,1.0,system
58,1,957,https://www.bibsonomy.org/bibtex/293fb4fd88de7...,58,1.0,system
59,1,984,https://www.bibsonomy.org/bibtex/20dac3cd23401...,59,1.0,system
60,1,987,https://www.bibsonomy.org/bibtex/234996efa89f2...,60,1.0,system
61,1,995,https://www.bibsonomy.org/bibtex/20eb599f35759...,61,1.0,system

So the `search()` method returns a dataframe with columns:
 - `qid`: this is by default "1", since it's our first and only query
 - `docid`: Terrier' internal integer for each document
 - `docno`: the external (string) unique identifier for each document
 - `score`: since we use the `Tf` weighting model, this score corresponds the total frequency of the query (terms) in each document
 - `rank`: A handy attribute showing the descending order by score
 - `query`: the input query

As expected, the `Tf` weighting model used here only counts the frequencies of the query terms in each document, i.e.:
$$
score(d,q) = \sum_{t \in q} tf_{t,d}
$$

In [55]:
search_engine.search("intelligent education")

,qid,docid,docno,rank,score,query
0,1,740,https://www.bibsonomy.org/bibtex/2b476e9f37ca1...,0,5.0,intelligent education
1,1,242,https://www.bibsonomy.org/bibtex/2f91c0697115d...,1,3.0,intelligent education
2,1,346,https://www.bibsonomy.org/bibtex/26895e4605d5e...,2,3.0,intelligent education
3,1,348,https://www.bibsonomy.org/bibtex/238a0ee82e84c...,3,3.0,intelligent education
4,1,564,https://www.bibsonomy.org/bibtex/2362d4d486a4a...,4,3.0,intelligent education
...,...,...,...,...,...,...
870,1,989,https://www.bibsonomy.org/bibtex/206f636f05a30...,870,1.0,intelligent education
871,1,991,https://www.bibsonomy.org/bibtex/26db4e5961ea7...,871,1.0,intelligent education
872,1,992,https://www.bibsonomy.org/bibtex/284f798116185...,872,1.0,intelligent education
873,1,998,https://www.bibsonomy.org/bibtex/268db9fb41250...,873,1.0,intelligent education
874,1,999,https://www.bibsonomy.org/bibtex/2b95d8d066e7c...,874,1.0,intelligent education

In [57]:
#what do we need for the inverse document frequency?

In [59]:
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()

In [61]:
#stem the term its base form
stem = stemmer.stem("learning")
stem

'learn'

In [63]:
#in how many documents does the stem 'learn' occur?
lexicon = index.getLexicon()
lexicon[stem].getDocumentFrequency()

49

In [65]:
#how many documents occur in our index?
index.getCollectionStatistics().numberOfDocuments

1000

In [67]:
def get_idf_for_term(term, index):
  lex = index.getLexicon()
  stemmed_term = stemmer.stem(term)

  if not stemmed_term in lex:
    return 
    
  lex_entry = lex[stemmed_term]

  df_term = lex_entry.getDocumentFrequency()
  N = index.getCollectionStatistics().numberOfDocuments
  
  #inverse document frequency
  idf = N/df_term

  #apply logarithm(base 10) to idf
  log_idf = np.emath.logn(10, idf)

  return log_idf

In [69]:
get_idf_for_term("learning", index)

1.3098039199714862

In [71]:
#define your own tf_idf method here:

def calc_tf_idf(query, docno, index):
    #remember that tfidf is the product of two components
    #hint: the tf model search result contains tf frequencies
    return 0

In [73]:
search_engine_tfidf = pt.BatchRetrieve(index, wmodel="TF_IDF")

/var/folders/88/9blsh45918g8y3n5vl6vztxr0000gq/T/ipykernel_2259/2880449899.py:1: DeprecationWarning: Call to deprecated class BatchRetrieve. (use pt.terrier.Retriever() instead) -- Deprecated since version 0.11.0.
  search_engine_tfidf = pt.BatchRetrieve(index, wmodel="TF_IDF")

In [75]:
search_engine_tfidf.search("intelligent education")

,qid,docid,docno,rank,score,query
0,1,837,https://www.bibsonomy.org/bibtex/29cc0434b3e50...,0,4.261447,intelligent education
1,1,943,https://www.bibsonomy.org/bibtex/275d5c245ba41...,1,4.261447,intelligent education
2,1,983,https://www.bibsonomy.org/bibtex/2eb8e8e572869...,2,4.261447,intelligent education
3,1,24,https://www.bibsonomy.org/bibtex/259133e526641...,3,3.940288,intelligent education
4,1,78,https://www.bibsonomy.org/bibtex/259133e526641...,4,3.940288,intelligent education
...,...,...,...,...,...,...
870,1,133,https://www.bibsonomy.org/bibtex/2c4df47ce17b7...,870,0.372299,intelligent education
871,1,231,https://www.bibsonomy.org/bibtex/29fcc0f646278...,871,0.372299,intelligent education
872,1,600,https://www.bibsonomy.org/bibtex/21b69569af8d0...,872,0.372299,intelligent education
873,1,251,https://www.bibsonomy.org/bibtex/2ba15da18da2c...,873,0.344993,intelligent education
874,1,353,https://www.bibsonomy.org/bibtex/24d041e3486cf...,874,0.332790,intelligent education

In [77]:
#Now we want to build an index with multiple fields

In [79]:
df_ai_filtered.columns

Index(['id', 'tags', 'label', 'description', 'date', 'changeDate', 'url',
       'pub-type', 'year', 'author', 'authors', 'docno', 'text'],
      dtype='object')

In [81]:
#transfrom dataframe into list of dictionaries
ai_dict = df_ai_filtered.to_dict(orient='records')

In [83]:
ai_dict

[{'id': 'https://www.bibsonomy.org/bibtex/24e338b04bc2abafd9fa0a1f4fe79103a/ijtsrd',
  'tags': ['710-714'],
  'label': 'Artificial Intelligence in Agriculture',
  'description': '',
  'date': '2021-04-13 13:15:04',
  'changeDate': '2021-04-13 13:15:04',
  'url': 'https://www.ijtsrd.com/engineering/electrical-engineering/38513/artificial-intelligence-in-agriculture/matthew-n-o-sadiku',
  'pub-type': 'article',
  'year': '2021',
  'author': ['Matthew N. O. Sadiku | Sarhan M. Musa | Abayomi Ajayi-Majebi'],
  'authors': [{'first': 'Matthew N. O. Sadiku | Sarhan M. Musa | Abayomi',
    'last': 'Ajayi-Majebi'}],
  'docno': 'https://www.bibsonomy.org/bibtex/24e338b04bc2abafd9fa0a1f4fe79103a/ijtsrd',
  'text': 'Artificial Intelligence in Agriculture'},
 {'id': 'https://www.bibsonomy.org/bibtex/283c4174f111d968e8ca51b252f8fea3e/meneteqel',
  'tags': ['digitalisation',
   'artificial_intelligence',
   'society',
   'labour_rights'],
  'label': 'Artificial intelligence, labour and society',
  'description': '',
  'date': '2024-04-08 09:45:09',
  'changeDate': '2024-04-08 09:46:54',
  'url': 'https://www.etui.org/publications/artificial-intelligence-labour-and-society',
  'pub-type': 'book',
  'year': '2024',
  'author': nan,
  'authors': nan,
  'docno': 'https://www.bibsonomy.org/bibtex/283c4174f111d968e8ca51b252f8fea3e/meneteqel',
  'text': 'Artificial intelligence, labour and society'},
 {'id': 'https://www.bibsonomy.org/bibtex/29f3b593035714a894c265f4fb9c535e7/ijtsrd',
  'tags': ['Artificial', 'Intelligence', 'Risks', 'and', 'Benefits'],
  'label': 'Artificial Intelligence Benefit and Risks',
  'description': '',
  'date': '2020-05-14 10:40:49',
  'changeDate': '2020-05-14 10:40:49',
  'url': 'https://www.ijtsrd.com/computer-science/artificial-intelligence/30232/artificial-intelligence-benefit-and-risks/seeta-m-chauhan',
  'pub-type': 'article',
  'year': '2020',
  'author': ['Seeta M. Chauhan'],
  'authors': [{'first': 'Seeta M.', 'last': 'Chauhan'}],
  'docno': 'https://www.bibsonomy.org/bibtex/29f3b593035714a894c265f4fb9c535e7/ijtsrd',
  'text': 'Artificial Intelligence Benefit and Risks'},
 {'id': 'https://www.bibsonomy.org/bibtex/2a97c2267cfe4a39d368f1507149affd0/meneteqel',
  'tags': ['industry',
   'artificial_intelligence',
   'health_and_safety',
   'produktion'],
  'label': 'Artificial intelligence in Industry 4.0: Implications for occupational safety and health',
  'description': '',
  'date': '2024-08-01 15:21:53',
  'changeDate': '2024-08-01 15:21:53',
  'url': 'https://www.etui.org/publications/artificial-intelligence-industry-40',
  'pub-type': 'book',
  'year': '2024',
  'author': ['Pierre Bérastégui'],
  'authors': [{'first': 'Pierre', 'last': 'Bérastégui'}],
  'docno': 'https://www.bibsonomy.org/bibtex/2a97c2267cfe4a39d368f1507149affd0/meneteqel',
  'text': 'Artificial intelligence in Industry 4.0: Implications for occupational safety and health'},
 {'id': 'https://www.bibsonomy.org/bibtex/2df98b0d20723566bfc445b3da9e69ac2/ijtsrd',
  'tags': ['Human',
   'Intelligence,',
   'intelligence,',
   'centric',
   'Artificialintelligence',
   'AGI,',
   'Ethical',
   'AI'],
  'label': 'Evolution of Artificial Intelligence by Prompt Science Analysis',
  'description': '',
  'date': '2024-12-30 07:46:23',
  'changeDate': '2024-12-30 07:46:23',
  'url': 'https://www.ijtsrd.com/computer-science/artificial-intelligence/69358/evolution-of-artificial-intelligence-by-prompt-science-analysis/manish-verma',
  'pub-type': 'article',
  'year': '2024',
  'author': ['Manish Verma'],
  'authors': [{'first': 'Manish', 'last': 'Verma'}],
  'docno': 'https://www.bibsonomy.org/bibtex/2df98b0d20723566bfc445b3da9e69ac2/ijtsrd',
  'text': 'Evolution of Artificial Intelligence by Prompt Science Analysis'},
 {'id': 'https://www.bibsonomy.org/bibtex/21a31a7056bb1c84ffe568f434b9d565f/ijtsrd',
  'tags': ['robotics,',
   'artificial',
   'intelligence,',
   'exploration,',
   'machine',
   'learning',
   'space',
   'industry,'],
  'label': 'Artificial Intelligence in Space Exploration',
  'description': '',
  'date': '2025-01-02 13:18:33',
  'changeDate': '2025-01-02 13:18:33',
  'url': 'https://www.ijtsrd.com/computer-science/artificial-intelligence/70469/artificial-intelligence-in-space-exploration/matthew-n-o-sadiku',
  'pub-type': 'article',
  'year': '2024',
  'author': ['Matthew N. O. Sadiku | Paul A. Adekunte | Janet O. Sadiku'],
  'authors': [{'first': 'Matthew N. O. Sadiku | Paul A. Adekunte | Janet O.',
    'last': 'Sadiku'}],
  'docno': 'https://www.bibsonomy.org/bibtex/21a31a7056bb1c84ffe568f434b9d565f/ijtsrd',
  'text': 'Artificial Intelligence in Space Exploration'},
 {'id': 'https://www.bibsonomy.org/bibtex/2f76cb3964befb565e8456efb255b9918/brusilovsky',
  'tags': ['explanation'],
  'label': 'Explanation in artificial intelligence: Insights from the social sciences',
  'description': 'Explanation in artificial intelligence: Insights from the social sciences - ScienceDirect',
  'date': '2023-06-05 00:07:52',
  'changeDate': '2023-06-05 00:07:52',
  'url': 'https://www.sciencedirect.com/science/article/pii/S0004370218305988',
  'pub-type': 'article',
  'year': '2019',
  'author': ['Tim Miller'],
  'authors': [{'first': 'Tim', 'last': 'Miller'}],
  'docno': 'https://www.bibsonomy.org/bibtex/2f76cb3964befb565e8456efb255b9918/brusilovsky',
  'text': 'Explanation in artificial intelligence: Insights from the social sciences'},
 {'id': 'https://www.bibsonomy.org/bibtex/24bc08fb79365b5bc698af1cd97fc1a75/ijtsrd',
  'tags': ['ANN',
   'Fuzzylogic',
   'ElectricalEngineering',
   'Artificialintelligence'],
  'label': 'Artificial Intelligence in Power Station',
  'description': '',
  'date': '2020-01-10 09:23:37',
  'changeDate': '2020-01-10 09:23:37',
  'url': 'https://www.ijtsrd.com/engineering/electrical-engineering/29784/artificial-intelligence-in-power-station/p-naveen',
  'pub-type': 'article',
  'year': '2019',
  'author': ['P. Naveen | S. Nikitha | P. Sudeesh | V. Vaishnavi'],
  'authors': [{'first': 'P. Naveen | S. Nikitha | P. Sudeesh | V.',
    'last': 'Vaishnavi'}],
  'docno': 'https://www.bibsonomy.org/bibtex/24bc08fb79365b5bc698af1cd97fc1a75/ijtsrd',
  'text': 'Artificial Intelligence in Power Station'},
 {'id': 'https://www.bibsonomy.org/bibtex/219d04dda236da5a4e7592a9eb2d4f5eb/mardukasoka',
  'tags': ['simulation', 'ai'],
  'label': 'A framework for Integrating Artificial Intelligence and Simulation',
  'description': 'A framework for Integrating Artificial Intelligence and Simulation | SpringerLink',
  'date': '2017-04-29 16:53:32',
  'changeDate': '2017-04-29 16:53:32',
  'url': 'http://dx.doi.org/10.1007/BF00851350',
  'pub-type': 'article',
  'year': '1994',
  'author': ['Georgios I. Doukidis', 'Marios C. Angelides'],
  'authors': [{'first': 'Georgios I.', 'last': 'Doukidis'},
   {'first': 'Marios C.', 'last': 'Angelides'}],
  'docno': 'https://www.bibsonomy.org/bibtex/219d04dda236da5a4e7592a9eb2d4f5eb/mardukasoka',
  'text': 'A framework for Integrating Artificial Intelligence and Simulation'},
 {'id': 'https://www.bibsonomy.org/bibtex/29f87881e4decfde15a1af630c8ea27d5/ijtsrd',
  'tags': ['Artificial',
   'Intelligence',
   'Markup',
   'Chatbot',
   'Language',
   'Articial',
   'Natural',
   'Processing'],
  'label': 'Artificial Intelligence Based Training and Placement Management',
  'description': '',
  'date': '2019-03-26 12:35:44',
  'changeDate': '2019-03-26 12:35:44',
  'url': 'http://www.ijtsrd.com/computer-science/artificial-intelligence/19180/artificial-intelligence-based-training-and-placement-management/krishanu-deb',
  'pub-type': 'article',
  'year': '2018',
  'author': ['Krishanu Deb | Pankaj Agrawal | Harish Nawale | Shradha Jadhav | Prof. Manisha Darak'],
  'authors': [{'first': 'Krishanu Deb | Pankaj Agrawal | Harish Nawale | Shradha Jadhav | Prof. Manisha',
    'last': 'Darak'}],
  'docno': 'https://www.bibsonomy.org/bibtex/29f87881e4decfde15a1af630c8ea27d5/ijtsrd',
  'text': 'Artificial Intelligence Based Training and Placement Management'},
 {'id': 'https://www.bibsonomy.org/bibtex/263320f0ab96ae778b51b2376aa914f59/ijtsrd',
  'tags': ['Learning,',
   'Systems,',
   'Artificialintelligence',
   'E-Marketing,',
   'Digital',
   'Electronic',
   'Computing,',
   'Machine',
   'Advertising,',
   'Intelligence,',
   'Web',
   'Intelligent',
   'Marketing,',
   'Cognitive',
   'Internet',
   'Advertising',
   'Automated',
   'Online'],
  'label': 'The Significance of Artificial Intelligence in Digital Marketing',
  'description': '',
  'date': '2023-10-14 13:59:49',
  'changeDate': '2023-10-14 13:59:49',
  'url': 'https://www.ijtsrd.com/computer-science/artificial-intelligence/59801/the-significance-of-artificial-intelligence-in-digital-marketing/dr-atul-kumar-mishra',
  'pub-type': 'article',
  'year': '2023',
  'author': ['Dr. Atul Kumar Mishra'],
  'authors': [{'first': 'Dr. Atul Kumar', 'last': 'Mishra'}],
  'docno': 'https://www.bibsonomy.org/bibtex/263320f0ab96ae778b51b2376aa914f59/ijtsrd',
  'text': 'The Significance of Artificial Intelligence in Digital Marketing'},
 {'id': 'https://www.bibsonomy.org/bibtex/26feca839dc10fb815235e9b0f19c2707/ijtsrd',
  'tags': ['Human',
   'Artificialintelligence',
   'Curiosity,',
   'Students,',
   'Instruction,',
   'Growth,',
   'Intelligence,',
   'Technology',
   'Creative',
   'Thinking',
   'Things,',
   'Chat-GPT,',
   'Classroom',
   'Machines,',
   'New',
   'Skills,'],
  'label': 'Impact of Artificial Intelligence and Curiosity among Students to Learn New Things',
  'description': '',
  'date': '2025-01-03 06:49:55',
  'changeDate': '2025-01-03 06:49:55',
  'url': 'https://www.ijtsrd.com/computer-science/artificial-intelligence/70509/impact-of-artificial-intelligence-and-curiosity-among-students-to-learn-new-things/dr-charu-sharma',
  'pub-type': 'article',
  'year': '2024',
  'author': ['Dr. Charu Sharma'],
  'authors': [{'first': 'Dr. Charu', 'last': 'Sharma'}],
  'docno': 'https://www.bibsonomy.org/bibtex/26feca839dc10fb815235e9b0f19c2707/ijtsrd',
  'text': 'Impact of Artificial Intelligence and Curiosity among Students to Learn New Things'},
 {'id': 'https://www.bibsonomy.org/bibtex/28a86ca74e262b9883c8dd4a7c60f1652/ijtsrd',
  'tags': ['(AI),',
   'Behavior,',
   'Intelligent',
   'Artificialintelligence',
   'Intelligence',
   'Computer',
   'Science,',
   'STEM'],
  'label': 'Artificial Intelligence Role in Modern Science Aims, Merits, Risks and Its Applications',
  'description': '',
  'date': '2024-01-05 10:08:27',
  'changeDate': '2024-01-05 10:08:27',
  'url': 'https://www.ijtsrd.com/computer-science/artificial-intelligence/59910/artificial-intelligence-role-in-modern-science-aims-merits-risks-and-its-applications/manish-verma',
  'pub-type': 'article',
  'year': '2023',
  'author': ['Manish Verma'],
  'authors': [{'first': 'Manish', 'last': 'Verma'}],
  'docno': 'https://www.bibsonomy.org/bibtex/28a86ca74e262b9883c8dd4a7c60f1652/ijtsrd',
  'text': 'Artificial Intelligence Role in Modern Science Aims, Merits, Risks and Its Applications'},
 {'id': 'https://www.bibsonomy.org/bibtex/2b31f13f50e07ac7e22de4ea993ba89ee/ijtsrd',
  'tags': ['Human',
   'Intelligence,',
   'Creativity,',
   'Artificialintelligence',
   'of',
   'Art,',
   'Expression',
   'Computational',
   'Freedom',
   'Modern'],
  'label': 'Artificial Intelligence Catalyzes a Revolution for 21st Century Human Creativity and Modern Art',
  'description': '',
  'date': '2022-07-22 08:10:40',
  'changeDate': '2022-07-22 08:10:40',
  'url': 'https://www.ijtsrd.com/computer-science/artificial-intelligence/49150/artificial-intelligence-catalyzes-a-revolution-for-21st-century-human-creativity-and-modern-art/avani-goenka',
  'pub-type': 'article',
  'year': '2022',
  'author': ['Avani Goenka'],
  'authors': [{'first': 'Avani', 'last': 'Goenka'}],
  'docno': 'https://www.bibsonomy.org/bibtex/2b31f13f50e07ac7e22de4ea993ba89ee/ijtsrd',
  'text': 'Artificial Intelligence Catalyzes a Revolution for 21st Century Human Creativity and Modern Art'},
 {'id': 'https://www.bibsonomy.org/bibtex/27ecf6efc8052756e6b1c5084ddcea538/ijtsrd',
  'tags': ['etc', 'Artificial', 'Intelligence', 'machines', 'technology'],
  'label': 'Artificial Intelligence Empowering the Future of Digital Transformation',
  'description': '',
  'date': '2020-06-10 06:39:14',
  'changeDate': '2020-06-10 06:39:14',
  'url': 'https://www.ijtsrd.com/computer-science/artificial-intelligence/30287/artificial-intelligence-empowering-the-future-of-digital-transformation/deepak-kumar',
  'pub-type': 'article',
  'year': '2020',
  'author': ['Deepak Kumar'],
  'authors': [{'first': 'Deepak', 'last': 'Kumar'}],
  'docno': 'https://www.bibsonomy.org/bibtex/27ecf6efc8052756e6b1c5084ddcea538/ijtsrd',
  'text': 'Artificial Intelligence Empowering the Future of Digital Transformation'},
 {'id': 'https://www.bibsonomy.org/bibtex/2c6e8dcc6939a3a8145af0bfcb66613d0/ijtsrd',
  'tags': ['Aayog',
   'Artificialintelligence',
   'Intelligence',
   'MeitY',
   'NITI',
   'Taskforce'],
  'label': 'Analysis and Comparative Study of the Development of Technology with Artificial Intelligence in India',
  'description': '',
  'date': '2020-07-16 11:09:36',
  'changeDate': '2020-07-16 11:09:36',
  'url': 'https://www.ijtsrd.com/computer-science/artificial-intelligence/31249/analysis-and-comparative-study-of-the-development-of-technology-with-artificial-intelligence-in-india/chinmaya-naik',
  'pub-type': 'article',
  'year': '2020',
  'author': ['Chinmaya Naik | Sonali Jain | Jai Sehgal'],
  'authors': [{'first': 'Chinmaya Naik | Sonali Jain | Jai',
    'last': 'Sehgal'}],
  'docno': 'https://www.bibsonomy.org/bibtex/2c6e8dcc6939a3a8145af0bfcb66613d0/ijtsrd',
  'text': 'Analysis and Comparative Study of the Development of Technology with Artificial Intelligence in India'},
 {'id': 'https://www.bibsonomy.org/bibtex/2934ad4d5459670059204a31a0aa7213b/ijtsrd',
  'tags': ['Discriminant',
   'Analysis',
   'SVM,',
   'Opinion',
   'Analysis,',
   'BOW,',
   'K-NN,'],
  'label': 'Opinion Text Analysis Using Artificial Intelligence',
  'description': '',
  'date': '2024-08-08 08:47:08',
  'changeDate': '2024-08-08 08:47:08',
  'url': 'https://www.ijtsrd.com/computer-science/artificial-intelligence/64847/opinion-text-analysis-using-artificial-intelligence/rahul-sagar',
  'pub-type': 'article',
  'year': '2024',
  'author': ['Rahul Sagar | Sumit Dalal | Sumiran'],
  'authors': [{'first': 'Rahul Sagar | Sumit Dalal |', 'last': 'Sumiran'}],
  'docno': 'https://www.bibsonomy.org/bibtex/2934ad4d5459670059204a31a0aa7213b/ijtsrd',
  'text': 'Opinion Text Analysis Using Artificial Intelligence'},
 {'id': 'https://www.bibsonomy.org/bibtex/24feff2b5c07e645c377f8a93c27ae02e/ijtsrd',
  'tags': ['Intelligence,',
   'Artificialintelligence',
   'Pharmaceutical,',
   'Trials,',
   'Challenges',
   'Clinical',
   'Industry,'],
  'label': 'Impact of Artificial Intelligence in the Pharmaceutical World A Review',
  'description': '',
  'date': '2023-07-18 14:31:02',
  'changeDate': '2023-07-18 14:31:02',
  'url': 'https://www.ijtsrd.com.com/computer-science/artificial-intelligence/57564/impact-of-artificial-intelligence-in-the-pharmaceutical-world-a-review/shaikh-sameer-salim',
  'pub-type': 'article',
  'year': '2023',
  'author': ['Shaikh Sameer Salim | Manoj Kumar'],
  'authors': [{'first': 'Shaikh Sameer Salim | Manoj', 'last': 'Kumar'}],
  'docno': 'https://www.bibsonomy.org/bibtex/24feff2b5c07e645c377f8a93c27ae02e/ijtsrd',
  'text': 'Impact of Artificial Intelligence in the Pharmaceutical World A Review'},
 {'id': 'https://www.bibsonomy.org/bibtex/2a5daa928276945e33c2a6ef3ee635e90/ijtsrd',
  'tags': ['gamification',
   'artificial',
   'game',
   'computer',
   'gaming',
   'in',
   'of',
   'AI',
   'games',
   'intelligence'],
  'label': 'Artificial Intelligence in Gaming',
  'description': '',
  'date': '2021-04-13 13:24:36',
  'changeDate': '2021-04-13 13:24:36',
  'url': 'https://www.ijtsrd.com/engineering/electrical-engineering/38516/artificial-intelligence-in-gaming/matthew-n-o-sadiku',
  'pub-type': 'article',
  'year': '2021',
  'author': ['Matthew N. O. Sadiku | Sarhan M. Musa | Abayomi Ajayi-Majebi'],
  'authors': [{'first': 'Matthew N. O. Sadiku | Sarhan M. Musa | Abayomi',
    'last': 'Ajayi-Majebi'}],
  'docno': 'https://www.bibsonomy.org/bibtex/2a5daa928276945e33c2a6ef3ee635e90/ijtsrd',
  'text': 'Artificial Intelligence in Gaming'},
 {'id': 'https://www.bibsonomy.org/bibtex/2ba1d81348174d6afe4b4264f9934767d/ijtsrd',
  'tags': ['intelligence,',
   'marketing,',
   'Artificialintelligence',
   'data',
   'machine',
   'analytics,',
   'learning',
   'digitalization,',
   'big'],
  'label': 'The Transformative Role of Artificial Intelligence Technology for Simulating Human Intelligence Across Various Sectors',
  'description': '',
  'date': '2024-08-09 10:58:41',
  'changeDate': '2024-08-09 10:58:41',
  'url': 'https://www.ijtsrd.com/physics/other/64924/the-transformative-role-of-artificial-intelligence-technology-for-simulating-human-intelligence-across-various-sectors/dr-madhuri-asati',
  'pub-type': 'article',
  'year': '2024',
  'author': ['Dr. Madhuri Asati'],
  'authors': [{'first': 'Dr. Madhuri', 'last': 'Asati'}],
  'docno': 'https://www.bibsonomy.org/bibtex/2ba1d81348174d6afe4b4264f9934767d/ijtsrd',
  'text': 'The Transformative Role of Artificial Intelligence Technology for Simulating Human Intelligence Across Various Sectors'},
 {'id': 'https://www.bibsonomy.org/bibtex/2a812df36a1a60ab7c70a27f78f966e6d/kirk86',
  'tags': ['deep-learning', 'logic'],
  'label': 'Reconciling deep learning with symbolic artificial intelligence: representing objects and relations',
  'description': 'Reconciling deep learning with symbolic artificial intelligence: representing objects and relations - ScienceDirect',
  'date': '2019-07-15 04:36:37',
  'changeDate': '2019-07-15 04:36:37',
  'url': 'http://www.sciencedirect.com/science/article/pii/S2352154618301943',
  'pub-type': 'article',
  'year': '2019',
  'author': ['Marta Garnelo', 'Murray Shanahan'],
  'authors': [{'first': 'Marta', 'last': 'Garnelo'},
   {'first': 'Murray', 'last': 'Shanahan'}],
  'docno': 'https://www.bibsonomy.org/bibtex/2a812df36a1a60ab7c70a27f78f966e6d/kirk86',
  'text': 'Reconciling deep learning with symbolic artificial intelligence: representing objects and relations'},
 {'id': 'https://www.bibsonomy.org/bibtex/210782e0d83c4c2cc7175f6012b3bbbe4/ijtsrd',
  'tags': ['human-computerinteraction', 'artificialintelligence'],
  'label': 'Artificial Intelligence and Human Computer Interaction',
  'description': '',
  'date': '2022-03-01 13:19:32',
  'changeDate': '2022-03-01 13:19:32',
  'url': 'https://www.ijtsrd.com/engineering/computer-engineering/47491/artificial-intelligence-and-humancomputer-interaction/matthew-n-o-sadiku',
  'pub-type': 'article',
  'year': '2021',
  'author': ['Matthew N. O. Sadiku | Uwakwe C. Chukwu | Abayomi Ajayi-Majebi | Sarhan M. Musa'],
  'authors': [{'first': 'Matthew N. O. Sadiku | Uwakwe C. Chukwu | Abayomi Ajayi-Majebi | Sarhan M.',
    'last': 'Musa'}],
  'docno': 'https://www.bibsonomy.org/bibtex/210782e0d83c4c2cc7175f6012b3bbbe4/ijtsrd',
  'text': 'Artificial Intelligence and Human Computer Interaction'},
 {'id': 'https://www.bibsonomy.org/bibtex/20650ad799a08ccda673011c68b0a4cfa/ijtsrd',
  'tags': ['Engineering', 'Computers'],
  'label': 'Artificial Intelligence Basics and Terminology',
  'description': '',
  'date': '2018-11-20 12:31:40',
  'changeDate': '2018-11-20 12:31:40',
  'url': 'http://www.ijtsrd.com/engineering/computer-engineering/18909/artificial-intelligence-basics-and-terminology/durgesh-raghuvanshi',
  'pub-type': 'article',
  'year': '2018',
  'author': ['Durgesh Raghuvanshi'],
  'authors': [{'first': 'Durgesh', 'last': 'Raghuvanshi'}],
  'docno': 'https://www.bibsonomy.org/bibtex/20650ad799a08ccda673011c68b0a4cfa/ijtsrd',
  'text': 'Artificial Intelligence Basics and Terminology'},

In [93]:
index_folder_mult = "./ai_index_mult"

fields=['docno', 'text', 'tags', 'description']

indexer_mult = pt.IterDictIndexer(index_folder_mult, meta={'docno': 200, 'text': 4096}, overwrite=True)
index_ref_mult = indexer_mult.index(ai_dict)

print(f"path to our index: {index_ref_mult.toString()}")

path to our index: ./ai_index_mult/data.properties

In [95]:
index_mult = pt.IndexFactory.of(index_ref_mult)

In [97]:
print(index_mult.getCollectionStatistics().toString())

Number of documents: 1000
Number of terms: 1420
Number of postings: 6189
Number of fields: 1
Number of tokens: 6417
Field names: [text]
Positions:   false

In [99]:
search_engine_mult = pt.terrier.Retriever(index_mult, wmodel="TF_IDF")

In [101]:
res = search_engine_mult.search("intelligence")
res

,qid,docid,docno,rank,score,query
0,1,508,https://www.bibsonomy.org/bibtex/2f7cf941158e2...,0,0.969908,intelligence
1,1,739,https://www.bibsonomy.org/bibtex/21a922cb4af1f...,1,0.969908,intelligence
2,1,738,https://www.bibsonomy.org/bibtex/224ac67b53792...,2,0.955768,intelligence
3,1,604,https://www.bibsonomy.org/bibtex/247f921d7eaa8...,3,0.922362,intelligence
4,1,610,https://www.bibsonomy.org/bibtex/23097df37203d...,4,0.922362,intelligence
...,...,...,...,...,...,...
870,1,133,https://www.bibsonomy.org/bibtex/2c4df47ce17b7...,870,0.372299,intelligence
871,1,231,https://www.bibsonomy.org/bibtex/29fcc0f646278...,871,0.372299,intelligence
872,1,600,https://www.bibsonomy.org/bibtex/21b69569af8d0...,872,0.372299,intelligence
873,1,251,https://www.bibsonomy.org/bibtex/2ba15da18da2c...,873,0.344993,intelligence
874,1,353,https://www.bibsonomy.org/bibtex/24d041e3486cf...,874,0.332790,intelligence

In [103]:
#save our data
pickle.dump(df_ai_filtered, open("ai_index_mult/ai_publications.pkl", "wb"))

In [105]:
#install steamlit
%pip install streamlit

Requirement already satisfied: streamlit in /opt/anaconda3/lib/python3.12/site-packages (1.37.1)
Requirement already satisfied: altair<6,>=4.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (5.0.1)
Requirement already satisfied: blinker<2,>=1.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (1.6.2)
Requirement already satisfied: cachetools<6,>=4.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (5.3.3)
Requirement already satisfied: click<9,>=7.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (8.1.7)
Requirement already satisfied: numpy<3,>=1.20 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (1.26.4)
Requirement already satisfied: packaging<25,>=20 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (24.1)
Requirement already satisfied: pandas<3,>=1.3.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<11,>=7.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (10.4.0)
Requirement already satisfied: protobuf<6,>=3.20 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (4.25.3)
Requirement already satisfied: pyarrow>=7.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (16.1.0)
Requirement already satisfied: requests<3,>=2.27 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (2.32.3)
Requirement already satisfied: rich<14,>=10.14.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (13.7.1)
Requirement already satisfied: tenacity<9,>=8.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (8.2.3)
Requirement already satisfied: toml<2,>=0.10.1 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.3.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (4.11.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (3.1.43)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (0.8.0)
Requirement already satisfied: tornado<7,>=6.0.3 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (6.4.1)
Requirement already satisfied: jinja2 in /opt/anaconda3/lib/python3.12/site-packages (from altair<6,>=4.0->streamlit) (3.1.4)
Requirement already satisfied: jsonschema>=3.0 in /opt/anaconda3/lib/python3.12/site-packages (from altair<6,>=4.0->streamlit) (4.23.0)
Requirement already satisfied: toolz in /opt/anaconda3/lib/python3.12/site-packages (from altair<6,>=4.0->streamlit) (0.12.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /opt/anaconda3/lib/python3.12/site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.7)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.12/site-packages (from pandas<3,>=1.3.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.12/site-packages (from pandas<3,>=1.3.0->streamlit) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.12/site-packages (from pandas<3,>=1.3.0->streamlit) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit) (2024.8.30)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from rich<14,>=10.14.0->streamlit) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/anaconda3/lib/python3.12/site-packages (from rich<14,>=10.14.0->streamlit) (2.15.1)
Requirement already satisfied: smmap<5,>=3.0.1 in /opt/anaconda3/lib/python3.12/site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.12/site-packages (from jinja2->altair<6,>=4.0->streamlit) (2.1.3)
Requirement already satisfied: attrs>=22.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in /opt/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in /opt/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.10.6)
Requirement already satisfied: mdurl~=0.1 in /opt/anaconda3/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit) (0.1.0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.3.0->streamlit) (1.16.0)
Note: you may need to restart the kernel to use updated packages.