# Aufgabe Modul 2

In [251]:
import pandas as pd
import requests
import json

In [253]:
url = "https://www.bibsonomy.org/json/search/database?items=1000&duplicates=merged"
result = requests.get(url) # result ist ein requests.models.Response Objekt
data = result.json() # das Response-Objekt bietet diese nützliche Methode an
df_bib_pd = pd.DataFrame(data["items"])

In [254]:
data1 = json.load(open("data/database.json"))
data2 = json.load(open("data/archive.json"))
df_search1 = pd.DataFrame(data1["items"])
df_search2 = pd.DataFrame(data2["items"])
df = pd.concat([df_search1, df_search2])

In [255]:
df

,type,id,tags,intraHash,label,user,description,date,changeDate,count,...,data,online,dnbtitleid,titleaddon,refnum,in-text-citation,w-type,w-projects,review,oai
0,Bookmark,https://www.bibsonomy.org/url/cc45493bf442b78d...,"[web2.0, database, desktop, aggregator, daily,...",cc45493bf442b78d923b0b1b9342676b,Office 2.0 Database,springnet,Office 2.0 Database,2006-04-19 19:49:42,2008-06-29 17:52:49,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bookmark,https://www.bibsonomy.org/url/61474ed79d5c3f63...,"[tool, database, 3403, Error, Fix,, recovery,,...",61474ed79d5c3f63c1d0b6dcd8c653f5,SQL Database 3403 Error Fix,traktools,SysTools Software releases an effective SQL da...,2009-09-15 19:13:52,2009-09-15 19:13:52,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Bookmark,https://www.bibsonomy.org/url/3cd373dd8ed9c534...,"[Article(s), Design, Database, Information]",3cd373dd8ed9c53483d39eaa928686f6,Database Sharding,panic,"The term ""sharding"" was coined by Google engin...",2011-10-01 02:24:14,2011-10-01 02:27:38,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Bookmark,https://www.bibsonomy.org/url/cc45493bf442b78d...,"[web2.0, 2007, database, socialsoftware, tools...",cc45493bf442b78d923b0b1b9342676b,Office 2.0 Database,akpe,"Overview of roughly 250 Web 2.0 applications, ...",2007-03-14 20:26:50,2011-03-14 16:42:58,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Bookmark,https://www.bibsonomy.org/url/2f5f76391c720a9b...,[databases],2f5f76391c720a9b688f60ec6f900f1d,Encyclopedia of Database Systems,ludaesch,Encyclopedia of Database Systems,2007-02-08 11:20:08,2007-09-26 06:23:20,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,Publication,https://www.bibsonomy.org/bibtex/24d1d395f96e5...,[dblp],4d1d395f96e5085554c516c5666c3ccf,Design Issues for a Digital x-Ray Archive Acce...,dblp,,2024-10-06 00:00:00,2024-10-07 08:49:20,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1996,Publication,https://www.bibsonomy.org/bibtex/2c39dd3220ad9...,[dblp],c39dd3220ad927cf40ddd2f2dc15afe0,"ADSM: A Multi-Platform, Scalable, Backup and A...",dblp,,2023-03-23 00:00:00,2024-04-10 19:39:00,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1997,Publication,https://www.bibsonomy.org/bibtex/2a63bd364207f...,[dblp],a63bd364207fd1d836435d79076b6bb3,An Elite Archive-Assisted Multi-Objective Evol...,dblp,,2024-08-20 00:00:00,2024-08-26 07:26:33,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998,Publication,https://www.bibsonomy.org/bibtex/20e09c3c0700c...,[dblp],0e09c3c0700cff326299926cd28b3298,A Vendor Neutral Archive with MONAI for Automa...,dblp,,2024-08-19 00:00:00,2024-08-26 08:00:23,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999,Publication,https://www.bibsonomy.org/bibtex/2e05a4feee791...,[dblp],e05a4feee7914c86bef22e88acd9cde4,The Image and Data Archive at the Laboratory o...,dblp,,2024-10-06 00:00:00,2024-10-07 07:12:01,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Filtern Sie die Daten so, dass nur noch Einträge des Typs "Publication" enthalten sind.

In [257]:
df = df.loc[df_bib.type == "Publication"]

### - Überlegen Sie, welche Felder Sie möglicherweise umbenennen wollen, und welche Sie nicht benötigen. Benennen Sie entsprechend Spalten um und wählen Sie nur die Spalten, die für Sie sinnvolle Informationen enthalten. Mögliche Änderungen der Daten sind das Umbenennen zu eindeutigeren Bezeichnungen (wie beispielsweise im Pandas Tutorial "label" zu "title"). Filtern Sie ihre Daten jedoch nicht zu drastisch und entfernen Sie nicht zu viele Felder, damit im zweiten Modulteil noch genügend Informationen übrig bleiben.

In [259]:
df.columns

Index(['type', 'id', 'tags', 'intraHash', 'label', 'user', 'description',
       'date', 'changeDate', 'count',
       ...
       'data', 'online', 'dnbtitleid', 'titleaddon', 'refnum',
       'in-text-citation', 'w-type', 'w-projects', 'review', 'oai'],
      dtype='object', length=154)

In [260]:
df_selection = df[["label", "author", "year", "type", "count"]]

In [261]:
df_selection = df_bib_selection.loc[df_bib_selection["author"].isnull() == False]
df_selection = df_bib_selection.loc[df_bib_selection["year"] <= "2025"]
df_selection = df_bib_selection.drop_duplicates(subset = "label", keep ="first")

In [262]:
df_bib_selection["year"].unique()

array([], dtype=object)

In [263]:
df_bib_selection["year_correct"] = df_bib_selection.apply(lambda row: row.year.isdigit(), axis=1)

ValueError: Columns must be same length as key

In [ ]:
df_bib_selection = df_bib_selection.loc[df_bib_selection.year_correct == True]
df_bib_selection

In [233]:
df_bib_selection_no_nan = df_bib_selection

In [235]:
df_bib_selection_no_nan

,label,author,year,type,year_correct
1756,Duplicate detection and record consolidation i...,[SA Cousins],{1998},Publication,False
1916,Caucasian Spiders. A faunistic database on the...,"[Stefan Otto, Sebastian Dietzold]",2006-2012,Publication,False

In [153]:
df_bib_selection_no_nan_rename = df_bib_selection_no_nan.rename(columns={"label": "title", "author": "authors"})

In [155]:
df_bib_selection_no_nan_rename

,title,authors,year,type
1000,EcoliNet: a database of cofunctional gene netw...,"[Hanhae Kim, Jung Eun E. Shim, Junha Shin, Ins...",2015,Publication
1001,The drug-minded protein interaction database (...,"[Meik Kunz, Chunguang Liang, Santosh Nilla, Al...",2016,Publication
1002,PhosphoGRID: a database of experimentally veri...,"[Chris Stark, Ting-Cheng C. Su, Ashton Breitkr...",2010,Publication
1003,GoSynthetic database tool to analyse natural a...,"[C. Liang, B. Kruger, T. Dandekar]",2013,Publication
1004,Database for Mobile Application,[Jasra Nisar Owais Noor Trumboo],2018,Publication
...,...,...,...,...
1995,An Operating System for a Database Machine.,[Chris Nyberg],1986,Publication
1996,A database of thermodynamic properties of the ...,"[Xin Li, Fan Wu, Feng Qi, A Daniel Beard]",2011,Publication
1997,Towards an Integrated Database-Prolog System.,"[Edward Sciore, David Scott Warren]",1984,Publication
1998,MetRxn: a knowledgebase of metabolites and rea...,"[Akhil Kumar, Patrick F. Suthers, Costas D. Ma...",2012,Publication
1999,Hybrid Concurrency Control in Database Systems.,"[Chae-Kyu Kim, Janusz R. Getta]",1996,Publication