# Aufgabe Modul 2

In [34]:
import pandas as pd
import requests

In [58]:
url = "https://www.bibsonomy.org/json/search/database?items=1000&duplicates=merged"
result = requests.get(url) # result ist ein requests.models.Response Objekt
data = result.json() # das Response-Objekt bietet diese nützliche Methode an
df_bib = pd.DataFrame(data["items"])

In [59]:
data.keys()

dict_keys(['types', 'properties', 'items'])

In [60]:
df_bib.columns

Index(['type', 'id', 'tags', 'intraHash', 'label', 'user', 'description',
       'date', 'changeDate', 'count',
       ...
       'subject-category', 'number-of-cited-references', 'journal-iso',
       'unique-id', 'times-cited', 'doc-delivery-number', 'm3', 'ty',
       'bdsk-url-2', 'library'],
      dtype='object', length=132)

In [86]:
df_bib["author"]

0                                                     NaN
1                                                     NaN
2                                                     NaN
3                                                     NaN
4                                                     NaN
                              ...
1995                                       [Chris Nyberg]
1996            [Xin Li, Fan Wu, Feng Qi, A Daniel Beard]
1997                  [Edward Sciore, David Scott Warren]
1998    [Akhil Kumar, Patrick F. Suthers, Costas D. Ma...
1999                          [Lukas Relly, Alan J. Kent]
Name: author, Length: 2000, dtype: object

In [100]:
df_bibsonomy_selection = df_bib[["label", "author", "year", "type"]]

In [102]:
df_bibsonomy_selection

,label,author,year,type
0,Office 2.0 Database,NaN,NaN,Bookmark
1,SQL Database 3403 Error Fix,NaN,NaN,Bookmark
2,Database Sharding,NaN,NaN,Bookmark
3,Office 2.0 Database,NaN,NaN,Bookmark
4,Encyclopedia of Database Systems,NaN,NaN,Bookmark
...,...,...,...,...
1995,An Operating System for a Database Machine.,[Chris Nyberg],1986,Publication
1996,A database of thermodynamic properties of the ...,"[Xin Li, Fan Wu, Feng Qi, A Daniel Beard]",2011,Publication
1997,Towards an Integrated Database-Prolog System.,"[Edward Sciore, David Scott Warren]",1984,Publication
1998,MetRxn: a knowledgebase of metabolites and rea...,"[Akhil Kumar, Patrick F. Suthers, Costas D. Ma...",2012,Publication
1999,Indexing in an Extensible Database System.,"[Lukas Relly, Alan J. Kent]",1993,Publication

### Filtern Sie die Daten so, dass nur noch Einträge des Typs "Publication" enthalten sind.

In [114]:
df_bibsonomy_selection_publication = df_bib.loc[df_bib.type == "Publication"]
df_bibsonomy_selection_publication.head()

,type,id,tags,intraHash,label,user,description,date,changeDate,count,...,subject-category,number-of-cited-references,journal-iso,unique-id,times-cited,doc-delivery-number,m3,ty,bdsk-url-2,library
1000,Publication,https://www.bibsonomy.org/bibtex/2750b8770eec8...,"[ecoli, gene-networks, database]",750b8770eec83ca7d18107df3d520113,EcoliNet: a database of cofunctional gene netw...,karthikraman,,2018-12-02 16:09:07,2018-12-02 16:09:07,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001,Publication,https://www.bibsonomy.org/bibtex/2d93ac9b6cfa6...,"[database, drug-protein-interactions, protein-...",d93ac9b6cfa60505ee7b3d7ffefca15f,The drug-minded protein interaction database (...,karthikraman,,2018-12-02 16:09:07,2018-12-02 16:09:07,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1002,Publication,https://www.bibsonomy.org/bibtex/233d3effaf95a...,"[database, phosphorylation, signalling, yeast]",33d3effaf95a6d714a6fb06099bdf647,PhosphoGRID: a database of experimentally veri...,karthikraman,,2018-12-02 16:09:07,2018-12-02 16:09:07,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1003,Publication,https://www.bibsonomy.org/bibtex/2ca6461cce248...,[test],ca6461cce248858567237c85cca8f378,GoSynthetic database tool to analyse natural a...,evp66rk,,2013-12-11 13:22:35,2013-12-11 13:22:35,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1004,Publication,https://www.bibsonomy.org/bibtex/2eb1605409b13...,"[JSON, XML, Database, documents, NOSQL, SQL]",eb1605409b134cc14adb1c45bc1bd3b0,Database for Mobile Application,ijtsrd,,2018-09-04 08:57:56,2018-10-02 11:01:26,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Überlegen Sie, welche Felder Sie möglicherweise umbenennen wollen, und welche Sie nicht benötigen. Benennen Sie entsprechend Spalten um und wählen Sie nur die Spalten, die für Sie sinnvolle Informationen enthalten. Mögliche Änderungen der Daten sind das Umbenennen zu eindeutigeren Bezeichnungen (wie beispielsweise im Pandas Tutorial "label" zu "title"). Filtern Sie ihre Daten jedoch nicht zu drastisch und entfernen Sie nicht zu viele Felder, damit im zweiten Modulteil noch genügend Informationen übrig bleiben.