In [1]:
import pyterrier as pt
import requests
import pandas as pd
import pickle
import nltk
import numpy as np
import json

In [2]:
url_base = "https://www.bibsonomy.org/json/search/"
url_attr = "?items=1000"

def df_from_query(query):
    url = url_base + query.replace(" ", "%20") + url_attr  
    result = requests.get(url)
    json_data = result.json()
    dataframe = pd.DataFrame(json_data["items"])
    dataframe["query"] = query
    return dataframe

dataframes = []
queries = ["database", "text", "library", "archive"]

for q in queries:
    df = df_from_query(q)
    dataframes.append(df)
    print(f"{len(df)} Ergebnisse für query {q} gefunden.")

data = pd.concat(dataframes, ignore_index=True)

2000 Ergebnisse für query database gefunden.
2000 Ergebnisse für query text gefunden.
2000 Ergebnisse für query library gefunden.
2000 Ergebnisse für query archive gefunden.

In [5]:
data

,type,id,tags,intraHash,label,user,description,date,changeDate,count,...,attachments,categories,url_pdf,data,online,titleaddon,refnum,in-text-citation,w-type,w-projects
0,Bookmark,https://www.bibsonomy.org/url/cc45493bf442b78d...,"[web2.0, database, desktop, aggregator, daily,...",cc45493bf442b78d923b0b1b9342676b,Office 2.0 Database,springnet,Office 2.0 Database,2006-04-19 19:49:42,2008-06-29 17:52:49,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bookmark,https://www.bibsonomy.org/url/61474ed79d5c3f63...,"[tool, database, 3403, Error, Fix,, recovery,,...",61474ed79d5c3f63c1d0b6dcd8c653f5,SQL Database 3403 Error Fix,traktools,SysTools Software releases an effective SQL da...,2009-09-15 19:13:52,2009-09-15 19:13:52,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Bookmark,https://www.bibsonomy.org/url/3cd373dd8ed9c534...,"[Article(s), Design, Database, Information]",3cd373dd8ed9c53483d39eaa928686f6,Database Sharding,panic,"The term ""sharding"" was coined by Google engin...",2011-10-01 02:24:14,2011-10-01 02:27:38,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Bookmark,https://www.bibsonomy.org/url/cc45493bf442b78d...,"[web2.0, 2007, database, socialsoftware, tools...",cc45493bf442b78d923b0b1b9342676b,Office 2.0 Database,akpe,"Overview of roughly 250 Web 2.0 applications, ...",2007-03-14 20:26:50,2011-03-14 16:42:58,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Bookmark,https://www.bibsonomy.org/url/2f5f76391c720a9b...,[databases],2f5f76391c720a9b688f60ec6f900f1d,Encyclopedia of Database Systems,ludaesch,Encyclopedia of Database Systems,2007-02-08 11:20:08,2007-09-26 06:23:20,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,Publication,https://www.bibsonomy.org/bibtex/2040f345d94cd...,[dblp],040f345d94cd5d5e6c4e6a2ca7d2f43e,Faculty self-archiving behavior: Factors affec...,dblp,,2020-06-24 00:00:00,2024-04-10 00:42:34,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7996,Publication,https://www.bibsonomy.org/bibtex/28217f4fe9f6a...,[dblp],8217f4fe9f6a3929c0d365d35447be84,Sensitivity and Access: Unlocking the Colonial...,dblp,,2024-08-08 00:00:00,2024-08-12 07:04:36,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7997,Publication,https://www.bibsonomy.org/bibtex/29994ea45725f...,[dblp],9994ea45725f4b521a1ca2da5f6b1bae,Online hot topic detection from web news archi...,dblp,,2021-09-19 00:00:00,2024-04-10 19:24:49,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7998,Publication,https://www.bibsonomy.org/bibtex/2ee55445bc456...,[dblp],ee55445bc456b80407d888fe2948f6a1,Serge Modular Archive Instrument (SMAI): Bridg...,dblp,,2024-09-16 00:00:00,2024-09-23 07:12:24,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7999,Publication,https://www.bibsonomy.org/bibtex/2dc534ef1b015...,[dblp],dc534ef1b01530bf66755fb1a8eaa51a,The peer-to-peer trace archive: design and com...,dblp,,2024-05-07 00:00:00,2024-05-13 10:00:25,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
#drop columns where at least 50% of the rows have missing values
df_filtered = data.dropna(axis=1, thresh=len(df)*0.5)

In [9]:
df_filtered.columns

Index(['type', 'id', 'tags', 'intraHash', 'label', 'user', 'description',
       'date', 'changeDate', 'count', 'url', 'interHash', 'pub-type',
       'journal', 'year', 'author', 'authors', 'volume', 'abstract',
       'bibtexKey', 'pages', 'publisher', 'number', 'booktitle', 'ee',
       'query'],
      dtype='object')

In [11]:
useful_columns = ['id', 'tags', 'label', 'description', 'date', 'changeDate', 'url', 'pub-type', 'year', 'author', 'authors']
df_filtered = df_filtered[useful_columns]

In [13]:
df_filtered

,id,tags,label,description,date,changeDate,url,pub-type,year,author,authors
0,https://www.bibsonomy.org/url/cc45493bf442b78d...,"[web2.0, database, desktop, aggregator, daily,...",Office 2.0 Database,Office 2.0 Database,2006-04-19 19:49:42,2008-06-29 17:52:49,http://itredux.com/office-20/database/,NaN,NaN,NaN,NaN
1,https://www.bibsonomy.org/url/61474ed79d5c3f63...,"[tool, database, 3403, Error, Fix,, recovery,,...",SQL Database 3403 Error Fix,SysTools Software releases an effective SQL da...,2009-09-15 19:13:52,2009-09-15 19:13:52,http://www.sqlrecoverytool.com/sql-database-34...,NaN,NaN,NaN,NaN
2,https://www.bibsonomy.org/url/3cd373dd8ed9c534...,"[Article(s), Design, Database, Information]",Database Sharding,"The term ""sharding"" was coined by Google engin...",2011-10-01 02:24:14,2011-10-01 02:27:38,http://www.codefutures.com/database-sharding/,NaN,NaN,NaN,NaN
3,https://www.bibsonomy.org/url/cc45493bf442b78d...,"[web2.0, 2007, database, socialsoftware, tools...",Office 2.0 Database,"Overview of roughly 250 Web 2.0 applications, ...",2007-03-14 20:26:50,2011-03-14 16:42:58,http://itredux.com/office-20/database/,NaN,NaN,NaN,NaN
4,https://www.bibsonomy.org/url/2f5f76391c720a9b...,[databases],Encyclopedia of Database Systems,Encyclopedia of Database Systems,2007-02-08 11:20:08,2007-09-26 06:23:20,http://refworks.springer.com/database-systems/,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
7995,https://www.bibsonomy.org/bibtex/2040f345d94cd...,[dblp],Faculty self-archiving behavior: Factors affec...,,2020-06-24 00:00:00,2024-04-10 00:42:34,http://dblp.uni-trier.de/db/conf/asist/asist20...,inproceedings,2007,[Jihyun Kim],"[{'first': 'Jihyun', 'last': 'Kim'}]"
7996,https://www.bibsonomy.org/bibtex/28217f4fe9f6a...,[dblp],Sensitivity and Access: Unlocking the Colonial...,,2024-08-08 00:00:00,2024-08-12 07:04:36,http://dblp.uni-trier.de/db/journals/dhq/dhq18...,article,2024,"[Jonathan Dentler, Lise Jaillant, Daniel Folia...","[{'first': 'Jonathan', 'last': 'Dentler'}, {'f..."
7997,https://www.bibsonomy.org/bibtex/29994ea45725f...,[dblp],Online hot topic detection from web news archi...,,2021-09-19 00:00:00,2024-04-10 19:24:49,http://dblp.uni-trier.de/db/conf/fskd/fskd2014...,inproceedings,2014,"[RuiGuo Yu, Mankun Zhao, Peng Chang, MuWen He]","[{'first': 'RuiGuo', 'last': 'Yu'}, {'first': ..."
7998,https://www.bibsonomy.org/bibtex/2ee55445bc456...,[dblp],Serge Modular Archive Instrument (SMAI): Bridg...,,2024-09-16 00:00:00,2024-09-23 07:12:24,http://dblp.uni-trier.de/db/conf/nime/nime2023...,inproceedings,2023,"[Ted Moore, Jean Brazeau]","[{'first': 'Ted', 'last': 'Moore'}, {'first': ..."
7999,https://www.bibsonomy.org/bibtex/2dc534ef1b015...,[dblp],The peer-to-peer trace archive: design and com...,,2024-05-07 00:00:00,2024-05-13 10:00:25,http://dblp.uni-trier.de/db/conf/conext/sw2010...,inproceedings,2010,"[Boxun Zhang, Alexandru Iosup, Johan Pouwelse,...","[{'first': 'Boxun', 'last': 'Zhang'}, {'first'..."

In [15]:
#pyterrier exspects a docno field
df_filtered['docno'] = df_filtered['id']
df_filtered['text'] = df_filtered['label']

In [17]:
index_folder = "./df_index"

indexer = pt.DFIndexer(index_folder, overwrite=True)
index_ref = indexer.index(df_filtered['text'], df_filtered['docno'])

print(f"path to our index: {index_ref.toString()}")

/var/folders/88/9blsh45918g8y3n5vl6vztxr0000gq/T/ipykernel_3547/146072258.py:3: DeprecationWarning: Call to deprecated class DFIndexer. (use pt.terrier.IterDictIndexer().index(dataframe.to_dict(orient='records')) instead) -- Deprecated since version 0.11.0.
  indexer = pt.DFIndexer(index_folder, overwrite=True)
Java started (triggered by TerrierIndexer.__init__) and loaded: pyterrier.java, pyterrier.terrier.java [version=5.11 (build: craig.macdonald 2025-01-13 21:29), helper_version=0.0.8]

09:14:34.413 [main] WARN org.terrier.structures.indexing.Indexer -- Adding an empty document to the index (https://www.bibsonomy.org/url/45d7bb8eace077fe1f46f404529960f4/iblis) - further warnings are suppressed
09:14:35.454 [main] WARN org.terrier.structures.indexing.Indexer -- Indexed 4 empty documents
path to our index: ./df_index/data.properties

In [19]:
index = pt.IndexFactory.of(index_ref)

In [21]:
print(index.getCollectionStatistics().toString())

Number of documents: 8000
Number of terms: 8481
Number of postings: 46839
Number of fields: 0
Number of tokens: 48611
Field names: []
Positions:   false

In [23]:
for kv in index.getLexicon():
    print(f"{kv.getKey()} -> {kv.getValue().toString()}")

0 -> term1 Nt=94 TF=103 maxTF=3 @{0 0 0}
000 -> term4818 Nt=5 TF=5 maxTF=1 @{0 132 1}
0002 -> term4089 Nt=4 TF=4 maxTF=1 @{0 145 3}
01 -> term5346 Nt=3 TF=3 maxTF=1 @{0 150 1}
017 -> term5389 Nt=1 TF=1 maxTF=1 @{0 158 3}
02 -> term3559 Nt=4 TF=4 maxTF=1 @{0 161 5}
03 -> term3626 Nt=3 TF=3 maxTF=1 @{0 169 7}
0301 -> term3463 Nt=1 TF=1 maxTF=1 @{0 177 1}
04 -> term3599 Nt=3 TF=3 maxTF=1 @{0 180 1}
05 -> term1331 Nt=3 TF=3 maxTF=1 @{0 187 5}
050 -> term2507 Nt=1 TF=1 maxTF=1 @{0 195 3}
06 -> term4354 Nt=3 TF=3 maxTF=1 @{0 198 1}
062 -> term7186 Nt=1 TF=1 maxTF=1 @{0 206 7}
07 -> term3868 Nt=3 TF=3 maxTF=1 @{0 210 1}
08 -> term3969 Nt=3 TF=4 maxTF=2 @{0 217 5}
09 -> term5266 Nt=1 TF=1 maxTF=1 @{0 224 0}
1 -> term767 Nt=48 TF=58 maxTF=4 @{0 227 2}
10 -> term1029 Nt=24 TF=25 maxTF=2 @{0 310 2}
100 -> term3368 Nt=8 TF=8 maxTF=1 @{0 355 1}
101 -> term3875 Nt=1 TF=1 maxTF=1 @{0 374 5}
1039 -> term5958 Nt=1 TF=1 maxTF=1 @{0 377 5}
10g -> term96 Nt=7 TF=7 maxTF=1 @{0 380 7}
11 -> term1275 Nt=11 TF=11 maxTF=1 @{0 393 3}
113 -> term5603 Nt=1 TF=1 maxTF=1 @{0 418 7}
115th -> term4565 Nt=1 TF=1 maxTF=1 @{0 422 1}
116 -> term5369 Nt=1 TF=1 maxTF=1 @{0 425 1}
12 -> term468 Nt=6 TF=6 maxTF=1 @{0 428 3}
120 -> term7135 Nt=1 TF=1 maxTF=1 @{0 443 1}
13 -> term3557 Nt=5 TF=6 maxTF=2 @{0 446 3}
14 -> term1698 Nt=7 TF=7 maxTF=1 @{0 458 4}
140 -> term6192 Nt=1 TF=1 maxTF=1 @{0 475 0}
1450 -> term371 Nt=2 TF=2 maxTF=1 @{0 478 2}
15 -> term1126 Nt=7 TF=7 maxTF=1 @{0 482 6}
150 -> term4460 Nt=1 TF=1 maxTF=1 @{0 497 2}
153 -> term2136 Nt=1 TF=1 maxTF=1 @{0 500 2}
16 -> term1598 Nt=6 TF=7 maxTF=2 @{0 503 0}
160 -> term4044 Nt=1 TF=1 maxTF=1 @{0 516 3}
1644 -> term808 Nt=1 TF=1 maxTF=1 @{0 519 3}
16th -> term2877 Nt=1 TF=1 maxTF=1 @{0 521 5}
17 -> term4353 Nt=3 TF=3 maxTF=1 @{0 524 3}
1740 -> term985 Nt=1 TF=1 maxTF=1 @{0 532 5}
1785 -> term7080 Nt=2 TF=2 maxTF=1 @{0 534 7}
17th -> term1425 Nt=1 TF=1 maxTF=1 @{0 540 1}
18 -> term1449 Nt=4 TF=4 maxTF=1 @{0 542 5}
180 -> term6991 Nt=1 TF=1 maxTF=1 @{0 550 7}
1800 -> term1230 Nt=1 TF=1 maxTF=1 @{0 554 1}
1802 -> term7352 Nt=1 TF=1 maxTF=1 @{0 556 5}
1837 -> term1708 Nt=1 TF=1 maxTF=1 @{0 559 7}
1850 -> term987 Nt=1 TF=1 maxTF=1 @{0 562 3}
1869 -> term7876 Nt=1 TF=1 maxTF=1 @{0 564 5}
1874 -> term6210 Nt=1 TF=1 maxTF=1 @{0 567 7}
1878 -> term8413 Nt=1 TF=1 maxTF=1 @{0 571 1}
1893 -> term7132 Nt=1 TF=1 maxTF=1 @{0 574 3}
1894 -> term7184 Nt=1 TF=1 maxTF=1 @{0 577 5}
1895 -> term6986 Nt=2 TF=2 maxTF=1 @{0 580 7}
1896 -> term6975 Nt=1 TF=1 maxTF=1 @{0 584 5}
1897 -> term6985 Nt=2 TF=2 maxTF=1 @{0 587 7}
1899 -> term6969 Nt=1 TF=1 maxTF=1 @{0 591 3}
19 -> term2164 Nt=8 TF=9 maxTF=2 @{0 594 5}
1900 -> term6984 Nt=2 TF=2 maxTF=1 @{0 612 4}
1901 -> term1707 Nt=1 TF=1 maxTF=1 @{0 616 6}
1902 -> term6971 Nt=1 TF=1 maxTF=1 @{0 619 2}
1904 -> term6974 Nt=1 TF=1 maxTF=1 @{0 622 4}
1907 -> term6973 Nt=1 TF=1 maxTF=1 @{0 625 6}
1909 -> term6972 Nt=1 TF=1 maxTF=1 @{0 629 0}
191 -> term1522 Nt=1 TF=1 maxTF=1 @{0 632 2}
1912 -> term807 Nt=2 TF=2 maxTF=1 @{0 634 6}
1922 -> term6211 Nt=1 TF=1 maxTF=1 @{0 640 2}
1923 -> term7372 Nt=1 TF=1 maxTF=1 @{0 643 4}
1939 -> term8358 Nt=1 TF=1 maxTF=1 @{0 646 6}
194 -> term1276 Nt=1 TF=1 maxTF=1 @{0 650 0}
1941 -> term8410 Nt=1 TF=1 maxTF=1 @{0 652 4}
1945 -> term370 Nt=3 TF=3 maxTF=1 @{0 655 6}
1950 -> term6156 Nt=1 TF=1 maxTF=1 @{0 663 4}
1956 -> term7166 Nt=1 TF=1 maxTF=1 @{0 666 6}
1957 -> term5955 Nt=1 TF=1 maxTF=1 @{0 670 0}
1959 -> term6263 Nt=2 TF=2 maxTF=1 @{0 673 2}
1960 -> term8401 Nt=1 TF=1 maxTF=1 @{0 678 4}
1960er -> term8094 Nt=1 TF=1 maxTF=1 @{0 681 6}
1965 -> term6863 Nt=1 TF=1 maxTF=1 @{0 685 0}
1967 -> term6670 Nt=1 TF=1 maxTF=1 @{0 688 2}
1970 -> term6147 Nt=2 TF=2 maxTF=1 @{0 691 4}
1974 -> term1630 Nt=1 TF=1 maxTF=1 @{0 697 0}
1976 -> term6188 Nt=1 TF=1 maxTF=1 @{0 699 4}
1980er -> term8097 Nt=1 TF=1 maxTF=1 @{0 702 6}
1981 -> term1553 Nt=1 TF=1 maxTF=1 @{0 706 0}
1983 -> term1050 Nt=2 TF=2 maxTF=1 @{0 708 4}
1984 -> term6265 Nt=1 TF=1 maxTF=1 @{0 712 6}
1985 -> term7081 Nt=2 TF=2 maxTF=1 @{0 716 0}
1986 -> term7848 Nt=2 TF=2 maxTF=1 @{0 721 2}
1990 -> term6148 Nt=1 TF=1 maxTF=1 @{0 727 0}
1992 -> term3056 Nt=1 TF=2 maxTF=2 @{0 730 2}
1994 -> term4670 Nt=1 TF=1 maxTF=1 @{0 733 1}
1996 -> term7329 Nt=2 TF=2 maxTF=1 @{0 736 1}
1997 -> term109 Nt=2 TF=2 maxTF=1 @{0 740 5}
1998 -> term2937 Nt=1 TF=1 maxTF=1 @{0 744 7}
1999 -> term6305 Nt=1 TF=1 maxTF=1 @{0 747 5}
1d -> term6518 Nt=1 TF=1 maxTF=1 @{0 750 7}
1st -> term2940 Nt=2 TF=2 maxTF=1 @{0 754 1}
2 -> term0 Nt=104 TF=113 maxTF=2 @{0 759 7}
20 -> term50 Nt=9 TF=9 maxTF=1 @{0 907 4}
200 -> term3409 Nt=1 TF=1 maxTF=1 @{0 927 4}
2000 -> term675 Nt=10 TF=10 maxTF=1 @{0 930 4}
2001 -> term1450 Nt=3 TF=4 maxTF=2 @{0 954 4}
2002 -> term2796 Nt=1 TF=1 maxTF=1 @{0 962 7}
2003 -> term2915 Nt=3 TF=3 maxTF=1 @{0 965 5}
2004 -> term1908 Nt=3 TF=3 maxTF=1 @{0 974 1}
2005 -> term276 Nt=8 TF=8 maxTF=1 @{0 981 7}
2006 -> term1332 Nt=8 TF=8 maxTF=1 @{0 1000 7}
2007 -> term3290 Nt=7 TF=7 maxTF=1 @{0 1018 7}
2008 -> term1110 Nt=9 TF=9 maxTF=1 @{0 1033 7}
2009 -> term1861 Nt=10 TF=10 maxTF=1 @{0 1052 7}
2010 -> term3602 Nt=6 TF=6 maxTF=1 @{0 1075 7}
2011 -> term2206 Nt=10 TF=10 maxTF=1 @{0 1089 7}
2012 -> term3993 Nt=7 TF=7 maxTF=1 @{0 1112 5}
2013 -> term1266 Nt=6 TF=6 maxTF=1 @{0 1129 5}
2014 -> term6352 Nt=2 TF=2 maxTF=1 @{0 1145 3}
2015 -> term2539 Nt=12 TF=12 maxTF=1 @{0 1150 5}
2016 -> term3088 Nt=11 TF=11 maxTF=1 @{0 1174 7}
2017 -> term1244 Nt=11 TF=13 maxTF=2 @{0 1197 3}
2018 -> term1127 Nt=10 TF=10 maxTF=1 @{0 1223 1}
2019 -> term3558 Nt=13 TF=14 maxTF=2 @{0 1245 3}
2020 -> term3601 Nt=3 TF=3 maxTF=1 @{0 1268 6}
2021 -> term1308 Nt=7 TF=7 maxTF=1 @{0 1277 6}
2022 -> term484 Nt=5 TF=5 maxTF=1 @{0 1295 0}
2025 -> term3600 Nt=1 TF=1 maxTF=1 @{0 1306 4}
2030 -> term6225 Nt=9 TF=9 maxTF=1 @{0 1309 4}
21 -> term4117 Nt=4 TF=4 maxTF=1 @{0 1322 4}
21c -> term175 Nt=1 TF=1 maxTF=1 @{0 1332 2}
21st -> term3023 Nt=10 TF=10 maxTF=1 @{0 1333 6}
22 -> term1549 Nt=6 TF=6 maxTF=1 @{0 1355 2}
2200 -> term7394 Nt=1 TF=1 maxTF=1 @{0 1370 2}
23 -> term4024 Nt=3 TF=3 maxTF=1 @{0 1373 4}
231 -> term2936 Nt=1 TF=1 maxTF=1 @{0 1382 0}
2324 -> term3327 Nt=1 TF=1 maxTF=1 @{0 1384 6}
24 -> term1548 Nt=6 TF=6 maxTF=1 @{0 1387 6}
240 -> term3913 Nt=1 TF=1 maxTF=1 @{0 1402 6}
249 -> term1004 Nt=1 TF=1 maxTF=1 @{0 1405 6}
25 -> term3922 Nt=3 TF=3 maxTF=1 @{0 1408 0}
256 -> term4924 Nt=1 TF=1 maxTF=1 @{0 1416 6}
25th -> term2538 Nt=2 TF=2 maxTF=1 @{0 1419 6}
26 -> term3054 Nt=1 TF=1 maxTF=1 @{0 1422 6}
26th -> term7579 Nt=1 TF=1 maxTF=1 @{0 1425 4}
2756 -> term3743 Nt=1 TF=1 maxTF=1 @{0 1428 6}
27th -> term5379 Nt=1 TF=1 maxTF=1 @{0 1431 6}
28 -> term3053 Nt=5 TF=5 maxTF=1 @{0 1435 0}
29 -> term6258 Nt=1 TF=1 maxTF=1 @{0 1447 2}
2bibliometr -> term6054 Nt=1 TF=1 maxTF=1 @{0 1450 4}
2d -> term3050 Nt=3 TF=3 maxTF=1 @{0 1453 6}
2nd -> term2479 Nt=2 TF=2 maxTF=1 @{0 1462 0}
3 -> term285 Nt=28 TF=29 maxTF=2 @{0 1467 6}
30 -> term6913 Nt=2 TF=2 maxTF=1 @{0 1518 3}
3013 -> term1601 Nt=1 TF=1 maxTF=1 @{0 1524 3}
3150 -> term665 Nt=1 TF=1 maxTF=1 @{0 1526 7}
3159 -> term1602 Nt=1 TF=1 maxTF=1 @{0 1529 1}
31c3 -> term3827 Nt=1 TF=1 maxTF=1 @{0 1531 5}
33 -> term6866 Nt=1 TF=1 maxTF=1 @{0 1534 5}
3403 -> term5 Nt=1 TF=1 maxTF=1 @{0 1537 7}
35mm -> term7598 Nt=1 TF=1 maxTF=1 @{0 1538 3}
36 -> term1108 Nt=1 TF=1 maxTF=1 @{0 1541 5}
37 -> term3263 Nt=1 TF=1 maxTF=1 @{0 1544 1}
3cdb -> term3071 Nt=1 TF=1 maxTF=1 @{0 1546 7}
3d -> term2535 Nt=20 TF=20 maxTF=1 @{0 1549 5}
3dmol -> term5519 Nt=1 TF=1 maxTF=1 @{0 1589 1}
3m -> term5178 Nt=1 TF=1 maxTF=1 @{0 1592 3}
3rd -> term297 Nt=2 TF=2 maxTF=1 @{0 1595 3}
4 -> term1067 Nt=19 TF=19 maxTF=1 @{0 1600 3}
40 -> term4240 Nt=3 TF=3 maxTF=1 @{0 1639 1}
41 -> term5822 Nt=1 TF=1 maxTF=1 @{0 1647 7}
42 -> term304 Nt=1 TF=1 maxTF=1 @{0 1651 1}
43 -> term3305 Nt=2 TF=2 maxTF=1 @{0 1652 7}
445 -> term1325 Nt=1 TF=1 maxTF=1 @{0 1658 1}
451 -> term38 Nt=2 TF=2 maxTF=1 @{0 1660 5}
456 -> term7435 Nt=1 TF=1 maxTF=1 @{0 1663 1}
4586 -> term4564 Nt=1 TF=1 maxTF=1 @{0 1666 3}
478 -> term6868 Nt=1 TF=1 maxTF=1 @{0 1669 3}
484 -> term6867 Nt=1 TF=1 maxTF=1 @{0 1672 5}
4store -> term1352 Nt=2 TF=2 maxTF=1 @{0 1675 7}
4th -> term2906 Nt=2 TF=2 maxTF=1 @{0 1679 1}
5 -> term471 Nt=18 TF=18 maxTF=1 @{0 1684 3}
50 -> term3287 Nt=6 TF=6 maxTF=1 @{0 1719 5}
500 -> term5365 Nt=2 TF=2 maxTF=1 @{0 1733 7}
5806 -> term19 Nt=1 TF=1 maxTF=1 @{0 1739 5}
594 -> term5536 Nt=1 TF=1 maxTF=1 @{0 1740 5}
5th -> term2148 Nt=3 TF=3 maxTF=1 @{0 1743 7}
6 -> term278 Nt=7 TF=7 maxTF=1 @{0 1751 1}
64 -> term176 Nt=1 TF=1 maxTF=1 @{0 1768 7}
645 -> term1326 Nt=1 TF=1 maxTF=1 @{0 1770 3}
6581 -> term7209 Nt=1 TF=1 maxTF=1 @{0 1772 7}
69 -> term3215 Nt=2 TF=2 maxTF=1 @{0 1776 1}
6beta2 -> term879 Nt=1 TF=1 maxTF=1 @{0 1780 5}
7 -> term110 Nt=14 TF=14 maxTF=1 @{0 1782 7}
70 -> term5699 Nt=1 TF=1 maxTF=1 @{0 1810 5}
70th -> term5701 Nt=1 TF=1 maxTF=1 @{0 1813 7}
71 -> term6672 Nt=1 TF=1 maxTF=1 @{0 1817 1}
721 -> term1128 Nt=1 TF=1 maxTF=1 @{0 1820 3}
74 -> term1283 Nt=1 TF=1 maxTF=1 @{0 1822 7}
760 -> term1193 Nt=1 TF=1 maxTF=1 @{0 1825 3}
76th -> term6553 Nt=1 TF=1 maxTF=1 @{0 1827 7}
7th -> term1453 Nt=1 TF=1 maxTF=1 @{0 1831 1}
8 -> term470 Nt=13 TF=13 maxTF=1 @{0 1833 5}
80 -> term3222 Nt=2 TF=2 maxTF=1 @{0 1862 5}
8080 -> term7470 Nt=1 TF=1 maxTF=1 @{0 1867 1}
82nd -> term6281 Nt=1 TF=1 maxTF=1 @{0 1870 3}
830 -> term279 Nt=1 TF=1 maxTF=1 @{0 1873 5}
8580 -> term7212 Nt=1 TF=1 maxTF=1 @{0 1875 3}
891 -> term5533 Nt=1 TF=1 maxTF=1 @{0 1878 5}
8th -> term1852 Nt=2 TF=2 maxTF=1 @{0 1881 7}
9 -> term1183 Nt=9 TF=9 maxTF=1 @{0 1887 7}
920 -> term3433 Nt=2 TF=2 maxTF=1 @{0 1907 7}
939 -> term5534 Nt=1 TF=1 maxTF=1 @{0 1912 3}
96 -> term7413 Nt=1 TF=1 maxTF=1 @{0 1915 5}
966 -> term1189 Nt=1 TF=1 maxTF=1 @{0 1918 7}
a3 -> term4803 Nt=1 TF=1 maxTF=1 @{0 1921 3}
a4 -> term6908 Nt=1 TF=1 maxTF=1 @{0 1924 3}
aa2 -> term6404 Nt=1 TF=1 maxTF=1 @{0 1927 5}
aaai -> term7807 Nt=1 TF=1 maxTF=1 @{0 1930 7}
aac -> term4113 Nt=1 TF=1 maxTF=1 @{0 1934 1}
aadhaar -> term1059 Nt=3 TF=3 maxTF=1 @{0 1937 1}
aagingbas -> term1924 Nt=1 TF=1 maxTF=1 @{0 1943 7}
aapl -> term5392 Nt=1 TF=1 maxTF=1 @{0 1946 5}
aaron -> term5552 Nt=2 TF=2 maxTF=1 @{0 1949 7}
aatss -> term4642 Nt=1 TF=1 maxTF=1 @{0 1954 3}
aaup -> term7182 Nt=1 TF=1 maxTF=1 @{0 1957 3}
ab -> term1208 Nt=3 TF=3 maxTF=1 @{0 1960 5}
ab52 -> term6406 Nt=1 TF=1 maxTF=1 @{0 1966 3}
abampdb -> term1935 Nt=1 TF=1 maxTF=1 @{0 1969 5}
abandon -> term5213 Nt=1 TF=1 maxTF=1 @{0 1972 3}
abandonwar -> term719 Nt=1 TF=2 maxTF=2 @{0 1975 3}
abbrevi -> term2521 Nt=1 TF=1 maxTF=1 @{0 1977 6}
abcdef -> term8165 Nt=1 TF=1 maxTF=1 @{0 1980 4}
abella -> term8210 Nt=1 TF=1 maxTF=1 @{0 1983 6}
abiot -> term2618 Nt=1 TF=1 maxTF=1 @{0 1987 0}
abou -> term7324 Nt=1 TF=1 maxTF=1 @{0 1989 6}
absatzsetz -> term3456 Nt=1 TF=1 maxTF=1 @{0 1993 0}
abschi -> term4989 Nt=1 TF=1 maxTF=1 @{0 1996 0}
abschluss -> term7971 Nt=1 TF=1 maxTF=1 @{0 1999 0}
absolut -> term7206 Nt=1 TF=1 maxTF=1 @{0 2002 2}
absorpt -> term7750 Nt=1 TF=1 maxTF=1 @{0 2005 4}
abstract -> term150 Nt=27 TF=27 maxTF=1 @{0 2008 6}
abu -> term5990 Nt=1 TF=1 maxTF=1 @{0 2058 6}
ac -> term5238 Nt=4 TF=4 maxTF=1 @{0 2062 0}
academ -> term493 Nt=72 TF=74 maxTF=3 @{0 2072 4}
academi -> term1273 Nt=5 TF=5 maxTF=1 @{0 2164 4}
academician -> term7914 Nt=1 TF=1 maxTF=1 @{0 2175 4}
acadtag -> term4521 Nt=1 TF=1 maxTF=1 @{0 2178 6}
acc -> term6690 Nt=7 TF=7 maxTF=1 @{0 2181 6}
acceler -> term2039 Nt=5 TF=5 maxTF=1 @{0 2193 2}
accent -> term8400 Nt=1 TF=1 maxTF=1 @{0 2205 0}
accept -> term3734 Nt=1 TF=1 maxTF=1 @{0 2208 2}
access -> term215 Nt=105 TF=106 maxTF=2 @{0 2211 2}
accessdeni -> term473 Nt=1 TF=1 maxTF=1 @{0 2357 7}
accid -> term1274 Nt=2 TF=2 maxTF=1 @{0 2359 7}
accident -> term5325 Nt=2 TF=2 maxTF=1 @{0 2364 7}
accord -> term6501 Nt=2 TF=2 maxTF=1 @{0 2370 5}
account -> term2706 Nt=2 TF=2 maxTF=1 @{0 2376 1}
accueil -> term6940 Nt=6 TF=6 maxTF=1 @{0 2381 7}
accur -> term5120 Nt=2 TF=2 maxTF=1 @{0 2393 1}
accuraci -> term3178 Nt=3 TF=3 maxTF=1 @{0 2398 3}
acetobas -> term3152 Nt=1 TF=1 maxTF=1 @{0 2406 5}
achiev -> term6392 Nt=3 TF=3 maxTF=1 @{0 2409 3}
acid -> term236 Nt=7 TF=7 maxTF=1 @{0 2417 5}
acinetobact -> term1938 Nt=2 TF=2 maxTF=1 @{0 2433 3}
acinetobas -> term1962 Nt=1 TF=1 maxTF=1 @{0 2437 1}
acl -> term7397 Nt=1 TF=1 maxTF=1 @{0 2439 7}
acm -> term1035 Nt=5 TF=5 maxTF=1 @{0 2443 1}
acoust -> term1965 Nt=4 TF=6 maxTF=2 @{0 2452 5}
acousticpow -> term7314 Nt=2 TF=2 maxTF=1 @{0 2461 5}
acquir -> term4905 Nt=5 TF=5 maxTF=1 @{0 2465 1}
acquisit -> term4068 Nt=9 TF=9 maxTF=1 @{0 2472 3}
acronym -> term1224 Nt=2 TF=3 maxTF=2 @{0 2492 1}
across -> term437 Nt=7 TF=7 maxTF=1 @{0 2498 0}
act -> term931 Nt=9 TF=9 maxTF=1 @{0 2511 2}
acta -> term4208 Nt=3 TF=3 maxTF=1 @{0 2531 0}
action -> term653 Nt=17 TF=18 maxTF=2 @{0 2538 4}
actionscript -> term5226 Nt=1 TF=1 maxTF=1 @{0 2570 3}
activ -> term1079 Nt=27 TF=28 maxTF=2 @{0 2573 3}
activecouch -> term5304 Nt=1 TF=1 maxTF=1 @{0 2622 2}
activemigr -> term1680 Nt=1 TF=1 maxTF=1 @{0 2625 4}
activerecord -> term5305 Nt=1 TF=1 maxTF=1 @{0 2628 0}
activeresourc -> term5306 Nt=1 TF=1 maxTF=1 @{0 2631 2}
activest -> term4326 Nt=1 TF=1 maxTF=1 @{0 2634 4}
actual -> term5639 Nt=1 TF=1 maxTF=1 @{0 2637 4}
acubert -> term2825 Nt=1 TF=1 maxTF=1 @{0 2640 6}
acupunctur -> term2827 Nt=1 TF=1 maxTF=1 @{0 2643 4}
acut -> term5820 Nt=1 TF=1 maxTF=1 @{0 2646 2}
ad -> term1721 Nt=11 TF=12 maxTF=2 @{0 2649 4}
ada -> term7344 Nt=2 TF=2 maxTF=1 @{0 2673 1}
adam -> term2522 Nt=2 TF=2 maxTF=1 @{0 2679 1}
adapt -> term2271 Nt=21 TF=21 maxTF=1 @{0 2685 1}
adarch -> term7290 Nt=1 TF=1 maxTF=1 @{0 2725 7}
adat -> term494 Nt=2 TF=2 maxTF=1 @{0 2729 1}
add -> term974 Nt=10 TF=10 maxTF=1 @{0 2733 3}
addgen -> term616 Nt=1 TF=1 maxTF=1 @{0 2752 1}
addit -> term3698 Nt=2 TF=2 maxTF=1 @{0 2754 3}
addon -> term685 Nt=1 TF=1 maxTF=1 @{0 2760 1}
address -> term900 Nt=9 TF=9 maxTF=1 @{0 2762 3}
addresse -> term5003 Nt=1 TF=1 maxTF=1 @{0 2783 5}
adhyayana -> term4771 Nt=1 TF=1 maxTF=1 @{0 2786 5}
aditi -> term2977 Nt=1 TF=1 maxTF=1 @{0 2789 5}
adjust -> term4330 Nt=1 TF=1 maxTF=1 @{0 2792 3}
admin -> term1412 Nt=1 TF=1 maxTF=1 @{0 2795 3}
administr -> term2322 Nt=7 TF=7 maxTF=1 @{0 2797 7}
ado -> term185 Nt=3 TF=3 maxTF=1 @{0 2815 1}
adob -> term3253 Nt=5 TF=5 maxTF=1 @{0 2822 1}
adodb -> term1458 Nt=2 TF=2 maxTF=1 @{0 2833 5}
adolesc -> term4635 Nt=1 TF=1 maxTF=1 @{0 2837 3}
adopt -> term1998 Nt=4 TF=4 maxTF=1 @{0 2840 3}
adsens -> term4189 Nt=1 TF=1 maxTF=1 @{0 2851 3}
adult -> term5607 Nt=1 TF=1 maxTF=1 @{0 2854 3}
advanc -> term492 Nt=28 TF=29 maxTF=2 @{0 2857 5}
advantag -> term5589 Nt=2 TF=2 maxTF=1 @{0 2909 2}
adventur -> term590 Nt=10 TF=11 maxTF=2 @{0 2915 0}
adverlicio -> term7511 Nt=1 TF=1 maxTF=1 @{0 2935 1}
advers -> term2835 Nt=1 TF=1 maxTF=1 @{0 2938 3}
adversari -> term4620 Nt=5 TF=5 maxTF=1 @{0 2941 1}
advertis -> term1344 Nt=8 TF=10 maxTF=2 @{0 2950 7}
advic -> term6123 Nt=1 TF=1 maxTF=1 @{0 2970 1}
advisori -> term6097 Nt=3 TF=3 maxTF=1 @{0 2973 3}
advocaci -> term5663 Nt=2 TF=2 maxTF=1 @{0 2981 1}
adwar -> term711 Nt=1 TF=1 maxTF=1 @{0 2986 7}
adzic -> term200 Nt=1 TF=1 maxTF=1 @{0 2989 1}
aeneid -> term4063 Nt=1 TF=1 maxTF=1 @{0 2990 7}
aeria -> term7100 Nt=1 TF=1 maxTF=1 @{0 2993 7}
aerial -> term2889 Nt=1 TF=1 maxTF=1 @{0 2997 1}
aerob -> term1391 Nt=2 TF=2 maxTF=1 @{0 2999 7}
aesthet -> term6399 Nt=1 TF=1 maxTF=1 @{0 3005 1}
affair -> term3473 Nt=1 TF=1 maxTF=1 @{0 3008 3}
affect -> term3018 Nt=4 TF=4 maxTF=1 @{0 3011 3}
affili -> term6642 Nt=1 TF=1 maxTF=1 @{0 3022 5}
afford -> term4075 Nt=2 TF=2 maxTF=1 @{0 3025 7}
affymetrix -> term2327 Nt=1 TF=1 maxTF=1 @{0 3031 7}
afghan -> term8067 Nt=1 TF=1 maxTF=1 @{0 3034 5}
africa -> term6429 Nt=3 TF=3 maxTF=1 @{0 3037 7}
africabib -> term1633 Nt=1 TF=1 maxTF=1 @{0 3045 3}
african -> term2644 Nt=4 TF=4 maxTF=1 @{0 3047 7}
africana -> term1632 Nt=1 TF=1 maxTF=1 @{0 3058 5}
aftm -> term2084 Nt=1 TF=1 maxTF=1 @{0 3061 1}
ag -> term327 Nt=14 TF=15 maxTF=2 @{0 3063 7}
agata -> term6548 Nt=1 TF=1 maxTF=1 @{0 3093 6}
agbas -> term3136 Nt=1 TF=1 maxTF=1 @{0 3097 0}
agbay -> term6829 Nt=1 TF=1 maxTF=1 @{0 3099 6}
agbiodata -> term2426 Nt=1 TF=1 maxTF=1 @{0 3103 0}
agd -> term2457 Nt=1 TF=1 maxTF=1 @{0 3105 6}
ageid -> term2573 Nt=1 TF=1 maxTF=1 @{0 3108 4}
agenc -> term1409 Nt=3 TF=3 maxTF=1 @{0 3111 2}
agend -> term6763 Nt=1 TF=1 maxTF=1 @{0 3117 6}
agenda -> term4981 Nt=5 TF=5 maxTF=1 @{0 3121 0}
agendi -> term6882 Nt=1 TF=1 maxTF=1 @{0 3131 6}
agent -> term3082 Nt=6 TF=6 maxTF=1 @{0 3135 0}
ager -> term6485 Nt=1 TF=1 maxTF=1 @{0 3150 4}
aggreg -> term2681 Nt=17 TF=17 maxTF=1 @{0 3153 6}
agid -> term914 Nt=1 TF=1 maxTF=1 @{0 3181 4}
agil -> term1133 Nt=3 TF=3 maxTF=1 @{0 3183 6}
agiledata -> term1423 Nt=1 TF=1 maxTF=1 @{0 3189 6}
agimatec -> term1714 Nt=1 TF=1 maxTF=1 @{0 3192 2}
agnost -> term5610 Nt=2 TF=2 maxTF=1 @{0 3194 6}
agodb -> term1959 Nt=1 TF=1 maxTF=1 @{0 3199 6}
agonist -> term6082 Nt=1 TF=1 maxTF=1 @{0 3202 4}
agre -> term5830 Nt=1 TF=1 maxTF=1 @{0 3205 6}
agreement -> term6313 Nt=1 TF=1 maxTF=1 @{0 3209 0}
agricultur -> term2030 Nt=6 TF=6 maxTF=1 @{0 3212 2}
agronomi -> term7046 Nt=1 TF=1 maxTF=1 @{0 3227 0}
agronomiqu -> term7500 Nt=1 TF=1 maxTF=1 @{0 3230 2}
agrosi -> term2595 Nt=1 TF=1 maxTF=1 @{0 3233 4}
agsl -> term6976 Nt=1 TF=1 maxTF=1 @{0 3236 2}
ahead -> term4397 Nt=2 TF=2 maxTF=1 @{0 3239 4}
ahmadelsagh -> term5201 Nt=1 TF=1 maxTF=1 @{0 3245 2}
ahp -> term2056 Nt=2 TF=2 maxTF=1 @{0 3248 2}
ai -> term3873 Nt=17 TF=17 maxTF=1 @{0 3254 2}
aib -> term5250 Nt=1 TF=1 maxTF=1 @{0 3281 6}
aid -> term2867 Nt=5 TF=5 maxTF=1 @{0 3285 0}
aim -> term584 Nt=2 TF=2 maxTF=1 @{0 3298 2}
aimedgraph -> term2730 Nt=1 TF=1 maxTF=1 @{0 3303 4}
aipac -> term3995 Nt=1 TF=1 maxTF=1 @{0 3306 2}
air -> term5212 Nt=3 TF=3 maxTF=1 @{0 3309 2}
airborn -> term8334 Nt=1 TF=1 maxTF=1 @{0 3317 2}
aircraft -> term1734 Nt=2 TF=3 maxTF=2 @{0 3320 4}
airlin -> term1735 Nt=1 TF=1 maxTF=1 @{0 3326 3}
airplan -> term1733 Nt=1 TF=1 maxTF=1 @{0 3328 7}
airtabl -> term1692 Nt=1 TF=1 maxTF=1 @{0 3331 3}
aisel -> term5720 Nt=1 TF=1 maxTF=1 @{0 3333 7}
ajax -> term3888 Nt=3 TF=3 maxTF=1 @{0 3337 1}
akwukwo -> term6816 Nt=1 TF=1 maxTF=1 @{0 3346 1}
al -> term2227 Nt=6 TF=8 maxTF=2 @{0 3349 3}
al1 -> term7465 Nt=1 TF=1 maxTF=1 @{0 3364 1}
ala -> term5375 Nt=10 TF=10 maxTF=1 @{0 3367 3}
alabama -> term7154 Nt=1 TF=1 maxTF=1 @{0 3389 1}
alamo -> term3006 Nt=1 TF=1 maxTF=1 @{0 3392 3}
alberta -> term3745 Nt=1 TF=1 maxTF=1 @{0 3395 1}
alberto -> term3265 Nt=1 TF=1 maxTF=1 @{0 3398 1}
albrighton -> term5281 Nt=1 TF=2 maxTF=2 @{0 3400 7}
album -> term703 Nt=2 TF=2 maxTF=1 @{0 3404 2}
alch -> term1186 Nt=1 TF=1 maxTF=1 @{0 3409 0}
alec -> term3825 Nt=1 TF=1 maxTF=1 @{0 3411 4}
alert -> term642 Nt=5 TF=5 maxTF=1 @{0 3414 4}
alexand -> term5757 Nt=1 TF=1 maxTF=1 @{0 3426 4}
alexandria -> term5805 Nt=5 TF=5 maxTF=1 @{0 3429 6}
alexandrian -> term6682 Nt=1 TF=1 maxTF=1 @{0 3441 6}
alexandrina -> term7830 Nt=1 TF=1 maxTF=1 @{0 3445 0}
alexandrinu -> term8278 Nt=1 TF=1 maxTF=1 @{0 3448 2}
alfresco -> term534 Nt=1 TF=1 maxTF=1 @{0 3451 4}
alfrescowiki -> term535 Nt=1 TF=1 maxTF=1 @{0 3453 4}
algal -> term2989 Nt=1 TF=1 maxTF=1 @{0 3455 4}
algebra -> term2971 Nt=2 TF=2 maxTF=1 @{0 3458 2}
algorithm -> term1557 Nt=87 TF=88 maxTF=2 @{0 3464 0}
algorithmen -> term4583 Nt=3 TF=3 maxTF=1 @{0 3572 3}
algoritm -> term8459 Nt=1 TF=1 maxTF=1 @{0 3579 3}
alias -> term3794 Nt=1 TF=1 maxTF=1 @{0 3582 5}
alic -> term6297 Nt=1 TF=1 maxTF=1 @{0 3585 5}
align -> term1996 Nt=16 TF=16 maxTF=1 @{0 3588 7}
alisonbabeu -> term3700 Nt=1 TF=1 maxTF=1 @{0 3620 1}
all -> term6760 Nt=1 TF=1 maxTF=1 @{0 3623 1}
alla -> term6711 Nt=2 TF=2 maxTF=1 @{0 3626 3}
allama -> term6650 Nt=1 TF=1 maxTF=1 @{0 3632 3}
allan -> term5697 Nt=2 TF=2 maxTF=1 @{0 3635 5}
allegro -> term5512 Nt=1 TF=1 maxTF=1 @{0 3640 3}
allgemein -> term8322 Nt=2 TF=2 maxTF=1 @{0 3643 5}
allianc -> term5296 Nt=2 TF=2 maxTF=1 @{0 3648 3}
alloc -> term6740 Nt=1 TF=1 maxTF=1 @{0 3654 5}

In [25]:
term_freq_dict = {}

for kv in index.getLexicon():
    term_freq_dict[kv.getKey()] = kv.getValue().frequency

In [27]:
term_freq_dict_sorted = sorted(term_freq_dict.items(), key=lambda x: x[1], reverse=True)

In [29]:
top_k = 30
term_freq_dict_sorted[:top_k]

[('librari', 2267),
 ('text', 2092),
 ('archiv', 1875),
 ('databas', 1837),
 ('data', 361),
 ('base', 320),
 ('web', 320),
 ('digit', 315),
 ('system', 314),
 ('us', 257),
 ('mine', 243),
 ('new', 236),
 ('open', 235),
 ('internet', 234),
 ('analysi', 202),
 ('search', 191),
 ('research', 185),
 ('classif', 180),
 ('model', 175),
 ('servic', 174),
 ('onlin', 163),
 ('manag', 159),
 ('learn', 158),
 ('org', 156),
 ('gener', 153),
 ('tool', 134),
 ('semant', 133),
 ('public', 132),
 ('scienc', 131),
 ('free', 130)]

In [31]:
search_engine = pt.BatchRetrieve(index, wmodel="Tf")

/var/folders/88/9blsh45918g8y3n5vl6vztxr0000gq/T/ipykernel_3547/951663741.py:1: DeprecationWarning: Call to deprecated class BatchRetrieve. (use pt.terrier.Retriever() instead) -- Deprecated since version 0.11.0.
  search_engine = pt.BatchRetrieve(index, wmodel="Tf")

In [33]:
search_engine.search("system")

,qid,docid,docno,rank,score,query
0,1,750,https://www.bibsonomy.org/url/be868d201af37d4a...,0,2.0,system
1,1,1845,https://www.bibsonomy.org/bibtex/27cebe02af1e4...,1,2.0,system
2,1,1861,https://www.bibsonomy.org/bibtex/2e8737a4cce47...,2,2.0,system
3,1,1863,https://www.bibsonomy.org/bibtex/2072b030962e3...,3,2.0,system
4,1,3853,https://www.bibsonomy.org/bibtex/280f75bb46fcb...,4,2.0,system
...,...,...,...,...,...,...
303,1,7950,https://www.bibsonomy.org/bibtex/2ae6a916923ad...,303,1.0,system
304,1,7968,https://www.bibsonomy.org/bibtex/2390b02f23f3d...,304,1.0,system
305,1,7973,https://www.bibsonomy.org/bibtex/25d3f12c5e0f6...,305,1.0,system
306,1,7974,https://www.bibsonomy.org/bibtex/270a5cfbabcbb...,306,1.0,system
307,1,7991,https://www.bibsonomy.org/bibtex/25926f6dbad9b...,307,1.0,system

In [35]:
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()

In [37]:
stem = stemmer.stem("learning")
stem

'learn'

In [39]:
lexicon = index.getLexicon()
lexicon[stem].getDocumentFrequency()

155

In [41]:
index.getCollectionStatistics().numberOfDocuments

8000

In [43]:
def get_idf_for_term(term, index):
  lex = index.getLexicon()
  stemmed_term = stemmer.stem(term)

  if not stemmed_term in lex:
    return 
    
  lex_entry = lex[stemmed_term]

  df_term = lex_entry.getDocumentFrequency()
  N = index.getCollectionStatistics().numberOfDocuments
  
  #inverse document frequency
  idf = N/df_term

  #apply logarithm(base 10) to idf
  log_idf = np.emath.logn(10, idf)

  return log_idf

In [45]:
get_idf_for_term("learning", index)

1.712758288821652

In [49]:
#define your own tf_idf method here:

def calc_tf_idf(query, docno, index):
    #remember that tfidf is the product of two components
    #hint: the tf model search result contains tf frequencies
    return 0

In [47]:
search_engine_tfidf = pt.BatchRetrieve(index, wmodel="TF_IDF")

/var/folders/88/9blsh45918g8y3n5vl6vztxr0000gq/T/ipykernel_3547/2880449899.py:1: DeprecationWarning: Call to deprecated class BatchRetrieve. (use pt.terrier.Retriever() instead) -- Deprecated since version 0.11.0.
  search_engine_tfidf = pt.BatchRetrieve(index, wmodel="TF_IDF")

In [51]:
search_engine_tfidf.search("database")

,qid,docid,docno,rank,score,query
0,1,751,https://www.bibsonomy.org/url/a096f0b12753c22e...,0,2.170079,database
1,1,281,https://www.bibsonomy.org/url/b05f7889d6a0731c...,1,2.058956,database
2,1,287,https://www.bibsonomy.org/url/b05f7889d6a0731c...,2,2.058956,database
3,1,1007,https://www.bibsonomy.org/bibtex/2b8151c596a8d...,3,2.058956,database
4,1,1785,https://www.bibsonomy.org/bibtex/25802e079a691...,4,2.056275,database
...,...,...,...,...,...,...
995,1,573,https://www.bibsonomy.org/url/262cdca8951e45ec...,995,1.360506,database
996,1,579,https://www.bibsonomy.org/url/cd8d11db33dc293f...,996,1.360506,database
997,1,580,https://www.bibsonomy.org/url/61ccc5248c3559d5...,997,1.360506,database
998,1,581,https://www.bibsonomy.org/url/17e00df720be1825...,998,1.360506,database
999,1,586,https://www.bibsonomy.org/url/18670c07c777d29a...,999,1.360506,database

In [53]:
# Index with multiple fields
df_dict = df_filtered.to_dict(orient='records')

In [55]:
df_dict

[{'id': 'https://www.bibsonomy.org/url/cc45493bf442b78d923b0b1b9342676b/springnet',
  'tags': ['web2.0',
   'database',
   'desktop',
   'aggregator',
   'daily',
   'incredible',
   'applications',
   'bookmarking',
   'blog'],
  'label': 'Office 2.0 Database',
  'description': 'Office 2.0 Database',
  'date': '2006-04-19 19:49:42',
  'changeDate': '2008-06-29 17:52:49',
  'url': 'http://itredux.com/office-20/database/',
  'pub-type': nan,
  'year': nan,
  'author': nan,
  'authors': nan,
  'docno': 'https://www.bibsonomy.org/url/cc45493bf442b78d923b0b1b9342676b/springnet',
  'text': 'Office 2.0 Database'},
 {'id': 'https://www.bibsonomy.org/url/61474ed79d5c3f63c1d0b6dcd8c653f5/traktools',
  'tags': ['tool',
   'database',
   '3403',
   'Error',
   'Fix,',
   'recovery,',
   'Database',
   'Recovery',
   'SQL'],
  'label': 'SQL Database 3403 Error Fix',
  'description': 'SysTools Software releases an effective SQL database recovery software to solve your sql database problems as sql database 3403 error and other problems. SQL database repair software frequently restore stored procedures, tables, views, triggers and other all items from damaged MDF files\r\n',
  'date': '2009-09-15 19:13:52',
  'changeDate': '2009-09-15 19:13:52',
  'url': 'http://www.sqlrecoverytool.com/sql-database-3403-error.html',
  'pub-type': nan,
  'year': nan,
  'author': nan,
  'authors': nan,
  'docno': 'https://www.bibsonomy.org/url/61474ed79d5c3f63c1d0b6dcd8c653f5/traktools',
  'text': 'SQL Database 3403 Error Fix'},
 {'id': 'https://www.bibsonomy.org/url/3cd373dd8ed9c53483d39eaa928686f6/panic',
  'tags': ['Article(s)', 'Design', 'Database', 'Information'],
  'label': 'Database Sharding',
  'description': 'The term "sharding" was coined by Google engineers, and popularized through their publication of the Big Table architecture. However, the concept of "shared-nothing" database partitioning has been around for a decade or more and there have been many implementations over this period, especially high profile in-house built solutions by Internet leaders such as eBay, Amazon, Digg, Flickr, Skype, YouTube, Facebook, Friendster, and Wikipedia.',
  'date': '2011-10-01 02:24:14',
  'changeDate': '2011-10-01 02:27:38',
  'url': 'http://www.codefutures.com/database-sharding/',
  'pub-type': nan,
  'year': nan,
  'author': nan,
  'authors': nan,
  'docno': 'https://www.bibsonomy.org/url/3cd373dd8ed9c53483d39eaa928686f6/panic',
  'text': 'Database Sharding'},
 {'id': 'https://www.bibsonomy.org/url/cc45493bf442b78d923b0b1b9342676b/akpe',
  'tags': ['web2.0', '2007', 'database', 'socialsoftware', 'tools', 'list'],
  'label': 'Office 2.0 Database',
  'description': 'Overview of roughly 250 Web 2.0 applications, including 29 bookmarking applications, 13 calendar applications, 5 contacts managers, 17 CRM systems, 11 database managers, 17 desktops, 14 development tools, 8 document managers, 11 feed readers, etc',
  'date': '2007-03-14 20:26:50',
  'changeDate': '2011-03-14 16:42:58',
  'url': 'http://itredux.com/office-20/database/',
  'pub-type': nan,
  'year': nan,
  'author': nan,
  'authors': nan,
  'docno': 'https://www.bibsonomy.org/url/cc45493bf442b78d923b0b1b9342676b/akpe',
  'text': 'Office 2.0 Database'},
 {'id': 'https://www.bibsonomy.org/url/2f5f76391c720a9b688f60ec6f900f1d/ludaesch',
  'tags': ['databases'],
  'label': 'Encyclopedia of Database Systems',
  'description': 'Encyclopedia of Database Systems',
  'date': '2007-02-08 11:20:08',
  'changeDate': '2007-09-26 06:23:20',
  'url': 'http://refworks.springer.com/database-systems/',
  'pub-type': nan,
  'year': nan,
  'author': nan,
  'authors': nan,
  'docno': 'https://www.bibsonomy.org/url/2f5f76391c720a9b688f60ec6f900f1d/ludaesch',
  'text': 'Encyclopedia of Database Systems'},
 {'id': 'https://www.bibsonomy.org/url/a61cde4a068fbdcd6e62c4aba774e8c0/traktools',
  'tags': ['Recovery,', 'Database', 'SQL', 'Repair'],
  'label': 'SQL Database Recovery',
  'description': 'Are you facing SQL data loss problem due to corruption of MS SQL Server (.MDF) files. Get SysTools SQL Recovery Tool and repair corrupt MDF files. SysTools SQL database recovery software can restore your all SQL Server meta data (tables, views, triggers, stored procedures, default values, user data types, functions etc) from corrupt MDF files.',
  'date': '2009-06-04 18:44:16',
  'changeDate': '2009-06-04 18:44:16',
  'url': 'http://www.nsftopst.com/sql-database-recovery-tool.html',
  'pub-type': nan,
  'year': nan,
  'author': nan,
  'authors': nan,
  'docno': 'https://www.bibsonomy.org/url/a61cde4a068fbdcd6e62c4aba774e8c0/traktools',
  'text': 'SQL Database Recovery'},
 {'id': 'https://www.bibsonomy.org/url/951c278564ddeaf05f3b623107ab2166/lysander07',
  'tags': ['database', '2012', 'sql', 'nosql'],
  'label': 'Updated database landscape graphic — Too much information',
  'description': 'infographic on current database landscape - sql, nosql, relational, graph, etc.',
  'date': '2012-11-04 10:35:18',
  'changeDate': '2012-11-04 10:35:18',
  'url': 'http://blogs.the451group.com/information_management/2012/11/02/updated-database-landscape-graphic/',
  'pub-type': nan,
  'year': nan,
  'author': nan,
  'authors': nan,
  'docno': 'https://www.bibsonomy.org/url/951c278564ddeaf05f3b623107ab2166/lysander07',
  'text': 'Updated database landscape graphic — Too much information'},
 {'id': 'https://www.bibsonomy.org/url/f24421e7631b58b6a933634efecd96ed/flykeysky',
  'tags': ['database', 'index', 'article'],
  'label': 'Database indexes for database speed & optimization',
  'description': '',
  'date': '2009-02-06 15:09:32',
  'changeDate': '2009-02-12 03:07:51',
  'url': 'http://www.websitedatabases.com/database-index.html',
  'pub-type': nan,
  'year': nan,
  'author': nan,
  'authors': nan,
  'docno': 'https://www.bibsonomy.org/url/f24421e7631b58b6a933634efecd96ed/flykeysky',
  'text': 'Database indexes for database speed & optimization'},
 {'id': 'https://www.bibsonomy.org/url/ea505f12ee46959719250ded1771e349/colindolly',
  'tags': ['software', 'Database', 'recovery'],
  'label': 'Database recovery software',
  'description': 'Database recovery software to repair corrupted access database & SQL Server Database. Repair and Recover corrupt database from Access and SQL. Stellar Phoenix SQL Database Recovery utility is the key tool for repairing the corrupted databases of MS SQL Server. This database repair software can repair all the database objects like triggers, stored procedures, views and lot many. The software creates the script files from which the repaired database can be retrieved. Database recovery software to repair corrupted access database & SQL Server Database. Repair and Recover corrupt database from Access and SQL\r\n\r\n\r\nFor More Details:-  http://www.database-recovery-software.com/\r\n',
  'date': '2009-07-02 13:36:24',
  'changeDate': '2009-07-02 13:36:24',
  'url': 'http://www.database-recovery-software.com/',
  'pub-type': nan,
  'year': nan,
  'author': nan,
  'authors': nan,
  'docno': 'https://www.bibsonomy.org/url/ea505f12ee46959719250ded1771e349/colindolly',
  'text': 'Database recovery software'},
 {'id': 'https://www.bibsonomy.org/url/6eccf72b8f65d35dd1dc9e2f1dac80e1/mdehghan',
  'tags': ['database', 'IDS', 'signature', 'cisco'],
  'label': 'IDS signature database !!! | Other Security Subjects | Cisco Support Community | 5806 | 9451456',
  'description': 'IDS signature database !!! | Other Security Subjects | Cisco Technical Support Forum | 5806 | 9451456',
  'date': '2015-06-07 21:27:03',
  'changeDate': '2015-06-07 21:27:03',
  'url': 'https://supportforums.cisco.com/discussion/9451456/ids-signature-database',
  'pub-type': nan,
  'year': nan,
  'author': nan,
  'authors': nan,
  'docno': 'https://www.bibsonomy.org/url/6eccf72b8f65d35dd1dc9e2f1dac80e1/mdehghan',
  'text': 'IDS signature database !!! | Other Security Subjects | Cisco Support Community | 5806 | 9451456'},
 {'id': 'https://www.bibsonomy.org/url/525e8fe1188cad8723c2d2dbee9e0ba0/springnet',
  'tags': ['database', 'hierarchical', 'mysql'],
  'label': 'Storing Hierarchical Data in a Database',
  'description': 'Whether you want to build your own forum, publish the messages from a mailing list on your Website, or write your own cms [1]: there will be a moment that you’ll want to store hierarchical data in a database. And, unless you’re using a XML [2]-like da',
  'date': '2006-07-24 03:47:16',
  'changeDate': '2008-06-29 17:50:38',
  'url': 'http://www.sitepoint.com/print/hierarchical-data-database',
  'pub-type': nan,
  'year': nan,
  'author': nan,
  'authors': nan,
  'docno': 'https://www.bibsonomy.org/url/525e8fe1188cad8723c2d2dbee9e0ba0/springnet',
  'text': 'Storing Hierarchical Data in a Database'},
 {'id': 'https://www.bibsonomy.org/url/52ea707164fbc944952c94a3dd916098/colindolly',
  'tags': ['repair', 'software', 'Database'],
  'label': 'Database repair software',
  'description': 'Stellar Phoenix SQL Database Recovery utility is the key tool for repairing the corrupted databases of MS SQL Server. This database repair software can repair all the database objects like triggers, stored procedures, views and lot many. The software creates the script files from which the repaired database can be retrieved. Database repair software to repair corrupted access database & SQL Server Database. Repair and Recover corrupt database from Access and SQL"\r\n\r\n\r\nFor More Details:-  http://www.database-repair-software.com/\r\n',
  'date': '2009-07-02 13:37:11',
  'changeDate': '2009-07-02 13:37:11',
  'url': 'http://www.database-repair-software.com/',
  'pub-type': nan,
  'year': nan,
  'author': nan,
  'authors': nan,
  'docno': 'https://www.bibsonomy.org/url/52ea707164fbc944952c94a3dd916098/colindolly',
  'text': 'Database repair software'},
 {'id': 'https://www.bibsonomy.org/url/f5cda44a0641661e095a56acde47e241/lystrata',
  'tags': ['analytics', 'database', 'visualization', 'data'],
  'label': 'Database visualization',
  'description': 'Database Visualization tool',
  'date': '2007-03-17 01:15:31',
  'changeDate': '2010-02-20 02:11:50',
  'url': 'http://www.visokio.com/omniscope/',
  'pub-type': nan,
  'year': nan,
  'author': nan,
  'authors': nan,
  'docno': 'https://www.bibsonomy.org/url/f5cda44a0641661e095a56acde47e241/lystrata',
  'text': 'Database visualization'},
 {'id': 'https://www.bibsonomy.org/url/e1a0101336c7ffd6b735d893a894a042/gresch',
  'tags': ['database',
   'computing',
   'develop',
   'refactoring',
   'tools',
   'sql',
   'db'],
  'label': 'Database Refactoring',
  'description': 'The Sundog Database Refactoring Tool (SDRT) is an open source (LGPL), DBMS-independent library that eases database development, particularly in an agile environment.',
  'date': '2007-04-16 13:20:54',
  'changeDate': '2007-04-16 13:20:54',
  'url': 'http://www.sundog.net/index.php/databaserefactoring/',
  'pub-type': nan,
  'year': nan,
  'author': nan,
  'authors': nan,
  'docno': 'https://www.bibsonomy.org/url/e1a0101336c7ffd6b735d893a894a042/gresch',
  'text': 'Database Refactoring'},
 {'id': 'https://www.bibsonomy.org/url/010e73c9e0beea891799e917e76c70e5/iblis',
  'tags': ['imported',
   'ecology',
   'biology',
   'species',
   'database',
   'invasion'],
  'label': 'Global Invasive Species Database',
  'description': '',
  'date': '2006-05-01 11:12:42',
  'changeDate': '2010-12-19 03:20:50',
  'url': 'http://www.issg.org/database/welcome/',
  'pub-type': nan,
  'year': nan,
  'author': nan,
  'authors': nan,
  'docno': 'https://www.bibsonomy.org/url/010e73c9e0beea891799e917e76c70e5/iblis',
  'text': 'Global Invasive Species Database'},
 {'id': 'https://www.bibsonomy.org/url/d9c7e8d4ccd32f1f46e6b628865c340d/traktools',
  'tags': ['MS', 'Database', 'SQL', 'Repair'],
  'label': 'SQL Database Repair',
  'description': 'MS SQL Database Repair Software from SysTools to repair SQL 2008 database, repair SQL 2005 database and repair SQL 2000 database reliably and comfortably. Gets an idea about How to repair corrupt SQL database or how to repair MDF file using this MS SQL repair software.',
  'date': '2009-12-30 17:10:27',
  'changeDate': '2009-12-30 17:10:27',
  'url': 'http://www.sql.databaserepair.net/',
  'pub-type': nan,
  'year': nan,
  'author': nan,
  'authors': nan,
  'docno': 'https://www.bibsonomy.org/url/d9c7e8d4ccd32f1f46e6b628865c340d/traktools',
  'text': 'SQL Database Repair'},
 {'id': 'https://www.bibsonomy.org/url/5c9906f9bb89d15f1b684c3a65e30f0a/lystrata',
  'tags': ['hypertable',
   'database',
   'mapreduce',
   'distributed',
   'bigtable',
   'hadoop'],
  'label': '451 CAOS Theory » Introducing Hypertable - a new open source database project',
  'description': 'Introducing Hypertable - a new open source database project',
  'date': '2008-02-21 06:07:50',
  'changeDate': '2010-02-20 02:11:07',
  'url': 'http://blogs.the451group.com/opensource/2008/02/19/introducing-hypertable-a-new-open-source-database-project/',
  'pub-type': nan,
  'year': nan,
  'author': nan,
  'authors': nan,
  'docno': 'https://www.bibsonomy.org/url/5c9906f9bb89d15f1b684c3a65e30f0a/lystrata',
  'text': '451 CAOS Theory » Introducing Hypertable - a new open source database project'},
 {'id': 'https://www.bibsonomy.org/url/96589b1b947236e3965a783607d0ba2f/pitman',
  'tags': ['projects', 'biodiversity', 'database'],
  'label': 'TDWG: Projects Database',
  'description': 'Data Standards\r\nAgriculture Network Information Center \tData In',
  'date': '2008-12-22 21:34:00',
  'changeDate': '2008-12-22 21:34:00',
  'url': 'http://www.tdwg.org/biodiv-projects/projects-database/',
  'pub-type': nan,
  'year': nan,
  'author': nan,
  'authors': nan,
  'docno': 'https://www.bibsonomy.org/url/96589b1b947236e3965a783607d0ba2f/pitman',
  'text': 'TDWG: Projects Database'},
 {'id': 'https://www.bibsonomy.org/url/e8fc97d4e028ac95cae5bc30ca74c91e/nosebrain',
  'tags': ['database', 'profiler', 'mongodb'],
  'label': 'Database Profiler - MongoDB',
  'description': '',
  'date': '2011-08-11 14:13:51',
  'changeDate': '2011-08-11 14:13:51',
  'url': 'http://www.mongodb.org/display/DOCS/Database+Profiler',
  'pub-type': nan,
  'year': nan,
  'author': nan,
  'authors': nan,
  'docno': 'https://www.bibsonomy.org/url/e8fc97d4e028ac95cae5bc30ca74c91e/nosebrain',
  'text': 'Database Profiler - MongoDB'},
 {'id': 'https://www.bibsonomy.org/url/5677b0a29fec816a54bcd5acd92b6f77/lystrata',
  'tags': ['science',
   'reference',
   'biology',
   'database',
   'nature',
   'interesting',
   'animals',
   'health',
   'list'],
  'label': 'Search the AnAge Database',
  'description': 'Age Database',
  'date': '2008-06-30 03:33:07',
  'changeDate': '2010-02-20 02:10:51',
  'url': 'http://genomics.senescence.info/species/query.php?show=5&sort=4&page=1',
  'pub-type': nan,
  'year': nan,
  'author': nan,
  'authors': nan,
  'docno': 'https://www.bibsonomy.org/url/5677b0a29fec816a54bcd5acd92b6f77/lystrata',
  'text': 'Search the AnAge Database'},
 {'id': 'https://www.bibsonomy.org/url/cc45493bf442b78d923b0b1b9342676b/kleverson',
  'tags': ['collaborative', 'Database', 'office'],
  'label': 'Itredux.com/office-20/database/',
  'description': 'interessantíssimo',
  'date': '2006-04-22 17:24:54',
  'changeDate': '2006-04-22 17:24:54',
  'url': 'http://itredux.com/office-20/database/',
  'pub-type': nan,
  'year': nan,
  'author': nan,
  'authors': nan,
  'docno': 'https://www.bibsonomy.org/url/cc45493bf442b78d923b0b1b9342676b/kleverson',
  'text': 'Itredux.com/office-20/database/'},
 {'id': 'https://www.bibsonomy.org/url/07e7575804a281f1c344da89256ddeee/pitman',
  'tags': ['database',
   'bio',
   'collaborative',
   'source',
   'tools',
   'db',
   'open'],
  'label': 'GMOD: Generic Model Organism Database',
  'description': 'Generic Model Organism Database project, a collection of open source software tools for creating and managing genome-scale biological databases. You can use it to create a small laboratory database of genome annotations, or a large web-accessible community database. GMOD tools are in use at many large and small community databases.',
  'date': '2008-04-06 18:18:59',
  'changeDate': '2008-04-06 18:18:59',
  'url': 'http://www.gmod.org/home',
  'pub-type': nan,
  'year': nan,
  'author': nan,
  'authors': nan,
  'docno': 'https://www.bibsonomy.org/url/07e7575804a281f1c344da89256ddeee/pitman',
  'text': 'GMOD: Generic Model Organism Database'},
 {'id': 'https://www.bibsonomy.org/url/a864ce7a699f298b40a176cebc0ca6b6/fisherlibrary',
  'tags': ['jihadist',
   'terrorism',
   'speeches',
   'extremist',
   'jihad',
   'interviews',
   'terrorist',
   'statements',
   'fundamentalistmuslim',
   'publications'],
  'label': 'RAND Voices of Jihad Database (Terrorism Database)',
  'description': 'This online database is a compilation of speeches, interviews, statements, and publications of jihadist leaders, foot soldiers, and sympathizers. Nearly all content is in English translation, and has been collected from publicly-accessible websites. Original links are provided, along with excerpts and full-text content when available.',
  'date': '2010-06-22 21:44:54',
  'changeDate': '2010-06-22 21:44:54',
  'url': 'http://www.rand.org/research_areas/terrorism/database/',
  'pub-type': nan,
  'year': nan,
  'author': nan,
  'authors': nan,
  'docno': 'https://www.bibsonomy.org/url/a864ce7a699f298b40a176cebc0ca6b6/fisherlibrary',
  'text': 'RAND Voices of Jihad Database (Terrorism Database)'},
 {'id': 'https://www.bibsonomy.org/url/d1c8b0d680c78bf47bdd8c5896e3a7b6/mobileink',
  'tags': ['bibliography',
   'library',
   'web',
   'mgmt',
   'database',
   'doc',
   'bibtex',
   'db'],
  'label': 'Document Database',
  'description': 'The Document Database was grown out of the need to organize research papers and their BibTex entries.',
  'date': '2006-06-08 19:12:53',
  'changeDate': '2006-06-08 19:12:53',
  'url': 'http://docdb.sourceforge.net/',
  'pub-type': nan,
  'year': nan,
  'author': nan,
  'authors': nan,
  'docno': 'https://www.bibsonomy.org/url/d1c8b0d680c78bf47bdd8c5896e3a7b6/mobileink',
  'text': 'Document Database'},
 {'id': 'https://www.bibsonomy.org/url/ef82c9d17fa3a21b17c8c8da8b7c5206/polythetic',
  'tags': ['prosopography',
   'database',
   'antiquity',
   'history',
   'ancient_near_east'],
  'label': 'OA Prosopography Database',
  'description': 'a mySQL backed database of persons occurring in Assyrian texts',
  'date': '2015-07-18 14:45:16',
  'changeDate': '2015-07-18 14:45:16',
  'url': 'http://oatp.net/',
  'pub-type': nan,
  'year': nan,
  'author': nan,
  'authors': nan,
  'docno': 'https://www.bibsonomy.org/url/ef82c9d17fa3a21b17c8c8da8b7c5206/polythetic',
  'text': 'OA Prosopography Database'},
 {'id': 'https://www.bibsonomy.org/url/8848bfb6ce8a6e6f1c670fc41204b6ba/pitman',
  'tags': ['science', 'commons', 'database', 'legal', 'protocol', 'creative'],
  'label': 'Science Commons: Database Protocol',
  'description': '',
  'date': '2008-11-02 02:21:57',
  'changeDate': '2008-11-02 02:21:57',
  'url': 'http://sciencecommons.org/resources/faq/database-protocol/',
  'pub-type': nan,
  'year': nan,
  'author': nan,
  'authors': nan,
  'docno': 'https://www.bibsonomy.org/url/8848bfb6ce8a6e6f1c670fc41204b6ba/pitman',
  'text': 'Science Commons: Database Protocol'},
 {'id': 'https://www.bibsonomy.org/url/3279b849950f64742b3be2c1a04832f4/traktools',
  'tags': ['Database', 'Recovery', 'Open', 'Sql'],
  'label': 'Open SQL Database',
  'description': 'An exclusive solution from SysTools Software labs to open SQL server 2005 and 2000 database files even MDF file get damaged or corrupted. SQL database repair software is adept to open damaged or corrupted MDF database files and restore stored procedures, tables, triggers, views and other data.\r\n',
  'date': '2009-09-08 17:33:31',
  'changeDate': '2009-09-08 17:33:31',
  'url': 'http://www.sqlrecoverytool.com/open-sql.html',
  'pub-type': nan,
  'year': nan,
  'author': nan,
  'authors': nan,

In [63]:
index_folder_mult = "./index_mult"

fields=['docno', 'text', 'tags', 'description']

indexer_mult = pt.IterDictIndexer(index_folder_mult, meta={'docno': 200, 'text': 4096}, overwrite=True)
index_ref_mult = indexer_mult.index(df_dict)

print(f"path to our index: {index_ref_mult.toString()}")

09:18:16.597 [ForkJoinPool-1-worker-1] WARN org.terrier.structures.indexing.Indexer -- Adding an empty document to the index (https://www.bibsonomy.org/url/45d7bb8eace077fe1f46f404529960f4/iblis) - further warnings are suppressed
09:18:16.975 [ForkJoinPool-1-worker-1] WARN org.terrier.structures.indexing.Indexer -- Indexed 4 empty documents
path to our index: ./index_mult/data.properties

In [65]:
index_mult = pt.IndexFactory.of(index_ref_mult)

In [67]:
print(index_mult.getCollectionStatistics().toString())

Number of documents: 8000
Number of terms: 8495
Number of postings: 46900
Number of fields: 1
Number of tokens: 48683
Field names: [text]
Positions:   false

In [69]:
search_engine_mult = pt.terrier.Retriever(index_mult, wmodel="TF_IDF")

In [71]:
res = search_engine_mult.search("intelligence")
res

,qid,docid,docno,rank,score,query
0,1,119,https://www.bibsonomy.org/url/8f1fb00012322e81...,0,5.319447,intelligence
1,1,3009,https://www.bibsonomy.org/bibtex/21a61a34d4984...,1,5.319447,intelligence
2,1,3092,https://www.bibsonomy.org/bibtex/21a61a34d4984...,2,5.319447,intelligence
3,1,3667,https://www.bibsonomy.org/bibtex/2508ce3b4cfd8...,3,5.319447,intelligence
4,1,6244,https://www.bibsonomy.org/url/7e3b188d3277ff0c...,4,5.319447,intelligence
5,1,3407,https://www.bibsonomy.org/bibtex/2326beb667d4c...,5,4.933700,intelligence
6,1,3545,https://www.bibsonomy.org/bibtex/255165fc7f1f9...,6,4.933700,intelligence
7,1,573,https://www.bibsonomy.org/url/262cdca8951e45ec...,7,4.600116,intelligence
8,1,2796,https://www.bibsonomy.org/url/e94f2e8c95d6fd01...,8,4.600116,intelligence
9,1,3205,https://www.bibsonomy.org/bibtex/2934ad4d54596...,9,4.600116,intelligence
10,1,7461,https://www.bibsonomy.org/bibtex/2e3677666eee2...,10,4.600116,intelligence
11,1,1560,https://www.bibsonomy.org/bibtex/2a9aeedc023b8...,11,4.308785,intelligence
12,1,6997,https://www.bibsonomy.org/url/a63d1bffada91ede...,12,4.308785,intelligence
13,1,7743,https://www.bibsonomy.org/bibtex/20bd599a1d3e4...,13,4.308785,intelligence
14,1,7873,https://www.bibsonomy.org/bibtex/2eb29bdfaeb62...,14,4.308785,intelligence
15,1,1319,https://www.bibsonomy.org/bibtex/2e01c06213221...,15,4.052157,intelligence
16,1,1330,https://www.bibsonomy.org/bibtex/2e01c06213221...,16,4.052157,intelligence
17,1,3534,https://www.bibsonomy.org/bibtex/2a13a19576a30...,17,4.052157,intelligence
18,1,7839,https://www.bibsonomy.org/bibtex/28f08bb5a969f...,18,4.052157,intelligence
19,1,1191,https://www.bibsonomy.org/bibtex/24174ad281bc2...,19,3.824379,intelligence
20,1,4492,https://www.bibsonomy.org/url/ab0ffbd0949eb1a7...,20,3.824379,intelligence
21,1,4936,https://www.bibsonomy.org/url/e89e7e0680809e64...,21,3.824379,intelligence
22,1,7983,https://www.bibsonomy.org/bibtex/217e640a5e9c6...,22,3.824379,intelligence
23,1,1705,https://www.bibsonomy.org/bibtex/2dada3848a74e...,23,3.620847,intelligence

In [75]:
#save our data
pickle.dump(df_filtered, open("index_mult/df_publications.pkl", "wb"))

In [77]:
#install steamlit
%pip install streamlit

Requirement already satisfied: streamlit in /opt/anaconda3/lib/python3.12/site-packages (1.37.1)
Requirement already satisfied: altair<6,>=4.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (5.0.1)
Requirement already satisfied: blinker<2,>=1.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (1.6.2)
Requirement already satisfied: cachetools<6,>=4.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (5.3.3)
Requirement already satisfied: click<9,>=7.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (8.1.7)
Requirement already satisfied: numpy<3,>=1.20 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (1.26.4)
Requirement already satisfied: packaging<25,>=20 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (24.1)
Requirement already satisfied: pandas<3,>=1.3.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<11,>=7.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (10.4.0)
Requirement already satisfied: protobuf<6,>=3.20 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (4.25.3)
Requirement already satisfied: pyarrow>=7.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (16.1.0)
Requirement already satisfied: requests<3,>=2.27 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (2.32.3)
Requirement already satisfied: rich<14,>=10.14.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (13.7.1)
Requirement already satisfied: tenacity<9,>=8.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (8.2.3)
Requirement already satisfied: toml<2,>=0.10.1 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.3.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (4.11.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (3.1.43)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (0.8.0)
Requirement already satisfied: tornado<7,>=6.0.3 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (6.4.1)
Requirement already satisfied: jinja2 in /opt/anaconda3/lib/python3.12/site-packages (from altair<6,>=4.0->streamlit) (3.1.4)
Requirement already satisfied: jsonschema>=3.0 in /opt/anaconda3/lib/python3.12/site-packages (from altair<6,>=4.0->streamlit) (4.23.0)
Requirement already satisfied: toolz in /opt/anaconda3/lib/python3.12/site-packages (from altair<6,>=4.0->streamlit) (0.12.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /opt/anaconda3/lib/python3.12/site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.7)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.12/site-packages (from pandas<3,>=1.3.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.12/site-packages (from pandas<3,>=1.3.0->streamlit) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.12/site-packages (from pandas<3,>=1.3.0->streamlit) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit) (2024.8.30)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from rich<14,>=10.14.0->streamlit) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/anaconda3/lib/python3.12/site-packages (from rich<14,>=10.14.0->streamlit) (2.15.1)
Requirement already satisfied: smmap<5,>=3.0.1 in /opt/anaconda3/lib/python3.12/site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.12/site-packages (from jinja2->altair<6,>=4.0->streamlit) (2.1.3)
Requirement already satisfied: attrs>=22.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in /opt/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in /opt/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.10.6)
Requirement already satisfied: mdurl~=0.1 in /opt/anaconda3/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit) (0.1.0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.3.0->streamlit) (1.16.0)
Note: you may need to restart the kernel to use updated packages.