In [1]:
import pyterrier as pt
import requests
import pandas as pd
import pickle
import nltk
import numpy as np
import json

In [9]:
df_filtered = pd.read_json('output.json')
df_filtered

,title,id,type,url,year,authors,doi,query,editor
0,EcoliNet: a database of cofunctional gene netw...,https://www.bibsonomy.org/bibtex/2750b8770eec8...,Publication,http://dx.doi.org/10.1093/database/bav001,2015,"[Hanhae Kim, Jung Eun E. Shim, Junha Shin, Ins...",10.1093/database/bav001,database,Jannik Ott
1,The drug-minded protein interaction database (...,https://www.bibsonomy.org/bibtex/2d93ac9b6cfa6...,Publication,http://dx.doi.org/10.1093/database/baw041,2016,"[Meik Kunz, Chunguang Liang, Santosh Nilla, Al...",10.1093/database/baw041,database,Jannik Ott
2,PhosphoGRID: a database of experimentally veri...,https://www.bibsonomy.org/bibtex/233d3effaf95a...,Publication,http://dx.doi.org/10.1093/database/bap026,2010,"[Chris Stark, Ting-Cheng C. Su, Ashton Breitkr...",10.1093/database/bap026,database,Jannik Ott
3,GoSynthetic database tool to analyse natural a...,https://www.bibsonomy.org/bibtex/2ca6461cce248...,Publication,http://dx.doi.org/10.1093/database/bat043,2013,"[C. Liang, B. Kruger, T. Dandekar]",10.1093/database/bat043,database,Jannik Ott
4,Database for Mobile Application,https://www.bibsonomy.org/bibtex/2eb1605409b13...,Publication,http://www.ijtsrd.com/computer-science/databas...,2018,[Jasra Nisar Owais Noor Trumboo],None,database,Jannik Ott
...,...,...,...,...,...,...,...,...,...
3515,Faculty self-archiving behavior: Factors affec...,https://www.bibsonomy.org/bibtex/2040f345d94cd...,Publication,http://dblp.uni-trier.de/db/conf/asist/asist20...,2007,[Jihyun Kim],None,archive,Jannik Ott
3516,Sensitivity and Access: Unlocking the Colonial...,https://www.bibsonomy.org/bibtex/28217f4fe9f6a...,Publication,http://dblp.uni-trier.de/db/journals/dhq/dhq18...,2024,"[Jonathan Dentler, Lise Jaillant, Daniel Folia...",None,archive,Jannik Ott
3517,Online hot topic detection from web news archi...,https://www.bibsonomy.org/bibtex/29994ea45725f...,Publication,http://dblp.uni-trier.de/db/conf/fskd/fskd2014...,2014,"[RuiGuo Yu, Mankun Zhao, Peng Chang, MuWen He]",None,archive,Jannik Ott
3518,Serge Modular Archive Instrument (SMAI): Bridg...,https://www.bibsonomy.org/bibtex/2ee55445bc456...,Publication,http://dblp.uni-trier.de/db/conf/nime/nime2023...,2023,"[Ted Moore, Jean Brazeau]",None,archive,Jannik Ott
3519,The peer-to-peer trace archive: design and com...,https://www.bibsonomy.org/bibtex/2dc534ef1b015...,Publication,http://dblp.uni-trier.de/db/conf/conext/sw2010...,2010,"[Boxun Zhang, Alexandru Iosup, Johan Pouwelse,...",None,archive,Jannik Ott

In [11]:
df_filtered.columns

Index(['title', 'id', 'type', 'url', 'year', 'authors', 'doi', 'query',
       'editor'],
      dtype='object')

In [13]:
#pyterrier exspects a docno field
df_filtered['docno'] = df_filtered['id']
df_filtered['text'] = df_filtered['title']

In [15]:
index_folder = "./df_index"

indexer = pt.DFIndexer(index_folder, overwrite=True)
index_ref = indexer.index(df_filtered['text'], df_filtered['docno'])

print(f"path to our index: {index_ref.toString()}")

/var/folders/88/9blsh45918g8y3n5vl6vztxr0000gq/T/ipykernel_1707/146072258.py:3: DeprecationWarning: Call to deprecated class DFIndexer. (use pt.terrier.IterDictIndexer().index(dataframe.to_dict(orient='records')) instead) -- Deprecated since version 0.11.0.
  indexer = pt.DFIndexer(index_folder, overwrite=True)
Java started (triggered by TerrierIndexer.__init__) and loaded: pyterrier.java, pyterrier.terrier.java [version=5.11 (build: craig.macdonald 2025-01-13 21:29), helper_version=0.0.8]

09:33:52.066 [main] WARN org.terrier.structures.indexing.Indexer -- Adding an empty document to the index (https://www.bibsonomy.org/bibtex/2998392ade6025286fed26bb09fc3dfc0/bibgreen) - further warnings are suppressed
09:33:52.467 [main] WARN org.terrier.structures.indexing.Indexer -- Indexed 2 empty documents
path to our index: ./df_index/data.properties

In [17]:
index = pt.IndexFactory.of(index_ref)

In [19]:
print(index.getCollectionStatistics().toString())

Number of documents: 3520
Number of terms: 5030
Number of postings: 23455
Number of fields: 0
Number of tokens: 24180
Field names: []
Positions:   false

In [21]:
for kv in index.getLexicon():
    print(f"{kv.getKey()} -> {kv.getValue().toString()}")

0 -> term165 Nt=34 TF=39 maxTF=3 @{0 0 0}
000 -> term2348 Nt=2 TF=2 maxTF=1 @{0 49 1}
050 -> term1142 Nt=1 TF=1 maxTF=1 @{0 54 5}
06 -> term4159 Nt=1 TF=1 maxTF=1 @{0 56 7}
1 -> term219 Nt=20 TF=23 maxTF=2 @{0 59 7}
10 -> term3466 Nt=2 TF=2 maxTF=1 @{0 94 4}
100 -> term2346 Nt=2 TF=2 maxTF=1 @{0 100 0}
10g -> term1038 Nt=1 TF=1 maxTF=1 @{0 105 0}
11 -> term4230 Nt=2 TF=2 maxTF=1 @{0 107 2}
115th -> term1974 Nt=1 TF=1 maxTF=1 @{0 112 4}
12 -> term2533 Nt=1 TF=1 maxTF=1 @{0 115 0}
14 -> term4158 Nt=1 TF=1 maxTF=1 @{0 117 6}
140 -> term3046 Nt=1 TF=1 maxTF=1 @{0 120 6}
153 -> term579 Nt=1 TF=1 maxTF=1 @{0 123 4}
16 -> term4125 Nt=1 TF=1 maxTF=1 @{0 125 4}
16th -> term1602 Nt=1 TF=1 maxTF=1 @{0 128 4}
17 -> term4197 Nt=2 TF=2 maxTF=1 @{0 131 0}
18 -> term484 Nt=1 TF=1 maxTF=1 @{0 136 0}
1869 -> term4280 Nt=1 TF=1 maxTF=1 @{0 138 0}
1878 -> term4942 Nt=1 TF=1 maxTF=1 @{0 141 0}
19 -> term619 Nt=7 TF=8 maxTF=2 @{0 144 0}
1939 -> term4871 Nt=1 TF=1 maxTF=1 @{0 158 3}
1941 -> term4939 Nt=1 TF=1 maxTF=1 @{0 161 3}
1945 -> term4870 Nt=1 TF=1 maxTF=1 @{0 164 3}
1950 -> term2998 Nt=1 TF=1 maxTF=1 @{0 167 3}
1959 -> term3129 Nt=2 TF=2 maxTF=1 @{0 170 1}
1960 -> term4928 Nt=1 TF=1 maxTF=1 @{0 174 7}
1960er -> term4544 Nt=1 TF=1 maxTF=1 @{0 177 7}
1965 -> term3915 Nt=1 TF=1 maxTF=1 @{0 180 7}
1967 -> term3682 Nt=1 TF=1 maxTF=1 @{0 183 7}
1970 -> term2978 Nt=2 TF=2 maxTF=1 @{0 186 7}
1976 -> term3042 Nt=1 TF=1 maxTF=1 @{0 191 7}
1980er -> term4547 Nt=1 TF=1 maxTF=1 @{0 194 5}
1984 -> term3131 Nt=1 TF=1 maxTF=1 @{0 197 5}
1986 -> term4247 Nt=1 TF=1 maxTF=1 @{0 200 3}
1990 -> term2979 Nt=1 TF=1 maxTF=1 @{0 203 3}
1994 -> term2126 Nt=1 TF=1 maxTF=1 @{0 206 1}
1997 -> term1181 Nt=1 TF=1 maxTF=1 @{0 208 7}
1999 -> term3190 Nt=1 TF=1 maxTF=1 @{0 211 1}
1d -> term3488 Nt=1 TF=1 maxTF=1 @{0 213 7}
1st -> term3288 Nt=1 TF=1 maxTF=1 @{0 216 7}
2 -> term164 Nt=39 TF=40 maxTF=2 @{0 219 5}
20 -> term3744 Nt=2 TF=2 maxTF=1 @{0 277 0}
2000 -> term1076 Nt=7 TF=7 maxTF=1 @{0 282 2}
2001 -> term1221 Nt=2 TF=2 maxTF=1 @{0 297 6}
2002 -> term1492 Nt=1 TF=1 maxTF=1 @{0 303 0}
2003 -> term1635 Nt=1 TF=1 maxTF=1 @{0 305 4}
2004 -> term252 Nt=1 TF=1 maxTF=1 @{0 308 0}
2005 -> term256 Nt=2 TF=2 maxTF=1 @{0 309 6}
2006 -> term87 Nt=2 TF=2 maxTF=1 @{0 314 4}
2007 -> term3811 Nt=2 TF=2 maxTF=1 @{0 317 4}
2009 -> term181 Nt=3 TF=3 maxTF=1 @{0 322 2}
2010 -> term3361 Nt=2 TF=2 maxTF=1 @{0 328 6}
2011 -> term677 Nt=3 TF=3 maxTF=1 @{0 332 4}
2012 -> term2012 Nt=2 TF=2 maxTF=1 @{0 339 4}
2014 -> term3254 Nt=2 TF=2 maxTF=1 @{0 344 4}
2015 -> term1187 Nt=6 TF=6 maxTF=1 @{0 349 0}
2016 -> term1835 Nt=6 TF=6 maxTF=1 @{0 361 6}
2017 -> term1975 Nt=3 TF=5 maxTF=2 @{0 374 2}
2018 -> term816 Nt=6 TF=6 maxTF=1 @{0 382 2}
2019 -> term3308 Nt=8 TF=9 maxTF=2 @{0 396 0}
2020 -> term2808 Nt=2 TF=2 maxTF=1 @{0 408 5}
2021 -> term2784 Nt=4 TF=4 maxTF=1 @{0 414 1}
2022 -> term2807 Nt=2 TF=2 maxTF=1 @{0 423 3}
2030 -> term3082 Nt=9 TF=9 maxTF=1 @{0 427 5}
21 -> term4420 Nt=1 TF=1 maxTF=1 @{0 440 1}
21st -> term1760 Nt=7 TF=7 maxTF=1 @{0 443 1}
22 -> term2903 Nt=2 TF=2 maxTF=1 @{0 457 7}
24 -> term2902 Nt=1 TF=1 maxTF=1 @{0 463 3}
25 -> term3179 Nt=1 TF=1 maxTF=1 @{0 466 1}
256 -> term2465 Nt=1 TF=1 maxTF=1 @{0 468 7}
25th -> term1186 Nt=1 TF=1 maxTF=1 @{0 471 5}
28 -> term2120 Nt=1 TF=1 maxTF=1 @{0 473 7}
29 -> term3123 Nt=1 TF=1 maxTF=1 @{0 476 5}
2bibliometr -> term2822 Nt=1 TF=1 maxTF=1 @{0 479 3}
2d -> term1795 Nt=3 TF=3 maxTF=1 @{0 482 1}
2nd -> term1106 Nt=2 TF=2 maxTF=1 @{0 489 5}
3 -> term1147 Nt=5 TF=5 maxTF=1 @{0 494 5}
30 -> term3976 Nt=2 TF=2 maxTF=1 @{0 505 5}
33 -> term3920 Nt=1 TF=1 maxTF=1 @{0 510 7}
3cdb -> term1815 Nt=1 TF=1 maxTF=1 @{0 513 7}
3d -> term1177 Nt=18 TF=18 maxTF=1 @{0 516 3}
3rd -> term3420 Nt=1 TF=1 maxTF=1 @{0 549 1}
4 -> term1423 Nt=9 TF=9 maxTF=1 @{0 552 1}
40 -> term4378 Nt=1 TF=1 maxTF=1 @{0 569 5}
4586 -> term1973 Nt=1 TF=1 maxTF=1 @{0 572 5}
478 -> term3922 Nt=1 TF=1 maxTF=1 @{0 575 1}
484 -> term3921 Nt=1 TF=1 maxTF=1 @{0 578 1}
5 -> term1329 Nt=2 TF=2 maxTF=1 @{0 581 1}
50 -> term2758 Nt=3 TF=3 maxTF=1 @{0 586 3}
5th -> term596 Nt=1 TF=1 maxTF=1 @{0 594 1}
6 -> term1645 Nt=2 TF=2 maxTF=1 @{0 596 1}
7 -> term1644 Nt=3 TF=3 maxTF=1 @{0 601 5}
71 -> term3684 Nt=1 TF=1 maxTF=1 @{0 609 5}
76th -> term3540 Nt=1 TF=1 maxTF=1 @{0 612 5}
8 -> term2976 Nt=3 TF=3 maxTF=1 @{0 615 5}
82nd -> term3150 Nt=1 TF=1 maxTF=1 @{0 623 3}
8th -> term170 Nt=2 TF=2 maxTF=1 @{0 626 1}
9 -> term4641 Nt=1 TF=1 maxTF=1 @{0 630 3}
a3 -> term2322 Nt=1 TF=1 maxTF=1 @{0 633 3}
a4 -> term3971 Nt=1 TF=1 maxTF=1 @{0 636 1}
aa2 -> term3326 Nt=1 TF=1 maxTF=1 @{0 639 1}
aaai -> term4195 Nt=1 TF=1 maxTF=1 @{0 642 1}
aagingbas -> term276 Nt=1 TF=1 maxTF=1 @{0 645 1}
aatss -> term2096 Nt=1 TF=1 maxTF=1 @{0 646 7}
ab52 -> term3328 Nt=1 TF=1 maxTF=1 @{0 649 3}
abampdb -> term291 Nt=1 TF=1 maxTF=1 @{0 652 3}
abbrevi -> term1159 Nt=1 TF=1 maxTF=1 @{0 654 1}
abcdef -> term4630 Nt=1 TF=1 maxTF=1 @{0 656 3}
abella -> term4688 Nt=1 TF=1 maxTF=1 @{0 659 3}
abiot -> term1336 Nt=1 TF=1 maxTF=1 @{0 662 3}
abschi -> term2548 Nt=1 TF=1 maxTF=1 @{0 664 7}
abschluss -> term4395 Nt=1 TF=1 maxTF=1 @{0 667 5}
absorpt -> term4121 Nt=1 TF=1 maxTF=1 @{0 670 5}
abstract -> term1130 Nt=12 TF=12 maxTF=1 @{0 673 5}
academ -> term732 Nt=58 TF=60 maxTF=3 @{0 695 5}
academi -> term3192 Nt=1 TF=1 maxTF=1 @{0 760 1}
academician -> term4327 Nt=1 TF=1 maxTF=1 @{0 762 7}
acc -> term3705 Nt=1 TF=1 maxTF=1 @{0 765 7}
acceler -> term434 Nt=4 TF=4 maxTF=1 @{0 768 7}
accent -> term4927 Nt=1 TF=1 maxTF=1 @{0 776 7}
access -> term104 Nt=60 TF=60 maxTF=1 @{0 779 7}
accid -> term901 Nt=1 TF=1 maxTF=1 @{0 862 3}
accident -> term2896 Nt=1 TF=1 maxTF=1 @{0 864 5}
accord -> term3460 Nt=2 TF=2 maxTF=1 @{0 867 3}
account -> term1397 Nt=1 TF=1 maxTF=1 @{0 872 5}
accur -> term2720 Nt=1 TF=1 maxTF=1 @{0 875 1}
accuraci -> term1937 Nt=3 TF=3 maxTF=1 @{0 877 7}
acetobas -> term1908 Nt=1 TF=1 maxTF=1 @{0 885 1}
achiev -> term3312 Nt=3 TF=3 maxTF=1 @{0 887 5}
acid -> term610 Nt=5 TF=5 maxTF=1 @{0 895 3}
acinetobact -> term295 Nt=2 TF=2 maxTF=1 @{0 906 3}
acinetobas -> term325 Nt=1 TF=1 maxTF=1 @{0 909 1}
acoust -> term331 Nt=2 TF=2 maxTF=1 @{0 910 7}
acquir -> term2445 Nt=3 TF=3 maxTF=1 @{0 915 5}
acquisit -> term2020 Nt=7 TF=7 maxTF=1 @{0 921 5}
across -> term1566 Nt=5 TF=5 maxTF=1 @{0 936 7}
act -> term1977 Nt=7 TF=7 maxTF=1 @{0 947 1}
action -> term270 Nt=8 TF=8 maxTF=1 @{0 961 3}
activ -> term542 Nt=23 TF=24 maxTF=2 @{0 976 1}
acubert -> term1520 Nt=1 TF=1 maxTF=1 @{0 1015 0}
acupunctur -> term1522 Nt=1 TF=1 maxTF=1 @{0 1017 4}
ad -> term1581 Nt=3 TF=4 maxTF=2 @{0 1020 0}
ada -> term4798 Nt=1 TF=1 maxTF=1 @{0 1027 1}
adam -> term1160 Nt=1 TF=1 maxTF=1 @{0 1030 1}
adapt -> term768 Nt=20 TF=20 maxTF=1 @{0 1032 3}
add -> term3598 Nt=1 TF=1 maxTF=1 @{0 1068 5}
addit -> term2645 Nt=1 TF=1 maxTF=1 @{0 1071 5}
address -> term924 Nt=6 TF=6 maxTF=1 @{0 1074 3}
addresse -> term2567 Nt=1 TF=1 maxTF=1 @{0 1088 1}
adhyayana -> term2282 Nt=1 TF=1 maxTF=1 @{0 1090 7}
aditi -> term1705 Nt=1 TF=1 maxTF=1 @{0 1093 5}
administr -> term846 Nt=6 TF=6 maxTF=1 @{0 1096 1}
ado -> term3933 Nt=1 TF=1 maxTF=1 @{0 1109 1}
adolesc -> term2082 Nt=1 TF=1 maxTF=1 @{0 1112 1}
adopt -> term377 Nt=3 TF=3 maxTF=1 @{0 1114 5}
advanc -> term206 Nt=16 TF=16 maxTF=1 @{0 1121 5}
advantag -> term2981 Nt=1 TF=1 maxTF=1 @{0 1150 5}
adventur -> term2434 Nt=2 TF=2 maxTF=1 @{0 1153 3}
advers -> term1518 Nt=1 TF=1 maxTF=1 @{0 1157 7}
adversari -> term2057 Nt=5 TF=5 maxTF=1 @{0 1160 3}
advertis -> term1988 Nt=3 TF=3 maxTF=1 @{0 1168 7}
advic -> term2940 Nt=1 TF=1 maxTF=1 @{0 1176 3}
advisori -> term2904 Nt=3 TF=3 maxTF=1 @{0 1179 1}
advocaci -> term3408 Nt=1 TF=1 maxTF=1 @{0 1186 1}
aerial -> term1592 Nt=1 TF=1 maxTF=1 @{0 1189 1}
aerob -> term1951 Nt=1 TF=1 maxTF=1 @{0 1191 5}
aesthet -> term3319 Nt=1 TF=1 maxTF=1 @{0 1194 1}
affect -> term1756 Nt=3 TF=3 maxTF=1 @{0 1197 1}
affili -> term3645 Nt=1 TF=1 maxTF=1 @{0 1205 1}
afford -> term3378 Nt=1 TF=1 maxTF=1 @{0 1208 1}
affymetrix -> term855 Nt=1 TF=1 maxTF=1 @{0 1211 1}
afghan -> term4508 Nt=1 TF=1 maxTF=1 @{0 1213 3}
africa -> term3356 Nt=3 TF=3 maxTF=1 @{0 1216 3}
african -> term1316 Nt=2 TF=2 maxTF=1 @{0 1223 3}
aftm -> term507 Nt=1 TF=1 maxTF=1 @{0 1228 7}
ag -> term277 Nt=10 TF=11 maxTF=2 @{0 1230 7}
agata -> term3531 Nt=1 TF=1 maxTF=1 @{0 1250 2}
agbas -> term1890 Nt=1 TF=1 maxTF=1 @{0 1253 2}
agbay -> term3870 Nt=1 TF=1 maxTF=1 @{0 1255 6}
agbiodata -> term1018 Nt=1 TF=1 maxTF=1 @{0 1258 6}
agd -> term1065 Nt=1 TF=1 maxTF=1 @{0 1261 0}
ageid -> term1232 Nt=1 TF=1 maxTF=1 @{0 1263 2}
agenc -> term1515 Nt=1 TF=1 maxTF=1 @{0 1265 4}
agend -> term3774 Nt=1 TF=1 maxTF=1 @{0 1268 0}
agenda -> term2537 Nt=5 TF=5 maxTF=1 @{0 1271 0}
agendi -> term3940 Nt=1 TF=1 maxTF=1 @{0 1281 0}
agent -> term1828 Nt=6 TF=6 maxTF=1 @{0 1284 0}
ager -> term3435 Nt=1 TF=1 maxTF=1 @{0 1297 4}
aggreg -> term1360 Nt=9 TF=9 maxTF=1 @{0 1300 4}
agil -> term3491 Nt=2 TF=2 maxTF=1 @{0 1319 4}
agodb -> term327 Nt=1 TF=1 maxTF=1 @{0 1323 0}
agonist -> term2874 Nt=1 TF=1 maxTF=1 @{0 1324 6}
agreement -> term3201 Nt=1 TF=1 maxTF=1 @{0 1327 4}
agricultur -> term418 Nt=4 TF=4 maxTF=1 @{0 1330 2}
agrosi -> term1262 Nt=1 TF=1 maxTF=1 @{0 1338 6}
ahp -> term461 Nt=2 TF=2 maxTF=1 @{0 1341 0}
ai -> term2847 Nt=3 TF=3 maxTF=1 @{0 1345 6}
aid -> term1615 Nt=2 TF=2 maxTF=1 @{0 1353 2}
aimedgraph -> term1424 Nt=1 TF=1 maxTF=1 @{0 1358 6}
air -> term5009 Nt=1 TF=1 maxTF=1 @{0 1361 2}
airborn -> term4839 Nt=1 TF=1 maxTF=1 @{0 1364 2}
aircraft -> term3761 Nt=1 TF=1 maxTF=1 @{0 1367 2}
ajax -> term3533 Nt=2 TF=2 maxTF=1 @{0 1370 2}
akwukwo -> term3853 Nt=1 TF=1 maxTF=1 @{0 1376 0}
al -> term703 Nt=4 TF=5 maxTF=2 @{0 1379 0}
ala -> term3081 Nt=5 TF=5 maxTF=1 @{0 1387 3}
alamo -> term1737 Nt=1 TF=1 maxTF=1 @{0 1398 3}
alert -> term618 Nt=1 TF=1 maxTF=1 @{0 1400 7}
alexandria -> term3640 Nt=2 TF=2 maxTF=1 @{0 1402 7}
alexandrian -> term3692 Nt=1 TF=1 maxTF=1 @{0 1408 5}
alexandrina -> term4223 Nt=1 TF=1 maxTF=1 @{0 1411 5}
alexandrinu -> term4772 Nt=1 TF=1 maxTF=1 @{0 1414 5}
algal -> term1719 Nt=1 TF=1 maxTF=1 @{0 1417 5}
algebra -> term1698 Nt=1 TF=1 maxTF=1 @{0 1420 1}
algorithm -> term41 Nt=72 TF=73 maxTF=2 @{0 1422 5}
algorithmen -> term2006 Nt=3 TF=3 maxTF=1 @{0 1505 4}
algoritm -> term4998 Nt=1 TF=1 maxTF=1 @{0 1512 0}
alic -> term3177 Nt=1 TF=1 maxTF=1 @{0 1515 0}
align -> term370 Nt=9 TF=9 maxTF=1 @{0 1517 6}
all -> term3787 Nt=1 TF=1 maxTF=1 @{0 1536 0}
alla -> term3726 Nt=2 TF=2 maxTF=1 @{0 1539 0}
allama -> term3659 Nt=1 TF=1 maxTF=1 @{0 1544 4}
allgemein -> term4826 Nt=2 TF=2 maxTF=1 @{0 1547 4}
allianc -> term4073 Nt=1 TF=1 maxTF=1 @{0 1552 0}
alloc -> term3764 Nt=1 TF=1 maxTF=1 @{0 1555 0}
allow -> term977 Nt=2 TF=2 maxTF=1 @{0 1558 0}
alltheweb -> term4306 Nt=1 TF=1 maxTF=1 @{0 1563 0}
alon -> term1313 Nt=2 TF=2 maxTF=1 @{0 1566 0}
alpha -> term728 Nt=1 TF=1 maxTF=1 @{0 1571 2}
alphab -> term4768 Nt=1 TF=1 maxTF=1 @{0 1573 2}
alphafold -> term509 Nt=1 TF=1 maxTF=1 @{0 1576 2}
alphamissens -> term1452 Nt=1 TF=1 maxTF=1 @{0 1578 2}
alten -> term4921 Nt=1 TF=1 maxTF=1 @{0 1580 6}
altern -> term1008 Nt=6 TF=6 maxTF=1 @{0 1583 6}
altmann -> term2531 Nt=1 TF=1 maxTF=1 @{0 1597 0}
altregistratur -> term4405 Nt=1 TF=1 maxTF=1 @{0 1599 6}
altsiedellandschaft -> term5021 Nt=1 TF=1 maxTF=1 @{0 1602 6}
alzheim -> term1580 Nt=1 TF=1 maxTF=1 @{0 1605 6}
am -> term4359 Nt=2 TF=2 maxTF=1 @{0 1608 2}
amass -> term4528 Nt=2 TF=2 maxTF=1 @{0 1613 6}
amaz -> term3015 Nt=1 TF=1 maxTF=1 @{0 1618 2}
ambigu -> term1596 Nt=1 TF=1 maxTF=1 @{0 1621 0}
america -> term3114 Nt=2 TF=2 maxTF=1 @{0 1623 4}
american -> term2830 Nt=9 TF=9 maxTF=1 @{0 1628 6}
amg -> term3712 Nt=1 TF=1 maxTF=1 @{0 1646 4}
amga -> term5003 Nt=1 TF=1 maxTF=1 @{0 1649 4}
amgcl -> term3710 Nt=1 TF=1 maxTF=1 @{0 1652 4}
amh -> term4543 Nt=1 TF=1 maxTF=1 @{0 1655 4}
amino -> term1332 Nt=1 TF=1 maxTF=1 @{0 1658 4}
aminobutyr -> term1477 Nt=1 TF=1 maxTF=1 @{0 1661 0}
amr -> term2328 Nt=1 TF=1 maxTF=1 @{0 1663 4}
amsterdam -> term3107 Nt=1 TF=1 maxTF=1 @{0 1666 2}
analog -> term3887 Nt=2 TF=2 maxTF=1 @{0 1669 0}
analys -> term32 Nt=6 TF=6 maxTF=1 @{0 1674 4}
analysi -> term13 Nt=139 TF=141 maxTF=2 @{0 1685 6}
analysieren -> term2676 Nt=1 TF=1 maxTF=1 @{0 1841 0}
analyst -> term2028 Nt=1 TF=1 maxTF=1 @{0 1843 6}
analyt -> term1059 Nt=15 TF=15 maxTF=1 @{0 1846 2}
analyz -> term1334 Nt=12 TF=12 maxTF=1 @{0 1873 4}
anambra -> term930 Nt=1 TF=1 maxTF=1 @{0 1896 2}
anaphora -> term1922 Nt=1 TF=1 maxTF=1 @{0 1898 4}
anatomi -> term2236 Nt=1 TF=1 maxTF=1 @{0 1901 0}
ancestri -> term1612 Nt=1 TF=1 maxTF=1 @{0 1903 6}
anchor -> term2106 Nt=5 TF=5 maxTF=1 @{0 1906 2}
ancient -> term1561 Nt=2 TF=2 maxTF=1 @{0 1915 6}
anderen -> term4021 Nt=1 TF=1 maxTF=1 @{0 1921 2}
andexperiment -> term3514 Nt=1 TF=1 maxTF=1 @{0 1924 2}
andrei -> term4326 Nt=1 TF=1 maxTF=1 @{0 1927 2}
android -> term2275 Nt=3 TF=3 maxTF=1 @{0 1930 2}
anemia -> term1613 Nt=1 TF=1 maxTF=1 @{0 1938 2}
anerbc -> term1616 Nt=1 TF=1 maxTF=1 @{0 1940 6}
aneurysm -> term1066 Nt=1 TF=1 maxTF=1 @{0 1943 2}
angebot -> term4058 Nt=1 TF=1 maxTF=1 @{0 1945 4}
angl -> term3740 Nt=1 TF=1 maxTF=1 @{0 1948 4}
ani -> term4413 Nt=1 TF=1 maxTF=1 @{0 1951 4}
anim -> term756 Nt=6 TF=6 maxTF=1 @{0 1954 4}
annif -> term2747 Nt=1 TF=1 maxTF=1 @{0 1967 2}
annot -> term69 Nt=45 TF=45 maxTF=1 @{0 1970 0}
annual -> term1601 Nt=3 TF=3 maxTF=1 @{0 2030 4}
ano -> term3849 Nt=1 TF=1 maxTF=1 @{0 2037 0}
anpassbarkeit -> term4904 Nt=1 TF=1 maxTF=1 @{0 2040 0}
answer -> term1216 Nt=9 TF=10 maxTF=2 @{0 2043 0}
antaeu -> term3507 Nt=1 TF=1 maxTF=1 @{0 2060 3}
anthropolog -> term5007 Nt=1 TF=1 maxTF=1 @{0 2063 3}
anthropologist -> term3609 Nt=1 TF=1 maxTF=1 @{0 2066 3}
anti -> term278 Nt=3 TF=3 maxTF=1 @{0 2069 3}
antibiot -> term1331 Nt=1 TF=1 maxTF=1 @{0 2076 3}
antibodi -> term3325 Nt=2 TF=2 maxTF=1 @{0 2078 7}
anticanc -> term602 Nt=1 TF=1 maxTF=1 @{0 2084 1}
antigen -> term3322 Nt=1 TF=1 maxTF=1 @{0 2086 1}
antik -> term2190 Nt=1 TF=1 maxTF=1 @{0 2089 1}
antimicrobi -> term292 Nt=4 TF=4 maxTF=1 @{0 2091 7}
antiqu -> term3689 Nt=2 TF=2 maxTF=1 @{0 2099 5}
anwendungen -> term1848 Nt=1 TF=1 maxTF=1 @{0 2105 1}
anxieti -> term3658 Nt=1 TF=1 maxTF=1 @{0 2107 5}
aop -> term3273 Nt=1 TF=1 maxTF=1 @{0 2110 5}
aortic -> term1307 Nt=1 TF=1 maxTF=1 @{0 2113 3}
ap -> term4139 Nt=1 TF=1 maxTF=1 @{0 2115 5}
apach -> term1053 Nt=1 TF=1 maxTF=1 @{0 2118 5}
apachebench -> term4830 Nt=2 TF=2 maxTF=1 @{0 2120 7}
apadb -> term1809 Nt=1 TF=1 maxTF=1 @{0 2125 3}
apd -> term1948 Nt=1 TF=1 maxTF=1 @{0 2127 7}
api -> term1490 Nt=4 TF=5 maxTF=2 @{0 2130 3}
apollo -> term4194 Nt=1 TF=1 maxTF=1 @{0 2138 6}
apostolico -> term4168 Nt=1 TF=1 maxTF=1 @{0 2141 6}
app -> term1800 Nt=5 TF=6 maxTF=2 @{0 2144 6}
append -> term4962 Nt=1 TF=1 maxTF=1 @{0 2156 3}
appli -> term1629 Nt=6 TF=6 maxTF=1 @{0 2159 3}
applic -> term33 Nt=61 TF=61 maxTF=1 @{0 2171 1}
apprais -> term1488 Nt=3 TF=3 maxTF=1 @{0 2250 7}
appreci -> term2781 Nt=1 TF=1 maxTF=1 @{0 2257 1}
apprentic -> term3457 Nt=1 TF=1 maxTF=1 @{0 2259 7}
approach -> term656 Nt=78 TF=78 maxTF=1 @{0 2262 7}
approxim -> term2699 Nt=3 TF=3 maxTF=1 @{0 2363 5}
april -> term2905 Nt=1 TF=1 maxTF=1 @{0 2371 3}
aptam -> term386 Nt=1 TF=1 maxTF=1 @{0 2374 1}
aquat -> term4791 Nt=1 TF=1 maxTF=1 @{0 2375 7}
aqueou -> term460 Nt=1 TF=1 maxTF=1 @{0 2378 7}
ar -> term4520 Nt=1 TF=1 maxTF=1 @{0 2380 7}
arab -> term2095 Nt=4 TF=4 maxTF=1 @{0 2383 7}
arabidopsi -> term246 Nt=2 TF=2 maxTF=1 @{0 2392 7}
aral -> term4310 Nt=1 TF=1 maxTF=1 @{0 2396 3}
arbitrari -> term2588 Nt=1 TF=1 maxTF=1 @{0 2399 3}
arbitrarili -> term2050 Nt=1 TF=1 maxTF=1 @{0 2402 1}
arc -> term2285 Nt=2 TF=2 maxTF=1 @{0 2404 5}
arch -> term4629 Nt=1 TF=1 maxTF=1 @{0 2410 3}
arch2 -> term4924 Nt=1 TF=1 maxTF=1 @{0 2413 3}
archaeogam -> term4435 Nt=1 TF=1 maxTF=1 @{0 2416 3}
archaeolog -> term4007 Nt=2 TF=2 maxTF=1 @{0 2419 3}
archetyp -> term4763 Nt=1 TF=1 maxTF=1 @{0 2424 7}
archi -> term1662 Nt=1 TF=1 maxTF=1 @{0 2427 7}
archimed -> term4319 Nt=2 TF=2 maxTF=1 @{0 2430 3}
architectur -> term1101 Nt=28 TF=28 maxTF=1 @{0 2435 7}
archiv -> term777 Nt=857 TF=893 maxTF=4 @{0 2479 7}
archivdienst -> term4388 Nt=1 TF=1 maxTF=1 @{0 2733 5}
archivefilm -> term4741 Nt=1 TF=1 maxTF=1 @{0 2736 5}
archiven -> term4112 Nt=1 TF=1 maxTF=1 @{0 2739 5}
archivenow -> term4305 Nt=1 TF=1 maxTF=1 @{0 2742 5}
archivespark -> term4055 Nt=3 TF=3 maxTF=1 @{0 2745 5}
archiveweb -> term4068 Nt=5 TF=5 maxTF=1 @{0 2752 1}
archivio -> term4172 Nt=2 TF=2 maxTF=1 @{0 2760 3}
archivist -> term4075 Nt=1 TF=1 maxTF=1 @{0 2765 5}
archivo -> term4498 Nt=2 TF=2 maxTF=1 @{0 2768 5}
archivportal -> term4056 Nt=1 TF=1 maxTF=1 @{0 2773 7}
archivschul -> term4385 Nt=1 TF=1 maxTF=1 @{0 2776 7}
arcp -> term4449 Nt=1 TF=1 maxTF=1 @{0 2779 7}
ardo -> term4781 Nt=2 TF=2 maxTF=1 @{0 2782 7}
arduino -> term736 Nt=2 TF=2 maxTF=1 @{0 2786 3}
area -> term1259 Nt=4 TF=4 maxTF=1 @{0 2790 7}
aren -> term2532 Nt=2 TF=2 maxTF=1 @{0 2801 1}
argania -> term709 Nt=1 TF=1 maxTF=1 @{0 2806 5}
argonaut -> term130 Nt=2 TF=2 maxTF=1 @{0 2808 5}
arhiva -> term4082 Nt=2 TF=2 maxTF=1 @{0 2811 5}
arhivu -> term4638 Nt=2 TF=2 maxTF=1 @{0 2817 1}
aristotl -> term3368 Nt=1 TF=1 maxTF=1 @{0 2821 1}
arithmet -> term2129 Nt=1 TF=1 maxTF=1 @{0 2824 1}
arizona -> term3237 Nt=1 TF=1 maxTF=1 @{0 2826 7}
armstrong -> term3252 Nt=1 TF=1 maxTF=1 @{0 2829 5}
arno -> term2246 Nt=1 TF=1 maxTF=1 @{0 2832 3}
aromadeg -> term1954 Nt=1 TF=1 maxTF=1 @{0 2835 1}
aromat -> term1952 Nt=1 TF=1 maxTF=1 @{0 2837 5}
arrai -> term1500 Nt=2 TF=2 maxTF=1 @{0 2840 1}
arrang -> term3914 Nt=1 TF=1 maxTF=1 @{0 2844 5}
arrayexpress -> term1692 Nt=1 TF=1 maxTF=1 @{0 2847 5}
art -> term2182 Nt=16 TF=16 maxTF=1 @{0 2850 1}
artdoc -> term4851 Nt=1 TF=1 maxTF=1 @{0 2879 7}
arteri -> term2030 Nt=1 TF=1 maxTF=1 @{0 2882 7}
articl -> term1539 Nt=13 TF=14 maxTF=2 @{0 2885 3}
artifact -> term4296 Nt=2 TF=2 maxTF=1 @{0 2911 6}
artifici -> term1589 Nt=6 TF=6 maxTF=1 @{0 2916 4}
artist -> term2661 Nt=8 TF=8 maxTF=1 @{0 2930 6}
aruba -> term3590 Nt=1 TF=1 maxTF=1 @{0 2945 2}
ascertain -> term443 Nt=1 TF=1 maxTF=1 @{0 2948 2}
ascii -> term2452 Nt=1 TF=1 maxTF=1 @{0 2950 0}
ascla -> term3409 Nt=1 TF=1 maxTF=1 @{0 2952 6}
ashra -> term3049 Nt=1 TF=1 maxTF=1 @{0 2955 6}
asia -> term4333 Nt=1 TF=1 maxTF=1 @{0 2958 4}
asian -> term1680 Nt=2 TF=2 maxTF=1 @{0 2961 4}
ask -> term2038 Nt=1 TF=1 maxTF=1 @{0 2966 6}
aspect -> term1628 Nt=5 TF=5 maxTF=1 @{0 2969 2}
aspekt -> term2270 Nt=1 TF=1 maxTF=1 @{0 2981 2}
assai -> term1889 Nt=1 TF=1 maxTF=1 @{0 2984 0}
assembl -> term283 Nt=2 TF=2 maxTF=1 @{0 2986 4}
assess -> term1236 Nt=17 TF=17 maxTF=1 @{0 2991 2}
assign -> term2664 Nt=1 TF=1 maxTF=1 @{0 3022 0}
assist -> term1956 Nt=9 TF=10 maxTF=2 @{0 3024 6}
associ -> term139 Nt=33 TF=33 maxTF=1 @{0 3042 7}
asssrdb -> term711 Nt=1 TF=1 maxTF=1 @{0 3090 1}
assumpt -> term58 Nt=1 TF=1 maxTF=1 @{0 3092 1}
astrocyt -> term1708 Nt=1 TF=1 maxTF=1 @{0 3093 1}
astronom -> term4966 Nt=1 TF=1 maxTF=1 @{0 3095 5}
astronomi -> term3568 Nt=2 TF=2 maxTF=1 @{0 3098 5}
astrophys -> term2843 Nt=1 TF=1 maxTF=1 @{0 3104 1}
atc -> term1404 Nt=1 TF=1 maxTF=1 @{0 3106 7}
atena -> term4794 Nt=1 TF=1 maxTF=1 @{0 3109 3}
athen -> term3311 Nt=7 TF=7 maxTF=1 @{0 3112 3}
athena -> term1102 Nt=1 TF=1 maxTF=1 @{0 3123 7}
athenaeum -> term4827 Nt=2 TF=2 maxTF=1 @{0 3126 1}
atherosclerot -> term1552 Nt=1 TF=1 maxTF=1 @{0 3130 5}
athisomirdb -> term247 Nt=1 TF=1 maxTF=1 @{0 3133 1}
athribonc -> term473 Nt=1 TF=1 maxTF=1 @{0 3134 7}
atla -> term287 Nt=5 TF=5 maxTF=1 @{0 3136 7}
atm23 -> term4348 Nt=1 TF=1 maxTF=1 @{0 3147 3}
atmospher -> term3147 Nt=2 TF=2 maxTF=1 @{0 3150 3}
atomist -> term882 Nt=1 TF=1 maxTF=1 @{0 3155 7}
att -> term2963 Nt=2 TF=2 maxTF=1 @{0 3158 1}
attack -> term884 Nt=2 TF=2 maxTF=1 @{0 3163 3}
attend -> term739 Nt=2 TF=2 maxTF=1 @{0 3168 3}
attent -> term2493 Nt=3 TF=3 maxTF=1 @{0 3173 1}
attitud -> term3271 Nt=3 TF=3 maxTF=1 @{0 3179 5}
attribut -> term2539 Nt=2 TF=2 maxTF=1 @{0 3185 5}
au -> term3911 Nt=3 TF=3 maxTF=1 @{0 3189 7}
auc -> term2214 Nt=1 TF=1 maxTF=1 @{0 3197 1}

In [23]:
term_freq_dict = {}

for kv in index.getLexicon():
    term_freq_dict[kv.getKey()] = kv.getValue().frequency

In [25]:
term_freq_dict_sorted = sorted(term_freq_dict.items(), key=lambda x: x[1], reverse=True)

In [27]:
top_k = 30
term_freq_dict_sorted[:top_k]

[('librari', 981),
 ('archiv', 893),
 ('databas', 824),
 ('text', 824),
 ('data', 252),
 ('system', 239),
 ('base', 234),
 ('web', 200),
 ('digit', 179),
 ('us', 171),
 ('analysi', 141),
 ('model', 141),
 ('mine', 130),
 ('classif', 122),
 ('research', 115),
 ('servic', 111),
 ('manag', 109),
 ('green', 100),
 ('new', 99),
 ('sustain', 99),
 ('learn', 92),
 ('semant', 85),
 ('studi', 85),
 ('design', 84),
 ('network', 80),
 ('approach', 78),
 ('integr', 77),
 ('resourc', 76),
 ('search', 76),
 ('gener', 75)]

In [29]:
search_engine = pt.BatchRetrieve(index, wmodel="Tf")

/var/folders/88/9blsh45918g8y3n5vl6vztxr0000gq/T/ipykernel_1707/951663741.py:1: DeprecationWarning: Call to deprecated class BatchRetrieve. (use pt.terrier.Retriever() instead) -- Deprecated since version 0.11.0.
  search_engine = pt.BatchRetrieve(index, wmodel="Tf")

In [31]:
search_engine.search("system")

,qid,docid,docno,rank,score,query
0,1,775,https://www.bibsonomy.org/bibtex/27cebe02af1e4...,0,2.0,system
1,1,791,https://www.bibsonomy.org/bibtex/2e8737a4cce47...,1,2.0,system
2,1,794,https://www.bibsonomy.org/bibtex/2072b030962e3...,2,2.0,system
3,1,1568,https://www.bibsonomy.org/bibtex/280f75bb46fcb...,3,2.0,system
4,1,17,https://www.bibsonomy.org/bibtex/28af31bbdb0bd...,4,1.0,system
...,...,...,...,...,...,...
230,1,3472,https://www.bibsonomy.org/bibtex/2ae6a916923ad...,230,1.0,system
231,1,3489,https://www.bibsonomy.org/bibtex/2390b02f23f3d...,231,1.0,system
232,1,3494,https://www.bibsonomy.org/bibtex/25d3f12c5e0f6...,232,1.0,system
233,1,3495,https://www.bibsonomy.org/bibtex/270a5cfbabcbb...,233,1.0,system
234,1,3511,https://www.bibsonomy.org/bibtex/25926f6dbad9b...,234,1.0,system

In [33]:
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()

In [35]:
stem = stemmer.stem("learning")
stem

'learn'

In [37]:
lexicon = index.getLexicon()
lexicon[stem].getDocumentFrequency()

90

In [39]:
index.getCollectionStatistics().numberOfDocuments

3520

In [41]:
def get_idf_for_term(term, index):
  lex = index.getLexicon()
  stemmed_term = stemmer.stem(term)

  if not stemmed_term in lex:
    return 
    
  lex_entry = lex[stemmed_term]

  df_term = lex_entry.getDocumentFrequency()
  N = index.getCollectionStatistics().numberOfDocuments
  
  #inverse document frequency
  idf = N/df_term

  #apply logarithm(base 10) to idf
  log_idf = np.emath.logn(10, idf)

  return log_idf

In [43]:
get_idf_for_term("learning", index)

1.592300154038806

In [45]:
#define your own tf_idf method here:

def calc_tf_idf(query, docno, index):
    #remember that tfidf is the product of two components
    #hint: the tf model search result contains tf frequencies
    return 0

In [47]:
search_engine_tfidf = pt.BatchRetrieve(index, wmodel="TF_IDF")

/var/folders/88/9blsh45918g8y3n5vl6vztxr0000gq/T/ipykernel_1707/2880449899.py:1: DeprecationWarning: Call to deprecated class BatchRetrieve. (use pt.terrier.Retriever() instead) -- Deprecated since version 0.11.0.
  search_engine_tfidf = pt.BatchRetrieve(index, wmodel="TF_IDF")

In [49]:
search_engine_tfidf.search("database")

,qid,docid,docno,rank,score,query
0,1,7,https://www.bibsonomy.org/bibtex/2b8151c596a8d...,0,2.087840,database
1,1,716,https://www.bibsonomy.org/bibtex/25802e079a691...,1,2.060145,database
2,1,29,https://www.bibsonomy.org/bibtex/292e537486422...,2,1.995273,database
3,1,237,https://www.bibsonomy.org/bibtex/2949b00f83f34...,3,1.995273,database
4,1,353,https://www.bibsonomy.org/bibtex/2baef7a8d376b...,4,1.995273,database
...,...,...,...,...,...,...
779,1,907,https://www.bibsonomy.org/bibtex/2f43d9d72eae5...,779,0.902869,database
780,1,297,https://www.bibsonomy.org/bibtex/2170909f0b219...,780,0.868039,database
781,1,420,https://www.bibsonomy.org/bibtex/25fbb861f86f5...,781,0.868039,database
782,1,214,https://www.bibsonomy.org/bibtex/2251c59300d5d...,782,0.835797,database
783,1,2307,https://www.bibsonomy.org/bibtex/28edcbb8e3073...,783,0.835797,database

In [51]:
# Index with multiple fields
df_dict = df_filtered.to_dict(orient='records')

In [53]:
df_dict

[{'title': 'EcoliNet: a database of cofunctional gene network for Escherichia coli.',
  'id': 'https://www.bibsonomy.org/bibtex/2750b8770eec83ca7d18107df3d520113/karthikraman',
  'type': 'Publication',
  'url': 'http://dx.doi.org/10.1093/database/bav001',
  'year': 2015,
  'authors': ['Hanhae Kim', 'Jung Eun E. Shim', 'Junha Shin', 'Insuk Lee'],
  'doi': '10.1093/database/bav001',
  'query': 'database',
  'editor': 'Jannik Ott',
  'docno': 'https://www.bibsonomy.org/bibtex/2750b8770eec83ca7d18107df3d520113/karthikraman',
  'text': 'EcoliNet: a database of cofunctional gene network for Escherichia coli.'},
 {'title': 'The drug-minded protein interaction database (DrumPID) for efficient target analysis and drug development.',
  'id': 'https://www.bibsonomy.org/bibtex/2d93ac9b6cfa60505ee7b3d7ffefca15f/karthikraman',
  'type': 'Publication',
  'url': 'http://dx.doi.org/10.1093/database/baw041',
  'year': 2016,
  'authors': ['Meik Kunz',
   'Chunguang Liang',
   'Santosh Nilla',
   'Alexander Cecil',
   'Thomas Dandekar'],
  'doi': '10.1093/database/baw041',
  'query': 'database',
  'editor': 'Jannik Ott',
  'docno': 'https://www.bibsonomy.org/bibtex/2d93ac9b6cfa60505ee7b3d7ffefca15f/karthikraman',
  'text': 'The drug-minded protein interaction database (DrumPID) for efficient target analysis and drug development.'},
 {'title': 'PhosphoGRID: a database of experimentally verified in vivo protein phosphorylation sites from the budding yeast Saccharomyces cerevisiae.',
  'id': 'https://www.bibsonomy.org/bibtex/233d3effaf95a6d714a6fb06099bdf647/karthikraman',
  'type': 'Publication',
  'url': 'http://dx.doi.org/10.1093/database/bap026',
  'year': 2010,
  'authors': ['Chris Stark',
   'Ting-Cheng C. Su',
   'Ashton Breitkreutz',
   'Pedro Lourenco',
   'Matthew Dahabieh',
   'Bobby-Joe J. Breitkreutz',
   'Mike Tyers',
   'Ivan Sadowski'],
  'doi': '10.1093/database/bap026',
  'query': 'database',
  'editor': 'Jannik Ott',
  'docno': 'https://www.bibsonomy.org/bibtex/233d3effaf95a6d714a6fb06099bdf647/karthikraman',
  'text': 'PhosphoGRID: a database of experimentally verified in vivo protein phosphorylation sites from the budding yeast Saccharomyces cerevisiae.'},
 {'title': 'GoSynthetic database tool to analyse natural and engineered molecular processes',
  'id': 'https://www.bibsonomy.org/bibtex/2ca6461cce248858567237c85cca8f378/evp66rk',
  'type': 'Publication',
  'url': 'http://dx.doi.org/10.1093/database/bat043',
  'year': 2013,
  'authors': ['C. Liang', 'B. Kruger', 'T. Dandekar'],
  'doi': '10.1093/database/bat043',
  'query': 'database',
  'editor': 'Jannik Ott',
  'docno': 'https://www.bibsonomy.org/bibtex/2ca6461cce248858567237c85cca8f378/evp66rk',
  'text': 'GoSynthetic database tool to analyse natural and engineered molecular processes'},
 {'title': 'Database for Mobile Application',
  'id': 'https://www.bibsonomy.org/bibtex/2eb1605409b134cc14adb1c45bc1bd3b0/ijtsrd',
  'type': 'Publication',
  'url': 'http://www.ijtsrd.com/computer-science/database/11215/database-for-mobile-application/jasra-nisar',
  'year': 2018,
  'authors': ['Jasra Nisar Owais Noor Trumboo'],
  'doi': None,
  'query': 'database',
  'editor': 'Jannik Ott',
  'docno': 'https://www.bibsonomy.org/bibtex/2eb1605409b134cc14adb1c45bc1bd3b0/ijtsrd',
  'text': 'Database for Mobile Application'},
 {'title': 'An international otology database',
  'id': 'https://www.bibsonomy.org/bibtex/25f85238089c4a2ec183b243bf83fa523/stevenarild',
  'type': 'Publication',
  'url': 'http://www.ncbi.nlm.nih.gov.ep.fjernadgang.kb.dk/pubmed/?term=yung+gjuric+haeusler',
  'year': 2005,
  'authors': ['M Yung',
   'M Gjuric',
   'R Haeusler',
   'P H Van de Heyning',
   'C Martin',
   'I R Swan',
   'R A Tange',
   'P T Huy',
   ' European Otology Database Project Group'],
  'doi': None,
  'query': 'database',
  'editor': 'Jannik Ott',
  'docno': 'https://www.bibsonomy.org/bibtex/25f85238089c4a2ec183b243bf83fa523/stevenarild',
  'text': 'An international otology database'},
 {'title': 'Enable Auditing in Oracle database',
  'id': 'https://www.bibsonomy.org/bibtex/27757584ce817952545d28d956896ba6a/ijtsrd',
  'type': 'Publication',
  'url': 'https://www.ijtsrd.com/computer-science/database/29881/enable-auditing-in-oracle-database/amrish-srivastava',
  'year': 2019,
  'authors': ['Amrish Srivastava'],
  'doi': None,
  'query': 'database',
  'editor': 'Jannik Ott',
  'docno': 'https://www.bibsonomy.org/bibtex/27757584ce817952545d28d956896ba6a/ijtsrd',
  'text': 'Enable Auditing in Oracle database'},
 {'title': 'Database and database application security',
  'id': 'https://www.bibsonomy.org/bibtex/2b8151c596a8d3eb7e7233f1a47d53b08/malte.wunsch',
  'type': 'Publication',
  'url': 'http://portal.acm.org/citation.cfm?id=1562877.1562909',
  'year': 2009,
  'authors': ['Huwida E. Said',
   'Mario A. Guimaraes',
   'Zakaria Maamar',
   'Leon Jololian'],
  'doi': None,
  'query': 'database',
  'editor': 'Jannik Ott',
  'docno': 'https://www.bibsonomy.org/bibtex/2b8151c596a8d3eb7e7233f1a47d53b08/malte.wunsch',
  'text': 'Database and database application security'},
 {'title': 'Vertical partitioning algorithms for database design',
  'id': 'https://www.bibsonomy.org/bibtex/281eb5e7b67cc969365c65a67721cb495/joergh',
  'type': 'Publication',
  'url': 'http://portal.acm.org/citation.cfm?id=1994.2209',
  'year': 1984,
  'authors': ['Shamkant Navathe',
   'Stefano Ceri',
   'Gio Wiederhold',
   'Jinglie Dou'],
  'doi': 'http://doi.acm.org/10.1145/1994.2209',
  'query': 'database',
  'editor': 'Jannik Ott',
  'docno': 'https://www.bibsonomy.org/bibtex/281eb5e7b67cc969365c65a67721cb495/joergh',
  'text': 'Vertical partitioning algorithms for database design'},
 {'title': 'The Reactome BioMart.',
  'id': 'https://www.bibsonomy.org/bibtex/206ba5aaa99967712038c684d1864c421/karthikraman',
  'type': 'Publication',
  'url': 'http://dx.doi.org/10.1093/database/bar031',
  'year': 2011,
  'authors': ['Robin A. Haw',
   'David Croft',
   'Christina K. Yung',
   'Nelson Ndegwa',
   "Peter D'Eustachio",
   'Henning Hermjakob',
   'Lincoln D. Stein'],
  'doi': '10.1093/database/bar031',
  'query': 'database',
  'editor': 'Jannik Ott',
  'docno': 'https://www.bibsonomy.org/bibtex/206ba5aaa99967712038c684d1864c421/karthikraman',
  'text': 'The Reactome BioMart.'},
 {'title': 'WholeCellSimDB: a hybrid relational/HDF database for whole-cell model predictions.',
  'id': 'https://www.bibsonomy.org/bibtex/235a7f0439923ab61281f80bb4fbe77c9/karthikraman',
  'type': 'Publication',
  'url': 'http://dx.doi.org/10.1093/database/bau095',
  'year': 2014,
  'authors': ['Jonathan R. Karr', 'Nolan C. Phillips', 'Markus W. Covert'],
  'doi': '10.1093/database/bau095',
  'query': 'database',
  'editor': 'Jannik Ott',
  'docno': 'https://www.bibsonomy.org/bibtex/235a7f0439923ab61281f80bb4fbe77c9/karthikraman',
  'text': 'WholeCellSimDB: a hybrid relational/HDF database for whole-cell model predictions.'},
 {'title': 'Oracle Database Backup Testing',
  'id': 'https://www.bibsonomy.org/bibtex/23300b9d02e6150493d24278d652fd980/ijtsrd',
  'type': 'Publication',
  'url': 'http://www.ijtsrd.com/computer-science/database/11572/oracle-database-backup-testing/vijay-kumar-tiwari',
  'year': 2018,
  'authors': ['Vijay Kumar Tiwari'],
  'doi': None,
  'query': 'database',
  'editor': 'Jannik Ott',
  'docno': 'https://www.bibsonomy.org/bibtex/23300b9d02e6150493d24278d652fd980/ijtsrd',
  'text': 'Oracle Database Backup Testing'},
 {'title': 'Implications of certain assumptions in database performance evauation',
  'id': 'https://www.bibsonomy.org/bibtex/2a8e950024e05fb6206578bb5a3c4d44a/jhammerb',
  'type': 'Publication',
  'url': 'http://portal.acm.org/citation.cfm?doid=329.318578',
  'year': 1984,
  'authors': ['S. Christodoulakis'],
  'doi': 'http://doi.acm.org/10.1145/329.318578',
  'query': 'database',
  'editor': 'Jannik Ott',
  'docno': 'https://www.bibsonomy.org/bibtex/2a8e950024e05fb6206578bb5a3c4d44a/jhammerb',
  'text': 'Implications of certain assumptions in database performance evauation'},
 {'title': 'A standardized database management of middle ear surgery in Korea',
  'id': 'https://www.bibsonomy.org/bibtex/24d001da0c68be5efe71702f9ecc2e4f2/stevenarild',
  'type': 'Publication',
  'url': 'http://www.ncbi.nlm.nih.gov.ep.fjernadgang.kb.dk/pubmed/?term=kim+hj+a+standardized+database+management',
  'year': 2007,
  'authors': ['H J Kim'],
  'doi': '10.1080/03655230701624871',
  'query': 'database',
  'editor': 'Jannik Ott',
  'docno': 'https://www.bibsonomy.org/bibtex/24d001da0c68be5efe71702f9ecc2e4f2/stevenarild',
  'text': 'A standardized database management of middle ear surgery in Korea'},
 {'title': 'SwissRegulon, a database of genome-wide annotations of regulatory sites: recent updates',
  'id': 'https://www.bibsonomy.org/bibtex/2e15360b1fc6345c1913a65b3112680fd/karthikraman',
  'type': 'Publication',
  'url': 'https://www.ncbi.nlm.nih.gov/pubmed/?term=SwissRegulon%2C+a+database+of+genome-wide+annotations+of+regulatory+sites%3A+recent+updates',
  'year': 2013,
  'authors': ['M Pachkov',
   'P J Balwierz',
   'P Arnold',
   'E Ozonov',
   'E van Nimwegen'],
  'doi': '10.1093/nar/gks1145',
  'query': 'database',
  'editor': 'Jannik Ott',
  'docno': 'https://www.bibsonomy.org/bibtex/2e15360b1fc6345c1913a65b3112680fd/karthikraman',
  'text': 'SwissRegulon, a database of genome-wide annotations of regulatory sites: recent updates'},
 {'title': 'ConsensusPathDB--a database for integrating human functional interaction networks',
  'id': 'https://www.bibsonomy.org/bibtex/22b7406cd1753f56e5a06ae8b48b24cdf/wnpxrz',
  'type': 'Publication',
  'url': 'http://www.ncbi.nlm.nih.gov/pubmed/18940869',
  'year': 2009,
  'authors': ['A Kamburov', 'C Wierling', 'H Lehrach', 'R Herwig'],
  'doi': '10.1093/nar/gkn698',
  'query': 'database',
  'editor': 'Jannik Ott',
  'docno': 'https://www.bibsonomy.org/bibtex/22b7406cd1753f56e5a06ae8b48b24cdf/wnpxrz',
  'text': 'ConsensusPathDB--a database for integrating human functional interaction networks'},
 {'title': 'PID: the Pathway Interaction Database',
  'id': 'https://www.bibsonomy.org/bibtex/250055d426be1ad08439d9523ae3c83d1/wnpxrz',
  'type': 'Publication',
  'url': 'http://www.ncbi.nlm.nih.gov/pubmed/18832364',
  'year': 2009,
  'authors': ['C F Schaefer',
   'K Anthony',
   'S Krupa',
   'J Buchoff',
   'M Day',
   'T Hannay',
   'K H Buetow'],
  'doi': '10.1093/nar/gkn653',
  'query': 'database',
  'editor': 'Jannik Ott',
  'docno': 'https://www.bibsonomy.org/bibtex/250055d426be1ad08439d9523ae3c83d1/wnpxrz',
  'text': 'PID: the Pathway Interaction Database'},
 {'title': 'Parallel database systems: the future of database processing or a passing fad?',
  'id': 'https://www.bibsonomy.org/bibtex/28af31bbdb0bde12ef6965492973f4831/jhammerb',
  'type': 'Publication',
  'url': 'http://portal.acm.org/citation.cfm?id=122058.122071',
  'year': 1990,
  'authors': ['David J. DeWitt', 'Jim Gray'],
  'doi': 'http://doi.acm.org/10.1145/122058.122071',
  'query': 'database',
  'editor': 'Jannik Ott',
  'docno': 'https://www.bibsonomy.org/bibtex/28af31bbdb0bde12ef6965492973f4831/jhammerb',
  'text': 'Parallel database systems: the future of database processing or a passing fad?'},
 {'title': 'The HUGO Gene Nomenclature Database, 2006 updates',
  'id': 'https://www.bibsonomy.org/bibtex/29b3aa72d312bf8a3e038ca92b6612fcd/sbsad',
  'type': 'Publication',
  'url': 'http://www.ncbi.nlm.nih.gov/pubmed/16381876',
  'year': 2006,
  'authors': ['T A Eyre',
   'F Ducluzeau',
   'T P Sneddon',
   'S Povey',
   'E A Bruford',
   'M J Lush'],
  'doi': '10.1093/nar/gkj147',
  'query': 'database',
  'editor': 'Jannik Ott',
  'docno': 'https://www.bibsonomy.org/bibtex/29b3aa72d312bf8a3e038ca92b6612fcd/sbsad',
  'text': 'The HUGO Gene Nomenclature Database, 2006 updates'},
 {'title': 'Traditional Databases vs NOSQL',
  'id': 'https://www.bibsonomy.org/bibtex/2a25665734dddc3bd249a981cd424fc74/ijtsrd',
  'type': 'Publication',
  'url': 'http://www.ijtsrd.com/computer-science/database/12961/traditional-databases-vs-nosql/owais-noor-trumboo',
  'year': 2018,
  'authors': ['Owais Noor Trumboo Jasra Nisar'],
  'doi': None,
  'query': 'database',
  'editor': 'Jannik Ott',
  'docno': 'https://www.bibsonomy.org/bibtex/2a25665734dddc3bd249a981cd424fc74/ijtsrd',
  'text': 'Traditional Databases vs NOSQL'},
 {'title': 'Federated database systems for managing distributed, heterogeneous, and autonomous databases',
  'id': 'https://www.bibsonomy.org/bibtex/2d8ab08ff39573bd64e7dc080adb2230b/buehner',
  'type': 'Publication',
  'url': 'http://delivery.acm.org/10.1145/100000/96604/p183-sheth.pdf?key1=96604&key2=8693487821&coll=GUIDE&dl=ACM&CFID=107002774&CFTOKEN=13258373',
  'year': 1990,
  'authors': ['Amit P. Sheth', 'James A. Larson'],
  'doi': '10.1145/96602.96604',
  'query': 'database',
  'editor': 'Jannik Ott',
  'docno': 'https://www.bibsonomy.org/bibtex/2d8ab08ff39573bd64e7dc080adb2230b/buehner',
  'text': 'Federated database systems for managing distributed, heterogeneous, and autonomous databases'},
 {'title': 'Migration from relational database like MySQL to nosql database like Cassandra is necessary and how to migrate it using spark',
  'id': 'https://www.bibsonomy.org/bibtex/2c47aa8b0c0695dbf04c04e34bb3a9101/ijtsrd',
  'type': 'Publication',
  'url': 'http://www.ijtsrd.com/engineering/computer-engineering/57/migration-from-relational-database-like-mysql-to-nosql-database-like-cassandra-is-necessary-and-how-to-migrate-it-using-spark/dr-kishor-atkotiya',
  'year': 2016,
  'authors': ['Dr. Kishor Atkotiya | Parag Shukla'],
  'doi': None,
  'query': 'database',
  'editor': 'Jannik Ott',
  'docno': 'https://www.bibsonomy.org/bibtex/2c47aa8b0c0695dbf04c04e34bb3a9101/ijtsrd',
  'text': 'Migration from relational database like MySQL to nosql database like Cassandra is necessary and how to migrate it using spark'},
 {'title': 'Database Security Model using Access Control Mechanism in Student Data Management',
  'id': 'https://www.bibsonomy.org/bibtex/2f21be0dc285cb90890e1d9ce3146a63a/ijtsrd',
  'type': 'Publication',
  'url': 'https://www.ijtsrd.com/computer-science/database/22820/database-security-model-using-access-control-mechanism-in-student-data-management/aye-mon-win',
  'year': 2019,
  'authors': ['Aye Mon Win | Khin Lay Myint'],
  'doi': 'https://doi.org/10.31142/ijtsrd22820',
  'query': 'database',
  'editor': 'Jannik Ott',
  'docno': 'https://www.bibsonomy.org/bibtex/2f21be0dc285cb90890e1d9ce3146a63a/ijtsrd',
  'text': 'Database Security Model using Access Control Mechanism in Student Data Management'},
 {'title': 'Survival of an Intrusion Tolerance Database System',
  'id': 'https://www.bibsonomy.org/bibtex/24f8b60cb12c7f1d1b31465d7e7b2f44b/ijtsrd',
  'type': 'Publication',
  'url': 'https://www.ijtsrd.com/computer-science/computer-security/26748/survival-of-an-intrusion-tolerance-database-system/su-thawda-win',
  'year': 2019,
  'authors': ['Su Thawda Win'],
  'doi': 'https://doi.org/10.31142/ijtsrd26748',
  'query': 'database',
  'editor': 'Jannik Ott',
  'docno': 'https://www.bibsonomy.org/bibtex/24f8b60cb12c7f1d1b31465d7e7b2f44b/ijtsrd',
  'text': 'Survival of an Intrusion Tolerance Database System'},
 {'title': 'BioNumbers--the database of key numbers in molecular and cell biology',
  'id': 'https://www.bibsonomy.org/bibtex/2c35febbc664422e27257b6f2f27b40f4/karthikraman',
  'type': 'Publication',
  'url': 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2808940/',
  'year': 2010,
  'authors': ['R Milo', 'P Jorgensen', 'U Moran', 'G Weber', 'M Springer'],
  'doi': '10.1093/nar/gkp889',
  'query': 'database',
  'editor': 'Jannik Ott',
  'docno': 'https://www.bibsonomy.org/bibtex/2c35febbc664422e27257b6f2f27b40f4/karthikraman',
  'text': 'BioNumbers--the database of key numbers in molecular and cell biology'},
 {'title': 'Janaushadhi Database Management System',
  'id': 'https://www.bibsonomy.org/bibtex/20900193932683227409336a3befeac54/ijtsrd',
  'type': 'Publication',
  'url': 'https://www.ijtsrd.com/computer-science/database/26403/janaushadhi-database-management-system/naimisha-u',
  'year': 2019,
  'authors': ['Naimisha U | Ashritha A'],
  'doi': 'https://doi.org/10.31142/ijtsrd26403',
  'query': 'database',
  'editor': 'Jannik Ott',
  'docno': 'https://www.bibsonomy.org/bibtex/20900193932683227409336a3befeac54/ijtsrd',
  'text': 'Janaushadhi Database Management System'},
 {'title': 'GAMMA\\—a high performance dataflow database machine',
  'id': 'https://www.bibsonomy.org/bibtex/2a295018d8ecc0212aca487ae1b0c753e/jhammerb',
  'type': 'Publication',
  'url': 'http://portal.acm.org/citation.cfm?id=48751.48773',
  'year': 1988,
  'authors': ['David J. DeWitt',
   'Goetz Graefe',
   'Krishna B. Kumar',
   'Robert H. Gerber',
   'Michael L. Heytens',
   'M. Muralikrishna'],
  'doi': None,
  'query': 'database',
  'editor': 'Jannik Ott',
  'docno': 'https://www.bibsonomy.org/bibtex/2a295018d8ecc0212aca487ae1b0c753e/jhammerb',
  'text': 'GAMMA\\—a high performance dataflow database machine'},
 {'title': 'Performance Driven Database Design for Scalable Web Applications',
  'id': 'https://www.bibsonomy.org/bibtex/2c753bff717eb9632d39e3679f7c269ef/mbruschi',
  'type': 'Publication',
  'url': 'http://dx.doi.org/10.1007/978-3-642-03973-7_5',
  'year': 2009,
  'authors': ['Jozsef Patvarczki', 'Murali Mani', 'Neil Heffernan'],
  'doi': '10.1007/978-3-642-03973-7_5',
  'query': 'database',
  'editor': 'Jannik Ott',
  'docno': 'https://www.bibsonomy.org/bibtex/2c753bff717eb9632d39e3679f7c269ef/mbruschi',
  'text': 'Performance Driven Database Design for Scalable Web Applications'},
 {'title': 'A comparative analysis of methodologies for database schema integration',
  'id': 'https://www.bibsonomy.org/bibtex/22636802d129dbf10d3dc35bdfdc6efb6/gravity',
  'type': 'Publication',
  'url': 'http://portal.acm.org/citation.cfm?doid=27633.27634',
  'year': 1986,
  'authors': ['C. Batini', 'M. Lenzerini', 'S. B. Navathe'],
  'doi': 'http://doi.acm.org/10.1145/27633.27634',
  'query': 'database',
  'editor': 'Jannik Ott',
  'docno': 'https://www.bibsonomy.org/bibtex/22636802d129dbf10d3dc35bdfdc6efb6/gravity',
  'text': 'A comparative analysis of methodologies for database schema integration'},
 {'title': 'A Comparison between Relational Databases and NoSQL Databases',
  'id': 'https://www.bibsonomy.org/bibtex/292e537486422445d574ddbbef9a49300/ijtsrd',
  'type': 'Publication',
  'url': 'http://www.ijtsrd.com/computer-science/database/11214/a-comparison-between-relational-databases-and-nosql-databases/behjat-u-nisa',
  'year': 2018,
  'authors': ['Behjat U Nisa'],
  'doi': None,
  'query': 'database',
  'editor': 'Jannik Ott',
  'docno': 'https://www.bibsonomy.org/bibtex/292e537486422445d574ddbbef9a49300/ijtsrd',
  'text': 'A Comparison between Relational Databases and NoSQL Databases'},
 {'title': 'XML and relational database management systems: the inside story',
  'id': 'https://www.bibsonomy.org/bibtex/26d3b73cfb1b666af1155c893cd37f5d5/malte.wunsch',
  'type': 'Publication',
  'url': 'http://portal.acm.org/citation.cfm?id=1066157.1066298',
  'year': 2005,
  'authors': ['Michael Rys', 'Don Chamberlin', 'Daniela Florescu'],
  'doi': None,
  'query': 'database',
  'editor': 'Jannik Ott',
  'docno': 'https://www.bibsonomy.org/bibtex/26d3b73cfb1b666af1155c893cd37f5d5/malte.wunsch',
  'text': 'XML and relational database management systems: the inside story'},
 {'title': 'The Claremont report on database research',
  'id': 'https://www.bibsonomy.org/bibtex/2c23ca6a7338e9687327054b7d62596bf/sb3000',
  'type': 'Publication',
  'url': 'http://doi.acm.org/10.1145/1516046.1516062',
  'year': 2009,
  'authors': ['Rakesh Agrawal',
   'Anastasia Ailamaki',
   'Philip A. Bernstein',
   'Eric A. Brewer',
   'Michael J. Carey',
   'Surajit Chaudhuri',
   'Anhai Doan',
   'Daniela Florescu',
   'Michael J. Franklin',
   'Hector Garcia-Molina',
   'Johannes Gehrke',
   'Le Gruenwald',
   'Laura M. Haas',
   'Alon Y. Halevy',
   'Joseph M. Hellerstein',

In [55]:
index_folder_mult = "./index_mult"

fields=['docno', 'text', 'tags', 'description']

indexer_mult = pt.IterDictIndexer(index_folder_mult, meta={'docno': 200, 'text': 4096}, overwrite=True)
index_ref_mult = indexer_mult.index(df_dict)

print(f"path to our index: {index_ref_mult.toString()}")

09:34:49.464 [ForkJoinPool-1-worker-1] WARN org.terrier.structures.indexing.Indexer -- Adding an empty document to the index (https://www.bibsonomy.org/bibtex/2998392ade6025286fed26bb09fc3dfc0/bibgreen) - further warnings are suppressed
09:34:49.671 [ForkJoinPool-1-worker-1] WARN org.terrier.structures.indexing.Indexer -- Indexed 2 empty documents
path to our index: ./index_mult/data.properties

In [57]:
index_mult = pt.IndexFactory.of(index_ref_mult)

In [59]:
print(index_mult.getCollectionStatistics().toString())

Number of documents: 3520
Number of terms: 5033
Number of postings: 23460
Number of fields: 1
Number of tokens: 24185
Field names: [text]
Positions:   false

In [61]:
search_engine_mult = pt.terrier.Retriever(index_mult, wmodel="TF_IDF")

In [63]:
res = search_engine_mult.search("intelligence")
res

,qid,docid,docno,rank,score,query
0,1,925,https://www.bibsonomy.org/bibtex/21a61a34d4984...,0,5.184718,intelligence
1,1,1447,https://www.bibsonomy.org/bibtex/2508ce3b4cfd8...,1,5.184718,intelligence
2,1,1234,https://www.bibsonomy.org/bibtex/2326beb667d4c...,2,4.837320,intelligence
3,1,1351,https://www.bibsonomy.org/bibtex/255165fc7f1f9...,3,4.837320,intelligence
4,1,1074,https://www.bibsonomy.org/bibtex/2934ad4d54596...,4,4.533552,intelligence
5,1,3011,https://www.bibsonomy.org/bibtex/2e3677666eee2...,5,4.533552,intelligence
6,1,502,https://www.bibsonomy.org/bibtex/2a9aeedc023b8...,6,4.265681,intelligence
7,1,3274,https://www.bibsonomy.org/bibtex/20bd599a1d3e4...,7,4.265681,intelligence
8,1,3396,https://www.bibsonomy.org/bibtex/2eb29bdfaeb62...,8,4.265681,intelligence
9,1,298,https://www.bibsonomy.org/bibtex/2e01c06213221...,9,4.027699,intelligence
10,1,1344,https://www.bibsonomy.org/bibtex/2a13a19576a30...,10,4.027699,intelligence
11,1,3364,https://www.bibsonomy.org/bibtex/28f08bb5a969f...,11,4.027699,intelligence
12,1,183,https://www.bibsonomy.org/bibtex/24174ad281bc2...,12,3.814868,intelligence
13,1,3504,https://www.bibsonomy.org/bibtex/217e640a5e9c6...,13,3.814868,intelligence
14,1,638,https://www.bibsonomy.org/bibtex/2dada3848a74e...,14,3.623401,intelligence

In [65]:
#save our data
pickle.dump(df_filtered, open("index_mult/df_publications.pkl", "wb"))

In [67]:
#install steamlit
%pip install streamlit

Requirement already satisfied: streamlit in /opt/anaconda3/lib/python3.12/site-packages (1.37.1)
Requirement already satisfied: altair<6,>=4.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (5.0.1)
Requirement already satisfied: blinker<2,>=1.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (1.6.2)
Requirement already satisfied: cachetools<6,>=4.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (5.3.3)
Requirement already satisfied: click<9,>=7.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (8.1.7)
Requirement already satisfied: numpy<3,>=1.20 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (1.26.4)
Requirement already satisfied: packaging<25,>=20 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (24.1)
Requirement already satisfied: pandas<3,>=1.3.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<11,>=7.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (10.4.0)
Requirement already satisfied: protobuf<6,>=3.20 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (4.25.3)
Requirement already satisfied: pyarrow>=7.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (16.1.0)
Requirement already satisfied: requests<3,>=2.27 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (2.32.3)
Requirement already satisfied: rich<14,>=10.14.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (13.7.1)
Requirement already satisfied: tenacity<9,>=8.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (8.2.3)
Requirement already satisfied: toml<2,>=0.10.1 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.3.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (4.11.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (3.1.43)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (0.8.0)
Requirement already satisfied: tornado<7,>=6.0.3 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (6.4.1)
Requirement already satisfied: jinja2 in /opt/anaconda3/lib/python3.12/site-packages (from altair<6,>=4.0->streamlit) (3.1.4)
Requirement already satisfied: jsonschema>=3.0 in /opt/anaconda3/lib/python3.12/site-packages (from altair<6,>=4.0->streamlit) (4.23.0)
Requirement already satisfied: toolz in /opt/anaconda3/lib/python3.12/site-packages (from altair<6,>=4.0->streamlit) (0.12.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /opt/anaconda3/lib/python3.12/site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.7)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.12/site-packages (from pandas<3,>=1.3.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.12/site-packages (from pandas<3,>=1.3.0->streamlit) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.12/site-packages (from pandas<3,>=1.3.0->streamlit) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit) (2024.8.30)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from rich<14,>=10.14.0->streamlit) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/anaconda3/lib/python3.12/site-packages (from rich<14,>=10.14.0->streamlit) (2.15.1)
Requirement already satisfied: smmap<5,>=3.0.1 in /opt/anaconda3/lib/python3.12/site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.12/site-packages (from jinja2->altair<6,>=4.0->streamlit) (2.1.3)
Requirement already satisfied: attrs>=22.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in /opt/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in /opt/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.10.6)
Requirement already satisfied: mdurl~=0.1 in /opt/anaconda3/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit) (0.1.0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.3.0->streamlit) (1.16.0)
Note: you may need to restart the kernel to use updated packages.